### ISSUE TITLE
Error in anvi-setup-pfams

### ISSUE THREAD

**Issue by johanneswerner** [merenlab/anvio#1014]
When I want to run `anvi-setup-pfams`, I get the following error.

```bash
$ anvi-setup-pfams
Current Pfam version on EBI ..................: 32.0 (2018-08)
Database URL .................................: http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release
Downloaded succesfully .......................: /data/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/data/misc/Pfam/Pfam-A.hmm.gz                                                    
Downloaded succesfully .......................: /data/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/data/misc/Pfam/Pfam.version.gz                                                  
Downloaded succesfully .......................: /data/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/data/misc/Pfam/Pfam-A.clans.tsv.gz                                              
Traceback (most recent call last):
  File "/data/miniconda3/envs/anvio/bin/anvi-setup-pfams", line 38, in <module>
    setup.download()
  File "/data/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/pfam.py", line 96, in download
    self.confirm_downloaded_files()
  File "/data/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/pfam.py", line 105, in confirm_downloaded_files
    checksum, file_name = [item.strip() for item in line.strip().split()]
ValueError: too many values to unpack (expected 2)
```

```bash
 anvi-self-test  --version
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

**Comment by ozcan** [comment]
Hi @johanneswerner, 

Thank you for reporting, it seems the file `md5_checksums` is not available in version `32.0`. Maybe it was not a standard file, I will figure this out and make checksum verification optional for downloaded files.

Actually, the download seems successful. If you just decompress two files, `anvi-run-pfams` should work as expected.

```
gunzip /data/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/data/misc/Pfam/Pfam.version.gz
gunzip /data/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/data/misc/Pfam/Pfam-A.clans.tsv.gz
```

`Pfam-A.hmm.gz` does not need to be decompressed, hmmer uses it compressed.

**Comment by meren** [comment]
We may need to do something about this if it is going to happen to everyone :/ Do you think the EBI just changed their file list with 32.0?

**Comment by ozcan** [comment]
It seems that file only exists for version `31.0`. We may ask them to put in `32.0` too, I think it is a necessary feature.

**Comment by meren** [comment]
I am not sure who to ask, but I will ping Rob Finn hoping that he will have a suggestion.

**Comment by jainamistry** [comment]
Hi,

I'm Jaina and I work with Rob Finn on Pfam. I've just generated the md5_checksums file for Pfam 32.0 and put a copy on the ftp site. Apologies for it being missing previously.

Best wishes,

Jaina

**Comment by johanneswerner** [comment]
Thank you for the quick responses and fix.
