### ISSUE TITLE
homebrew install/anvi-db-migrate v5.2 error

### ISSUE THREAD

**Issue by maureenbug** [merenlab/anvio#1075]
Hello,

I've been having trouble getting 5.2 working on my mac.

First off, here's this:
```
mberg-lm:~ mberg$ anvi-self-test --version
Anvi'o version ...............................: margaret (v5.2)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

After installing 5.2, I tried to update my db files, and would get this error message:

```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.3, library is 1.10.4
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
                   HDF5 Version: 1.10.4
                  Configured on: Fri Oct 19 20:07:55 BST 2018
                  Configured by: brew@HighSierra-2.local
                    Host system: x86_64-apple-darwin17.7.0
              Uname information: Darwin HighSierra-2.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
                       Byte sex: little-endian
             Installation point: /usr/local/Cellar/hdf5/1.10.4

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables: 
                        LDFLAGS: 
                     H5_LDFLAGS:  -Wl,-commons,use_dylibs
                     AM_LDFLAGS:  -L/usr/local/opt/szip/lib
                Extra libraries: -lsz -lz -ldl -lm 
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang ( Apple LLVM version 10.0.0 )
                       CPPFLAGS: 
                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/usr/local/opt/szip/include
                        C Flags: 
                     H5 C Flags:     
                     AM C Flags: 
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /usr/local/opt/gcc/bin/gfortran ( GNU Fortran (Homebrew GCC 8.2.0) 8.2.0)
                  Fortran Flags: 
               H5 Fortran Flags:  -pedantic -Wall -Wextra -Wunderflow -Wimplicit-interface -Wsurprising -Wno-c-binding-type  -s -O2
               AM Fortran Flags: 
         Shared Fortran Library: yes
         Static Fortran Library: yes

                            C++: yes
                   C++ Compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ ( Apple LLVM version 10.0.0 )
                      C++ Flags: 
                   H5 C++ Flags:    
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

                           Java: no


Features:
---------
                   Parallel HDF5: no
Parallel Filtered Dataset Writes: no
              Large Parallel I/O: no
              High-level library: yes
                    Threadsafety: no
             Default API mapping: v110
  With deprecated public symbols: yes
          I/O filters (external): deflate(zlib),szip(encoder)
                             MPE: no
                      Direct VFD: no
                         dmalloc: no
  Packages w/ extra debug output: none
                     API tracing: no
            Using memory checker: no
 Memory allocation sanity checks: no
             Metadata trace file: no
          Function stack tracing: no
       Strict file format checks: no
    Optimization instrumentation: no
Bye...
Abort trap: 6
```

I uninstalled anvio (all my previous version) and HDF5, and reinstalled everything... I still get the same problem.

I saw some similar issues on here, and tried to install anvio (homebrew) from the source. However, I get this error message:

```
==> /usr/local/Cellar/anvio/5.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/anvio--matplotlib-20181218-26092-1wiuefs/matplotlib-2.2.3
Last 15 lines from /Users/mberg/Library/Logs/Homebrew/anvio/03.pip:
Removed build tracker '/private/tmp/pip-req-tracker-zbcgcd2o'
Command "/usr/local/Cellar/anvio/5.2/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-nu_n_3l1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-cmkwm5v1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/anvio/5.2/libexec/bin/../include/site/python3.7/matplotlib" failed with error code 1 in /private/tmp/pip-req-build-nu_n_3l1/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 791, in install
    spinner=spinner,
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/anvio/5.2/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-nu_n_3l1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-cmkwm5v1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/anvio/5.2/libexec/bin/../include/site/python3.7/matplotlib" failed with error code 1 in /private/tmp/pip-req-build-nu_n_3l1/
```

The anvi-self-test --suite mini ran fine with the first homebrew install (i.e. not from the source).

Any help is appreciated, thanks in advance!
Maureen

**Comment by ozcan** [comment]
Hey @maureenbug,
Can you try installing with `brew install merenlab/anvio/anvio --build-from-source --verbose` ?

It will take slightly longer than installing pre-built package but it will compile it for your system, so maybe this can solve version mismatch.

Also you may give a shot to conda installation method.
Best,

**Comment by maureenbug** [comment]
Thanks for getting back to me! When I try to install it that way, I get this error:

```
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/openblas:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks:/usr/local/opt/python@2/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/mpfr/lib/pkgconfig:/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/gsl/lib/pkgconfig:/usr/local/opt/openblas/lib/pkgconfig:/usr/local/opt/python@2/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/pkg-config/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python/bin:/usr/local/opt/gcc/bin:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/prodigal/bin:/usr/local/opt/hmmer/bin:/usr/local/opt/gsl/bin:/usr/local/opt/hdf5/bin:/usr/local/opt/diamond/bin:/usr/local/opt/mcl/bin:/usr/local/opt/muscle/bin:/usr/local/opt/lmdb/bin:/usr/local/opt/blast/bin:/usr/local/opt/python@2/bin:/usr/local/opt/numpy/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: merenlab/anvio/anvio 5.2 did not build
Logs:
     /Users/mberg/Library/Logs/Homebrew/anvio/03.pip.cc
     /Users/mberg/Library/Logs/Homebrew/anvio/00.options.out
     /Users/mberg/Library/Logs/Homebrew/anvio/03.pip
     /Users/mberg/Library/Logs/Homebrew/anvio/01.python3
     /Users/mberg/Library/Logs/Homebrew/anvio/02.python3

```

But I went ahead and installed conda so I could install anvio... which worked perfectly, and everything is up and running smoothly. 

Thanks!
