### ISSUE TITLE
ANI calculation error

### ISSUE THREAD

**Issue by carloshenriquezc** [merenlab/anvio#1090]
Hi everyone, 
I am trying to stimate ANI with SAGs, but I receive this message

Traceback (most recent call last):
  File "/home/carlos/anaconda3/envs/anvio5/bin/anvi-compute-ani", line 193, in <module>
    main(args)
  File "/home/carlos/anaconda3/envs/anvio5/bin/anvi-compute-ani", line 120, in main
    linkage=args.linkage, distance=args.distance)
  File "/home/carlos/anaconda3/envs/anvio5/lib/python3.6/site-packages/anvio/clustering.py", line 97, in get_newick_tree_data_for_dict
    newick = get_newick_from_matrix(vectors, distance, linkage, norm, id_to_sample_dict, transpose=transpose)
  File "/home/carlos/anaconda3/envs/anvio5/lib/python3.6/site-packages/anvio/clustering.py", line 109, in get_newick_from_matrix
    vectors = get_normalized_vectors(vectors, norm=norm, progress=progress)
  File "/home/carlos/anaconda3/envs/anvio5/lib/python3.6/site-packages/anvio/clustering.py", line 161, in get_normalized_vectors
    vectors = np.array(vectors, dtype=np.float64)
ValueError: could not convert string to float: 'False'

I use only SAGs with contigs > 1000 b
Thanks,

**Comment by meren** [comment]
@carloshenriquezc, because you simply removed the message which was asking you to mention some details about your installation before sending your issue, now I need to send an extra message to ask you about those. Do you see the waste of time and energy here?

Please read the entirety of the text in "New Issue" window if you would like to try again.
