### ISSUE TITLE
Error when inspecting splits in anvi-interactive

### ISSUE THREAD

**Issue by evelienadri** [merenlab/anvio#1119]
Hi Meren and co,  
  
I'm running anvi-interactive on a contigs database with profiles that I have used and inspected before successfully. I recently got a new computer and upgraded the operating system from iMac 27" and macOS El Capitan to iMac Pro; macOS Mojave version 10.14.3. The Anvi'o version information is as follows:
  
````
Anvi'o version ...............................: margaret (v5.2)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
````
  
In the interactive interface, when I click to inspect a split, I get the following error message on the terminal and the inspect window in my browser keeps trying to load: 
  
```
[08 Mar 19 12:52:53 Recovering variability information for split] ...                                                            Traceback (most recent call last):
  File "/usr/local/Cellar/anvio/5.2/libexec/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/Cellar/anvio/5.2/libexec/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/anvio/bottleroutes.py", line 483, in charts
    split_variability_info_dict = self.interactive.get_variability_information_for_split(split_name, skip_outlier_SNVs=self.args.hide_outlier_SNVs)
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/anvio/dbops.py", line 2420, in get_variability_information_for_split
    split_variability_information = list(profile_db.db.get_some_rows_from_table_as_dict(t.variable_nts_table_name, '''split_name = "%s"''' % split_name, error_if_no_data=False).values())
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/anvio/db.py", line 439, in get_some_rows_from_table_as_dict
    rows = self._exec('''SELECT * FROM %s WHERE %s''' % (table_name, where_clause)).fetchall()
  File "/usr/local/Cellar/anvio/5.2/libexec/lib/python3.7/site-packages/anvio/db.py", line 183, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.DatabaseError: database disk image is malformed
```

Can you advise on how to get this to work? 
 
Thanks,  
Evelien

**Comment by meren** [comment]
It looks like the database file is corrupted. I would suggest you to re-download, or re-generate it from scratch (with `anvi-merge` if it is a merged profile, or with `anvi-profile` if it is a single profile).
