### ISSUE TITLE
anvi-import-collection sqlite3 error

### ISSUE THREAD

**Issue by NVOostende** [merenlab/anvio#1148]
``` 
$ anvi-self-test --version
Anvi'o version ...............................: margaret (v5.4)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```
Hi,
when I try to replicate the Prochlorococcus metapangenomes-workflow I get an error when running the 'anvi-import-collection' script:
```
echo "start importing GENOME-COLLECTION into profile database"
anvi-import-collection ${COLLECT_DIR}/Prochlorococcus-GENOME-COLLECTION.txt \
                       -c ${CONTIG_DIR}/Prochlorococcus-CONTIGS.db \
                       -p ${PROFIL_DIR}/Prochlorococcus-MERGED/PROFILE.db \
                       -C ${COLLECT_DIR}/Genomes
```
which reports the following error:
``` 
start importing GENOME-COLLECTION into profile database
Item names in input ..........................: 2,671
Num bins in input ............................: 31
Traceback (most recent call last):
  File "/tigress/oostende/software/anaconda2/envs/anvio54/bin/anvi-import-collection", line 231, in <module>
    main(args)
  File "/tigress/oostende/software/anaconda2/envs/anvio54/bin/anvi-import-collection", line 97, in main
    db_names = utils.get_all_item_names_from_the_database(args.pan_or_profile_db)
  File "/tigress/oostende/software/anaconda2/envs/anvio54/lib/python3.6/site-packages/anvio/utils.py", line 2211, in get_all_item_names_from_the_database
    all_items = set(database.get_single_column_from_table('mean_coverage_Q2Q3_splits', 'contig'))
  File "/tigress/oostende/software/anaconda2/envs/anvio54/lib/python3.6/site-packages/anvio/db.py", line 317, in get_single_column_from_table
    response = self._exec('''SELECT %s %s FROM %s''' % ('DISTINCT' if unique else '', column, table))
  File "/tigress/oostende/software/anaconda2/envs/anvio54/lib/python3.6/site-packages/anvio/db.py", line 205, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: no such table: mean_coverage_Q2Q3_splits
``` 
The 'Prochlorococcus-GENOME-COLLECTION.txt' table looks fine:
```
$ head Prochlorococcus-GENOME-COLLECTION.txt 
AS9601-00000001_split_00001	AS9601
AS9601-00000001_split_00002	AS9601
AS9601-00000001_split_00003	AS9601
AS9601-00000001_split_00004	AS9601
AS9601-00000001_split_00005	AS9601
AS9601-00000001_split_00006	AS9601
AS9601-00000001_split_00007	AS9601
AS9601-00000001_split_00008	AS9601
AS9601-00000001_split_00009	AS9601
AS9601-00000001_split_00010	AS9601
```
Not sure how to fix this (minor) issue ...

I installed Anvio5.4 using conda:
```
conda install -y --name anvio54 -c conda-forge -c bioconda anvio==5.4.0 "blas=*=openblas" 
```
All the best,
Nicolas

**Comment by ozcan** [comment]
Hi @NVOostende,

It looks like your Merged profile.db corrupted at some point, maybe at merging step, can you run the command below and look at the table names?

`sqlite3 ${PROFIL_DIR}/Prochlorococcus-MERGED/PROFILE.db ".tables"`

**Comment by NVOostende** [comment]
Hi Ozcan,

thanks for your reply.
Not sure what the result should look like, but here it is:
```
$ sqlite3 PROFILE.db ".tables"
collections_bins_info   item_orders             variable_codons       
collections_info        layer_additional_data   variable_nucleotides  
collections_of_contigs  layer_orders            views                 
collections_of_splits   self                  
item_additional_data    states 
```
Does this look ok?

Best,
Nicolas

**Comment by ozcan** [comment]
This profile database looks like it is generated by when you run `anvi-interactive --manual`. How did you generated this profile.db?

**Comment by NVOostende** [comment]
Mmmh, I didn't run this 'anvi-interactive --manual'
Below is the script I used to build the profiles for a bunch of metagenomes, before merging them:

```
echo "### start generating coverage and detection stats for each genome contig in given metagenome ###"
for sample in `awk '{print $1}' ${SAMPLES_DIR}/samples_HOT.txt`
do
        if [ "$sample" == "sample" ]; then continue; fi
        anvi-profile -c ${CONTIG_DIR}/Prochlorococcus-CONTIGS.db \
                -i ${MAPP_DIR}/$sample.bam \
                --min-contig-length 1000 \
                --min-mean-coverage 1 \
                --skip-SNV-profiling \
                --num-threads $NUM_THREADS \
                -o ${PROFIL_DIR}/$sample \
                --sample-name $sample
done

cd ${PROFIL_DIR}

anvi-merge */PROFILE.db \
       -o ${PROFIL_DIR}/Prochlorococcus-MERGED \
       -c ${CONTIG_DIR}/Prochlorococcus-CONTIGS.db
```

**Comment by meren** [comment]
Yes, this profile database looks weird. A merged profile database should look like this:

```
abundance_contigs             mean_coverage_Q2Q3_splits
abundance_splits              mean_coverage_contigs
collections_bins_info         mean_coverage_splits
collections_info              relative_abundance_contigs
collections_of_contigs        relative_abundance_splits
collections_of_splits         self
detection_contigs             states
detection_splits              std_coverage_contigs
item_additional_data          std_coverage_splits
item_orders                   variability_contigs
layer_additional_data         variability_splits
layer_orders                  variable_codons
max_normalized_ratio_contigs  variable_nucleotides
max_normalized_ratio_splits   views
mean_coverage_Q2Q3_contigs
```

@NVOostende, can you please send the output of this command, too:

``` bash
anvi-db-info ${PROFIL_DIR}/Prochlorococcus-MERGED/PROFILE.db
```

**Comment by meren** [comment]
(I think you should also look at your log files to make sure your `anvi-merge` command did run properly and there were no errors).

**Comment by NVOostende** [comment]
Ok, thanks!
Not sure how to output the 'anvi-merge' log files (newbie here), but here goes 'anvi-db-info':
```
$ anvi-db-info PROFILE.db

DB Info (no touch)
===============================================
Database Path ................................: PROFILE.db
Description ..................................: _No description is provided_
Type .........................................: profile
Version ......................................: 31


DB Info (no touch also)
===============================================
anvio ........................................: 5.4
sample_id ....................................: HOTdcm
samples ......................................: HOT_147_Apr03_125m, HOT_148_May03_115m, HOT_149_Jun03_100m, HOT_152_Oct03_100m, HOT_153_Nov03_100m, HOT_158_Apr04_125m, HOT_159_May04_115m, HOT_160_Jun04_125m, HOT_163_Sep04_115m, HOT_164_Oct04_115m, HOT_165_Nov04_100m, HOT_216_Nov09_100m
total_reads_mapped ...........................: 1884653, 2185564, 4756297, 395786, 1299263, 2328457, 624581, 857826, 1013066, 315630, 714473, 3284778
merged .......................................: 1
blank ........................................: 0
items_ordered ................................: 0
default_view .................................: mean_coverage
min_contig_length ............................: 1000
max_contig_length ............................: 9223372036854775807
SNVs_profiled ................................: 0
SCVs_profiled ................................: 0
num_contigs ..................................: 272
num_splits ...................................: 2671
total_length .................................: 54734945
min_coverage_for_variability .................: 10
report_variability_full ......................: 0
contigs_db_hash ..............................: hasha1406090
creation_date ................................: 1556557494.44471

* Please remember that it is never a good idea to change these values. But in some
cases it may be absolutely necessary to update something here, and a programmer
may ask you to run this program and do it. But even then, you should be very
skeptical. For instance, if the programmer asks you to change the values for
'num_contigs', or 'kmer_size', it would mean that they likely hate you and want
you to fail. So please be extremely careful changing any of these values.
```

**Comment by meren** [comment]
Your `anvi-merge` command does not say `--skip-hierarchical-clustering`, but your profile database says `items_ordered: False`.

Something must have gone wrong. Can you please remove the directory `${PROFIL_DIR}/Prochlorococcus-MERGED` and re-run this step manually and post the output here?

```
anvi-merge */PROFILE.db \
       -o ${PROFIL_DIR}/Prochlorococcus-MERGED \
       -c ${CONTIG_DIR}/Prochlorococcus-CONTIGS.db
```

**Comment by NVOostende** [comment]
Hi,
indeed, an error message at the end of 'anvi-merge' tells me that something went wrong while merging the databases: 'The auxiliary database at "HOT_148_May03_115m/AUXILIARY-DATA.db" does not know anything about the split "PAC1-00000019_split_00001"'
Not sure how to fix this issue though ..

Here's the output:
```
48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Reading self tables of each single profile db] ...                                                 ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Layer additional data ops] ...                                                                     ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional keys and data for layers] ...                                                ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional data for layers] ...                                                         ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional keys and data for layers] ...                                                ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional data for layers] ...                                                         ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional keys and data for layers] ...                                                ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional data for layers] ...                                                         ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional keys and data for layers] ...                                                ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional data for layers] ...                                                         ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional keys and data for layers] ...                                                ^[[0m^M                                                                                                                        ^M^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:51 Recovering additional data for layers] ...                                                         ^[[0m^M
..
WARNING
===============================================
Anvi'o just set the normalization values for each sample based on how many
mapped reads they contained. This information will only be used to calculate the
normalized coverage table. Here are those values: HOT_147_Apr03_125m: 0.17,
HOT_148_May03_115m: 0.14, HOT_149_Jun03_100m: 0.07, HOT_152_Oct03_100m: 0.80,
HOT_153_Nov03_100m: 0.24, HOT_158_Apr04_125m: 0.14, HOT_159_May04_115m: 0.51,
HOT_160_Jun04_125m: 0.37, HOT_163_Sep04_115m: 0.31, HOT_164_Oct04_115m: 1.00,
HOT_165_Nov04_100m: 0.44, HOT_216_Nov09_100m: 0.10

profiler_version .............................: 31
output_dir ...................................: /scratch/gpfs/oostende/Anvio_HOT/profile_cov/Prochlorococcus-MERGED
sample_id ....................................: Prochlorococcus_MERGED
description ..................................: None
profile_db ...................................: /scratch/gpfs/oostende/Anvio_HOT/profile_cov/Prochlorococcus-MERGED/PROFILE.db
merged .......................................: True
contigs_db_hash ..............................: hasha1406090
num_runs_processed ...........................: 12
merged_sample_ids ............................: HOT_147_Apr03_125m, HOT_148_May03_115m, HOT_149_Jun03_100m, HOT_152_Oct03_100m, HOT_153_Nov03_100m, HOT_158_Apr04_125m, HOT_159_May04_115m, HOT_160_Jun04_125m, HOT_163_Sep04_115m, HOT_164_Oct04_115m, HOT_165_Nov04_100m, HOT_216_Nov09_100m
Common layer additional data keys ............: default
total_reads_mapped ...........................: 1884653, 2185564, 4756297, 395786, 1299263, 2328457, 624581, 857826, 1013066, 315630, 714473, 3284778
cmd_line .....................................: /tigress/oostende/software/anaconda2/envs/anvio54/bin/anvi-merge HOT_147_Apr03_125m/PROFILE.db HOT_148_May03_115m/PROFILE.db HOT_149_Jun03_100m/PROFILE.db HOT_152_Oct03_100m/PROFILE.db HOT_153_Nov03_100m/PROFILE.db HOT_158_Apr04_125m/PROFILE.db HOT_159_May04_115m/PROFILE.db HOT_160_Jun04_125m/PROFILE.db HOT_163_Sep04_115m/PROFILE.db HOT_164_Oct04_115m/PROFILE.db HOT_165_Nov04_100m/PROFILE.db HOT_216_Nov09_100m/PROFILE.db SAMPLES-MERGED/PROFILE.db -o /scratch/gpfs/oostende/Anvio_HOT/profile_cov/Prochlorococcus-MERGED -c /scratch/gpfs/oostende/Anvio_HOT/contigs_db/Prochlorococcus-CONTIGS.db
clustering_performed .........................: True
^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:52 Merging split coverage data] HOT_147_Apr03_125m/PROFILE.db                                         ^[[0m^M                                                                                                                        ^M^[[48;5;6m^[[38;5;0m^M[30 Apr 19 13:34:52 Merging split coverage data] HOT_148_May03_115m/PROFILE.db                                         ^[[0mTraceback (most recent call last):
  File "/tigress/oostende/software/anaconda2/envs/anvio54/bin/anvi-merge", line 51, in <module>
    merger.MultipleRuns(args).merge()
  File "/tigress/oostende/software/anaconda2/envs/anvio54/lib/python3.6/site-packages/anvio/merger.py", line 532, in merge
    self.merge_split_coverage_data()
  File "/tigress/oostende/software/anaconda2/envs/anvio54/lib/python3.6/site-packages/anvio/merger.py", line 395, in merge_split_coverage_data
    coverages_dict = sample_split_coverage_values.get(split_name)
  File "/tigress/oostende/software/anaconda2/envs/anvio54/lib/python3.6/site-packages/anvio/auxiliarydataops.py", line 116, in get
    raise AuxiliaryDataError('The auxiliary database at "%s" does not know anything about the split "%s"' % (self.db_path, split_name))
anvio.errors.AuxiliaryDataError:

Auxiliary Data Error: The auxiliary database at "HOT_148_May03_115m/AUXILIARY-DATA.db" does not know
                      anything about the split "PAC1-00000019_split_00001"
```

**Comment by meren** [comment]
This is very interesting and should never happen. Can you please send the output of these two commands:

```
anvi-db-info HOT_148_May03_115m/PROFILE.db

anvi-db-info HOT_147_Apr03_125m/PROFILE.db
```

**Comment by NVOostende** [comment]
Ok, good to know! I'm learning a lot here ..
Here's the output:
```
$ anvi-db-info HOT_148_May03_115m/PROFILE.db

DB Info (no touch)
===============================================
Database Path ................................: HOT_148_May03_115m/PROFILE.db
Description ..................................: _No description is provided_
Type .........................................: profile
Version ......................................: 31


DB Info (no touch also)
===============================================
anvio ........................................: 5.4
sample_id ....................................: HOT_148_May03_115m
samples ......................................: HOT_148_May03_115m
merged .......................................: 0
blank ........................................: 0
items_ordered ................................: 0
default_view .................................: single
min_contig_length ............................: 1000
max_contig_length ............................: 9223372036854775807
SNVs_profiled ................................: 0
SCVs_profiled ................................: 0
min_coverage_for_variability .................: 10
report_variability_full ......................: 0
contigs_db_hash ..............................: hasha1406090
creation_date ................................: 1556556642.89538
num_splits ...................................: 2671
num_contigs ..................................: 272
total_length .................................: 54734945
```
```
$ anvi-db-info HOT_147_Apr03_125m/PROFILE.db

DB Info (no touch)
===============================================
Database Path ................................: HOT_147_Apr03_125m/PROFILE.db
Description ..................................: _No description is provided_
Type .........................................: profile
Version ......................................: 31


DB Info (no touch also)
===============================================
anvio ........................................: 5.4
sample_id ....................................: HOT_147_Apr03_125m
samples ......................................: HOT_147_Apr03_125m
merged .......................................: 0
blank ........................................: 0
items_ordered ................................: 0
default_view .................................: single
min_contig_length ............................: 1000
max_contig_length ............................: 9223372036854775807
SNVs_profiled ................................: 0
SCVs_profiled ................................: 0
min_coverage_for_variability .................: 10
report_variability_full ......................: 0
contigs_db_hash ..............................: hasha1406090
creation_date ................................: 1556556598.74008
num_splits ...................................: 2671
num_contigs ..................................: 272
total_length .................................: 54734945
```

**Comment by meren** [comment]
Well. One last question that should help us sort everything out. Can you please copy-paste this entire thing and run it in the same directory:

``` bash
for i in HOT_147_Apr03_125m HOT_148_May03_115m HOT_149_Jun03_100m HOT_152_Oct03_100m HOT_153_Nov03_100m HOT_158_Apr04_125m HOT_159_May04_115m HOT_160_Jun04_125m HOT_163_Sep04_115m HOT_164_Oct04_115m HOT_165_Nov04_100m HOT_216_Nov09_100m
C
do
    echo "* $i: " `sqlite3 $i/AUXILIARY-DATA.db 'select count(*) split_name from split_coverages;'`
done
```

**Comment by meren** [comment]
Well. One last question that should help us sort everything out. Can you please copy-paste this entire thing and run it in the same directory:

``` bash
for i in HOT_147_Apr03_125m HOT_148_May03_115m HOT_149_Jun03_100m HOT_152_Oct03_100m HOT_153_Nov03_100m HOT_158_Apr04_125m HOT_159_May04_115m HOT_160_Jun04_125m HOT_163_Sep04_115m HOT_164_Oct04_115m HOT_165_Nov04_100m HOT_216_Nov09_100m
do
    echo "* $i: " `sqlite3 $i/AUXILIARY-DATA.db 'select count(*) split_name from split_coverages;'`
done
```

**Comment by NVOostende** [comment]
OK, here we go:
```
$ for i in HOT_147_Apr03_125m HOT_148_May03_115m HOT_149_Jun03_100m HOT_152_Oct03_100m HOT_153_Nov03_100m HOT_158_Apr04_125m HOT_159_May04_115m HOT_160_Jun04_125m HOT_163_Sep04_115m HOT_164_Oct04_115m HOT_165_Nov04_100m HOT_216_Nov09_100m
> do
>     echo "* $i: " `sqlite3 $i/AUXILIARY-DATA.db 'select count(*) split_name from split_coverages;'`
> done
* HOT_147_Apr03_125m:  586
* HOT_148_May03_115m:  1619
* HOT_149_Jun03_100m:  1882
* HOT_152_Oct03_100m:  337
* HOT_153_Nov03_100m:  1177
* HOT_158_Apr04_125m:  1856
* HOT_159_May04_115m:  615
* HOT_160_Jun04_125m:  1210
* HOT_163_Sep04_115m:  901
* HOT_164_Oct04_115m:  303
* HOT_165_Nov04_100m:  591
* HOT_216_Nov09_100m:  1872
```

**Comment by meren** [comment]
I don't understand how is this possible, @NVOostende :( All these numbers should have been equal, but they are all over the place. If you still have your BAM files would you mind re-profiling HOT_147_Apr03_125m and HOT_148_May03_115m samples and see if AUXILIARY-DATA.db in them contains the same number of items using the same command?

I have never seen this before, so I would be happy to find out how you ended up there.

**Comment by NVOostende** [comment]
OK, will do (I'll need to sbatch it to the cluster, so hang on). 
Thank you for looking into this!
Nicolas

**Comment by NVOostende** [comment]
OK, I think I know what happened and should've known why 'anvi-merge' didn't work. My mistake!
Thank you for all your help figuring this one out.
Best, 
Nicolas

When generating the profiles, the minimum coverage was not set to zero but 1:
```
for sample in `awk '{print $1}' ${SAMPLES_DIR}/samples_HOT.txt`
do
        if [ "$sample" == "sample" ]; then continue; fi
        anvi-profile -c ${CONTIG_DIR}/Prochlorococcus-CONTIGS.db \
                -i ${MAPP_DIR}/$sample.bam \
                --min-contig-length 1000 \
                --min-mean-coverage 0 \
                --skip-SNV-profiling \
                --num-threads $NUM_THREADS \
                -o ${PROFIL_DIR}/$sample \
                --sample-name $sample
done
```
Setting '--min-mean-coverage' to zero took care of the issue:

```
$ for i in HOT_147_Apr03_125m HOT_148_May03_115m HOT_149_Jun03_100m HOT_152_Oct03_100m HOT_153_Nov03_100m HOT_158_Apr04_125m HOT_159_May04_115m HOT_160_Jun04_125m HOT_163_Sep04_115m HOT_164_Oct04_115m HOT_165_Nov04_100m HOT_216_Nov09_100m
> do
>     echo "* $i: " `sqlite3 $i/AUXILIARY-DATA.db 'select count(*) split_name from split_coverages;'`
> done
* HOT_147_Apr03_125m:  2671
* HOT_148_May03_115m:  2671
* HOT_149_Jun03_100m:  2671
* HOT_152_Oct03_100m:  2671
* HOT_153_Nov03_100m:  2671
* HOT_158_Apr04_125m:  2671
* HOT_159_May04_115m:  2671
* HOT_160_Jun04_125m:  2671
* HOT_163_Sep04_115m:  2671
* HOT_164_Oct04_115m:  2671
* HOT_165_Nov04_100m:  2671
* HOT_216_Nov09_100m:  2671
```
Running 'anvi-merge' worked like a charm this time:
```                                                                                           
^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:47 Reading self tables of each single profile db] ...                          
                       ESC[0m^M                                                                                           
                             ^M^M                                                                                         
                               ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:47 Layer additional data ops] ...               
                                                      ESC[0m^M                                                            
                                                            ^M^M                                                          
                                                              ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:47 Recovering add
itional keys and data for layers] ...                                                ESC[0m^M                             
                                                                                           ^M^M                           
                                                                                             ^MESC[48;5;6mESC[38;5;0m^M[01
 May 19 15:47:47 Recovering additional data for layers] ...                                                         ESC[0m
^M                                                                                                                        
^M^M                                                                                                                      
  ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:47 Recovering additional keys and data for layers] ...                       
                         ESC[0m^M                                                                                         
                               ^M^M                                                                                       
                                 ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:47 Recovering additional data for layers] ... 
                                                        ESC[0m^M                                                          
                                                              ^M^M                                                        
                                                                ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:47 Recovering a
dditional keys and data for layers] ...                                                ESC[0m^M                           
                                                                                             ^M^M                         
                                                                                               ^MESC[48;5;6mESC[38;5;0m^M[
01 May 19 15:47:47 Recovering additional data for layers] ...                                                         ESC[
0m^M                                                                                                                      
  ^M^M                                                                                                                    
    ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:48 Recovering additional keys and data for layers] ...                     
                           ESC[0m^M                                                                                       
                                 ^M^M                                                                                     
                                   ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:48 Recovering additional data for layers] ..
.                                                         ESC[0m^M                                                        
                                                                ^M^M                                                      
                                                                  ^MESC[48;5;6mESC[38;5;0m^M[01 May 19 15:47:48 Recovering
 additional keys and data for layers] ...                                                ESC[0m^M                         
                                                                                               ^M^M                       
....
mapped reads they contained. This information will only be used to calculate the
normalized coverage table. Here are those values: HOT_147_Apr03_125m: 0.17,
HOT_148_May03_115m: 0.14, HOT_149_Jun03_100m: 0.07, HOT_152_Oct03_100m: 0.80,
HOT_153_Nov03_100m: 0.24, HOT_158_Apr04_125m: 0.14, HOT_159_May04_115m: 0.51,
HOT_160_Jun04_125m: 0.37, HOT_163_Sep04_115m: 0.31, HOT_164_Oct04_115m: 1.00,
HOT_165_Nov04_100m: 0.44, HOT_216_Nov09_100m: 0.10

profiler_version .............................: 31
output_dir ...................................: /scratch/gpfs/oostende/Anvio_HOT/profile_cov/Prochlorococcus-MERGED
sample_id ....................................: Prochlorococcus_MERGED
description ..................................: None
profile_db ...................................: /scratch/gpfs/oostende/Anvio_HOT/profile_cov/Prochlorococcus-MERGED/PROFIL
E.db
merged .......................................: True
contigs_db_hash ..............................: hasha1406090
num_runs_processed ...........................: 12
merged_sample_ids ............................: HOT_147_Apr03_125m, HOT_148_May03_115m, HOT_149_Jun03_100m, HOT_152_Oct03_
100m, HOT_153_Nov03_100m, HOT_158_Apr04_125m, HOT_159_May04_115m, HOT_160_Jun04_125m, HOT_163_Sep04_115m, HOT_164_Oct04_11
5m, HOT_165_Nov04_100m, HOT_216_Nov09_100m
Common layer additional data keys ............: default
total_reads_mapped ...........................: 1884653, 2185564, 4756297, 395786, 1299263, 2328457, 624581, 857826, 1013066, 315630, 714473, 3284778
cmd_line .....................................: /tigress/oostende/software/anaconda2/envs/anvio54/bin/anvi-merge HOT_147_Apr03_125m/PROFILE.db HOT_148_May03_115m/PROFILE.db HOT_149_Jun03_100m/PROFILE.db HOT_152_Oct03_100m/PROFILE.db HOT_153_Nov03_100m/PROFILE.db HOT_158_Apr04_125m/PROFILE.db HOT_159_May04_115m/PROFILE.db HOT_160_Jun04_125m/PROFILE.db HOT_163_Sep04_115m/PROFILE.db HOT_164_Oct04_115m/PROFILE.db HOT_165_Nov04_100m/PROFILE.db HOT_216_Nov09_100m/PROFILE.db -o /scratch/gpfs/oostende/Anvio_HOT/profile_cov/Prochlorococcus-MERGED -c /scratch/gpfs/oostende/Anvio_HOT/contigs_db/Prochlorococcus-CONTIGS.db
clustering_performed .........................: True
....
Layer orders added
===============================================
* std_coverage
* mean_coverage
* mean_coverage_Q2Q3
* max_normalized_ratio
* relative_abundance
* detection
* abundance

Data groups added
===============================================
* default (w/1 items)

* Happy ☘
```
```

**Comment by meren** [comment]
Aha! This is very important for us to know. Setting a `--min-mean-coverage` flag potentially changes which contigs from a given contigs database to be characterized in single profile databases as some contigs may have no coverage in some environments, and that leads to a problem in the anvi-merge step as now each auxiliary database contains a random subset of contigs. 

Thank you very much for your patience, @NVOostende. I will enter another issue to address this so instead of a cryptic error message we show the user something intelligible.
