### ISSUE TITLE
anvi-get-short-reads-from-bam broken??

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#1151]
Hi folks,

I'm trying to run `anvi-get-short-reads-from-bam` but the process fails. I tested anvi'o 5.3, 5.4 and 5.5 and all end in the exact same error:

```
$ anvi-get-short-reads-from-bam -p SAMPLES_MERGED/PROFILE.db -c CONTIGS.db -Q -X original_profiles/isoprene_map.sort.bam -C MAGs -b ISORED_MAG_00002 -O ISORED_MAG_00002-reads
Input BAM file(s) ............................: isoprene_map.sort.bam
Collection ID ................................: MAGs
Bin(s) .......................................: ISORED_MAG_00002
Number of splits .............................: 195
[03 May 19 09:49:23 Accessing reads] Reading splits info from the contigs database ...                                                                                Traceback (most recent call last):
  File "/home/xabi/anaconda2/envs/anvi-53/bin/anvi-get-short-reads-from-bam", line 52, in <module>
    r.store_short_reads_for_splits()
  File "/home/xabi/anaconda2/envs/anvi-53/lib/python3.6/site-packages/anvio/bamops.py", line 520, in store_short_reads_for_splits
    short_reds_for_splits_dict = self.get_short_reads_for_splits_dict()
  File "/home/xabi/anaconda2/envs/anvi-53/lib/python3.6/site-packages/anvio/bamops.py", line 431, in get_short_reads_for_splits_dict
    splits_basic_info = contigs_db.db.get_table_as_dict(t.splits_info_table_name)
AttributeError: 'NoneType' object has no attribute 'get_table_as_dict'
```

In all cases, they are conda environments in Ubuntu.

Cheers

**Comment by meren** [comment]
Hey @xvazquezc,

I tried to recapitulate the error. It first worked for me:

``` bash
$ anvi-get-short-reads-from-bam -p SAMPLES-MERGED/PROFILE.db \
                                -c CONTIGS.db \
                                -Q \
                                -X SAMPLE-01.bam \
                                -C CONCOCT \
                                -b Bin_1 \
                                -O ISORED_MAG_00002-reads
Input BAM file(s) ............................: SAMPLE-01.bam
Collection ID ................................: CONCOCT
Bin(s) .......................................: Bin_1
Number of splits .............................: 18
Output file for R1 ...........................: ISORED_MAG_00002-reads_R1.fa.gz
Output file for R2 ...........................: ISORED_MAG_00002-reads_R2.fa.gz
Output file for UNPAIRED .....................: ISORED_MAG_00002-reads_UNPAIRED.fa.gz

Num paired-end reads stored ..................: 0
Num unpaired reads stored ....................: 11,877
```

But then when I tried it like this, I got the same error:

``` bash
$ anvi-get-short-reads-from-bam -p SAMPLES-MERGED/PROFILE.db \
                                -c A_CONTIGS_DB_THAT_DOESNT_EXIST.db \
                                -Q \
                                -X SAMPLE-01.bam \
                                -C CONCOCT \
                                -b Bin_1 \
                                -O ISORED_MAG_00002-reads
Input BAM file(s) ............................: SAMPLE-01.bam
Collection ID ................................: CONCOCT
Bin(s) .......................................: Bin_1
Number of splits .............................: 18
[03 May 19 09:57:42 Accessing reads] Reading splits info from the contigs database ...                                                                                                                     Traceback (most recent call last):
  File "/Users/meren/github/anvio/bin/anvi-get-short-reads-from-bam", line 52, in <module>
    r.store_short_reads_for_splits()
  File "/Users/meren/github/anvio/anvio/bamops.py", line 520, in store_short_reads_for_splits
    short_reds_for_splits_dict = self.get_short_reads_for_splits_dict()
  File "/Users/meren/github/anvio/anvio/bamops.py", line 431, in get_short_reads_for_splits_dict
    splits_basic_info = contigs_db.db.get_table_as_dict(t.splits_info_table_name)
AttributeError: 'NoneType' object has no attribute 'get_table_as_dict'
```

:)

I will fix the code to make sure it checks whether the contigs db is there or not before it gets all the way down here, but I think your fix will be pretty simple on your end to move on for now.

Best,
