### ISSUE TITLE
KeyError with anvi-gen-gene-consensus-sequences

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1157]
```
cd /Users/evan/Software/anvio/anvio/tests/
bash run_variability_mock.sh new
cd sandbox/test-output
echo "1" > genes
anvi-gen-gene-consensus-sequences -p SAMPLES-MERGED/PROFILE.db -c single_contig.db --genes-of-interest genes
```

this leads to the following key error:

```
Traceback (most recent call last):
  File "/Users/evan/Software/anvio/bin/anvi-gen-gene-consensus-sequences", 
line 62, in <module>
    c = variabilityops.ConsensusSequences(args)
  File "/Users/evan/Software/anvio/anvio/variabilityops.py", line 2169, in 
__init__
    NucleotidesEngine.__init__(self, args=args, r=self.run, p=self.progress
)
  File "/Users/evan/Software/anvio/anvio/variabilityops.py", line 1798, in 
__init__
    VariabilitySuper.__init__(self, args=args, r=self.run, p=self.progress)
  File "/Users/evan/Software/anvio/anvio/variabilityops.py", line 593, in _
_init__
    split_names_of_interest = self.get_splits_of_interest(splits_of_interes
t_path=None, split_source="gene_caller_ids")
  File "/Users/evan/Software/anvio/anvio/variabilityops.py", line 822, in g
et_splits_of_interest
    splits_of_interest = list(set([self.gene_callers_id_to_split_name_dict[
g] for g in (self.genes_of_interest or self.gene_caller_ids)]))
  File "/Users/evan/Software/anvio/anvio/variabilityops.py", line 822, in <
listcomp>
    splits_of_interest = list(set([self.gene_callers_id_to_split_name_dict[
g] for g in (self.genes_of_interest or self.gene_caller_ids)]))
KeyError: 1
```

**Comment by meren** [comment]
Ah. PERFECT./

**Comment by ekiefl** [comment]
https://github.com/merenlab/anvio/commit/c6c675cf9e1fbad9512127ba50c77b4537ef4fa9

Very bad temporary fix
