### ISSUE TITLE
anvi-run-pfams fails when there are no hits

### ISSUE THREAD

**Issue by michaelkyu** [merenlab/anvio#1187]
### Anvi'o version

```
$ anvi-self-test --version

Anvi'o version ...............................: margaret (v5.5-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 13
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

I installed `anvio` from the `master` branch on May 6, 2019 (this was the [last commit](https://github.com/merenlab/anvio/commit/4f4d25e00584f4bfa77037f447bdb849fc173073) of my version).

### Data to reproduce issue

Please see the attachment [tmp_anvi_pfam.tar.gz](https://github.com/merenlab/anvio/files/3389211/tmp_anvi_pfam.tar.gz).  The commands I mention below are in `script.sh` and `script_modified.sh`.

### Error description
I have a small sequence (`NZ_CP032847.1.fasta`). I want to create a contigs db and search for pfams with the commands

```
anvi-gen-contigs-database -f NZ_CP032847.1.fa -o NZ_CP032847_1-contigs.db
anvi-run-pfams -c NZ_CP032847_1-contigs.db -T 2
```

However, I get the following error

```
WARNING
===============================================
You did not provide any gene caller ids. As a result, anvi'o will give you back
sequences for every 1 gene call stored in the contigs database.

Output .......................................: /tmp/tmpjaemql9k/AA_gene_sequences.fa

HMM Profiling for Pfam
===============================================
Reference ....................................: unknown
Kind .........................................: unknown
Alphabet .....................................: AA
Context ......................................: GENE
Domain .......................................: N\A
HMM model path ...............................: /share/project/mbm/anvio/anvio/data/misc/Pfam/Pfam-A.hmm.gz
Number of genes ..............................: 17,928
Noise cutoff term(s) .........................: --cut_ga
Number of CPUs will be used for search .......: 2
Temporary work dir ...........................: /tmp/tmp177qorcp
HMM scan output ..............................: /tmp/tmp177qorcp/hmm.output
HMM scan hits ................................: /tmp/tmp177qorcp/hmm.hits
Log file .....................................: /tmp/tmp177qorcp/00_log.txt
Number of raw hits ...........................: 0
Traceback (most recent call last):
  File "/share/project/mbm/anvio/bin/anvi-run-pfams", line 34, in <module>
    pfam.process()
  File "/share/project/mbm/anvio/anvio/pfam.py", line 225, in process
    parser = parser_modules['search']['hmmscan'](hmm_hits_file, alphabet='AA', context='GENE')
  File "/share/project/mbm/anvio/anvio/parsers/hmmscan.py", line 49, in __init__
    Parser.__init__(self, 'HMMScan', [hmm_scan_hits_txt], files_expected, files_structure)
  File "/share/project/mbm/anvio/anvio/parsers/base.py", line 32, in __init__
    self.input_file_names = [os.path.basename(p) for p in input_file_paths]
  File "/share/project/mbm/anvio/anvio/parsers/base.py", line 32, in <listcomp>
    self.input_file_names = [os.path.basename(p) for p in input_file_paths]
  File "/scratch/miniconda/envs/anvio-master-zelda/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I attempted to debug this code and found that
1. There are no Pfam hits in my sequence, this causes `HMMer.run_hmmscan()` to return `None`
2. This `None` result is passed a few times eventually to `os.path.basename`, which gives the final error message of `TypeError: expected str, bytes or os.PathLike object, not NoneType`

To further confirm the root problem is that there are no Pfam hits, I appended to `NZ_CP032847.1.fasta` a random sequence from Pfam, i.e., vav human: [Pfam record](https://pfam.xfam.org/protein/P15498#tabview=tab0) and [nucleotide sequence](https://www.ncbi.nlm.nih.gov/nuccore/NM_005428). My new sequence is `NZ_CP032847.1.modified.fasta`, which should have a Pfam hit. And voila, I get no more errors when I re-run the same commands!

```
anvi-gen-contigs-database -f NZ_CP032847.1.modified.fa -o NZ_CP032847.1.modified-contigs.db
anvi-run-pfams -c NZ_CP032847.1.modified-contigs.db -T 2
```

**Comment by meren** [comment]
This took forever, but I finally addressed it. Sorry for the delay.

This is what happens after the last commit:

![image](https://user-images.githubusercontent.com/197307/66075304-ea0dd500-e520-11e9-9e4a-5178dba20e42.png)

this will be in `v6`.
