### ISSUE TITLE
TypeError for tnseq/inseq tests

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1189]
This is in `master`.

Running `./run_gen_gene_level_stats_tests.sh` after the last commit (1045128c801f1ce25637ca5226442f81bd9913bb) results in the following error:

```
Traceback (most recent call last):
  File "/Users/meren/github/anvio/bin/anvi-interactive", line 108, in <module>
    d = interactive.Interactive(args)
  File "/Users/meren/github/anvio/anvio/interactive.py", line 201, in __init__
    self.load_gene_mode()
  File "/Users/meren/github/anvio/anvio/interactive.py", line 1047, in load_gene_mode
    self.init_gene_level_coverage_stats_dicts()
  File "/Users/meren/github/anvio/anvio/dbops.py", line 2464, in init_gene_level_coverage_stats_dicts
    self.init_gene_level_coverage_stats_from_genes_db(parameters)
  File "/Users/meren/github/anvio/anvio/dbops.py", line 2402, in init_gene_level_coverage_stats_from_genes_db
    self.gene_level_coverage_stats_dict = table_for_gene_level_coverages.read()
  File "/Users/meren/github/anvio/anvio/tables/genelevelcoverages.py", line 159, in read
    data[gene_callers_id][sample_name]['gene_coverage_values_per_nt'] = utils.convert_binary_blob_to_numpy_array(g, 'uint16')
  File "/Users/meren/github/anvio/anvio/utils.py", line 531, in convert_binary_blob_to_numpy_array
    return np.frombuffer(gzip.decompress(blob), dtype=dtype)
  File "/Users/meren/miniconda3/lib/python3.6/gzip.py", line 531, in decompress
    with GzipFile(fileobj=io.BytesIO(data)) as f:
TypeError: a bytes-like object is required, not 'int'
```

Probably an easy fix for @eburgoswisc :)

**Comment by eburgoswisc** [comment]
I can fix it! Also, im getting this error when running gene mode in anvi-interactive. I started working on a fix if thats all right.

```
Traceback (most recent call last):
File "/Users/emanuelburgos/venvs/anvio-master/bin/anvi-interactive", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/emanuelburgos/bioinformatic-modules/anvio/bin/anvi-interactive", line 108, in <module>
    d = interactive.Interactive(args)
  File "/Users/emanuelburgos/bioinformatic-modules/anvio/anvio/interactive.py", line 201, in __init__
    self.load_gene_mode()
  File "/Users/emanuelburgos/bioinformatic-modules/anvio/anvio/interactive.py", line 1045, in load_gene_mode
    ProfileSuperclass.__init__(self, self.args)
  File "/Users/emanuelburgos/bioinformatic-modules/anvio/anvio/dbops.py", line 2308, in __init__
    self.num_mapped_reads_per_sample = {self.p_meta['samples'][i]: int(self.p_meta['total_reads_mapped'][i]) for i in range(0, len(self.p_meta['samples']))}
  File "/Users/emanuelburgos/bioinformatic-modules/anvio/anvio/dbops.py", line 2308, in <dictcomp>
    self.num_mapped_reads_per_sample = {self.p_meta['samples'][i]: int(self.p_meta['total_reads_mapped'][i]) for i in range(0, len(self.p_meta['samples']))}
ValueError: invalid literal for int() with base 10: ','
```

**Comment by meren** [comment]
Sounds great :)

**Comment by eburgoswisc** [comment]
I made some fixes for this issue! Should I open up a new PR? Sorry it took me a bit, I got held up with benchwork :(.

**Comment by meren** [comment]
Thank you, @eburgoswisc! A PR addressing this issue would be the best strategy, I think :)

**Comment by meren** [comment]
Thank you very much, @eburgoswisc. I am testing it right now and realizing there are some necessary changes for this to work. I will associate the commit with this issue so you can take a look later.

**Comment by meren** [comment]
Hey @eburgoswisc, please take a look at the changes I've made in the PR #1193.

Everything is working like a clock now, but one problem remains. There is no way to pass parameters to the computation of the tn-seq stats. That is OK, though, and can wait for someone to complain about it first.
