### ISSUE TITLE
Collection mode in `master` fails to return sequences for HMMs through the right-click menu

### ISSUE THREAD

**Issue by jrunde1** [merenlab/anvio#1198]
```
Traceback (most recent call last):
  File "anvio-master/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "anvio-master/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "anvio-master/anvio/anvio/bottleroutes.py", line 993, in get_hmm_hit_from_bin
    hmm_sequences_dict = self.interactive.hmm_access.get_sequences_dict_for_hmm_hits_in_splits({bin_name: set(self.interactive.collection[bin_name])})
AttributeError: 'Interactive' object has no attribute 'hmm_access'
```

**Comment by ozcan** [comment]
Thanks for reporting Joe,
Now popup appears instead of an error saying `"HMMs for single-copy core genes were not run for this contigs database. "`. If you have run the HMMs and still got this error, that might be another bug.
Best,
