### ISSUE TITLE
fresh install, anvi-self-test fails

### ISSUE THREAD

**Issue by ohthetrees** [merenlab/anvio#1202]
Hello, I'm on Mac OS 10.14.4. I freshly installed conda just for the purpose of installing anvio on this machine, but I'm having problems passing the self test. Thanks in advance for any advice you can offer.

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
sh Miniconda3-latest-MacOSX-x86_64.sh
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create -n anvio anvio
conda activate anvio
anvi-self-test 
```
The output is long, I snipped it:

```
:: Output directory ...

/var/folders/y2/f9078yrx44jfh2wwqjx4m0h00000gn/T/tmpvw70iw4a/test-output



:: Anvo'o version ...

Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1


[SNIP]        


:: Removing HMM hits for Rinke_et_al from the contigs database ...

                                                                                                                                                          
WARNING
===============================================
Previous entries for "Rinke_et_al" is being removed from "hmm_hits_info,
hmm_hits, hmm_hits_in_splits"



:: Export genomic locus using HMM ...

Traceback (most recent call last):
  File "/Users/gabrielle/miniconda3/envs/anvio/bin/anvi-export-locus", line 37, in <module>
    from anvio.splitter import LocusSplitter
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/splitter.py", line 19, in <module>
    import anvio.profiler as profiler
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/profiler.py", line 21, in <module>
    import anvio.clustering as clustering
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/clustering.py", line 8, in <module>
    from sklearn import manifold
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/manifold/__init__.py", line 5, in <module>
    from .locally_linear import locally_linear_embedding, LocallyLinearEmbedding
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/manifold/locally_linear.py", line 17, in <module>
    from ..neighbors import NearestNeighbors
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/neighbors/__init__.py", line 9, in <module>
    from .graph import kneighbors_graph, radius_neighbors_graph
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/neighbors/graph.py", line 7, in <module>
    from .base import KNeighborsMixin, RadiusNeighborsMixin
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/neighbors/base.py", line 18, in <module>
    from ..metrics import pairwise_distances
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/metrics/__init__.py", line 33, in <module>
    from . import cluster
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/metrics/cluster/__init__.py", line 20, in <module>
    from .unsupervised import silhouette_samples
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py", line 12, in <module>
    from ..pairwise import pairwise_distances
  File "/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 30, in <module>
    from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
ImportError: dlopen(/Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/metrics/pairwise_fast.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/gabrielle/miniconda3/envs/anvio/lib/python3.6/site-packages/sklearn/metrics/pairwise_fast.cpython-36m-darwin.so
  Reason: image not found


Config Error: According to the exit code ('1'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the 
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry 
              just a bit less.                           
```

**Comment by ozcan** [comment]
Hi @ohthetrees,

Some people solved the issue by installing the latest version of `scikit-learn`. There are more suggestions on this thread https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/anvio/h-B_6w7kMco/gVk8o2lQBwAJ

```
pip install https://github.com/scikit-learn/scikit-learn/archive/4035e60a6f0a0a2546bf0442ab603961c6a9cc4a.zip```

**Comment by ohthetrees** [comment]
Thanks @ozcan . Can you share any plans for a fix? I would like to keep the install stock and simple, without having to do manual installs.

Thanks,
Cedar

**Comment by smsaladi** [comment]
The following also seems to work:

```
conda create -n anvio35 python=3.5 anaconda
conda install -c bioconda samtools prodigal hmmer sqlite gsl hdf5
pip install anvio
```

sklearn is installed from pip which might be doing the trick.

**Comment by xxz19900** [comment]
Config Error: Some bin names you declared do not appear to be in the collection CONCOCT.




Config Error: According to the exit code ('255'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from  
              the lines above. But if you don't see anything obvious, and especially if the   
              test ended up running until the end with reasonable looking final results, you  
              shouldn't worry too much about this error. Life is short and we all can worry   
              just a bit less.
