### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by alper1976** [merenlab/anvio#1236]
**_Meren's note. I edited this report to remove excess text that should have not been submitted. If you want to enjoy the original version, you can access it by clicking the link above._**

```
:: Anvo'o version ...

Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

```
(...)
:: Populating taxonomy for splits table in the database using 'centrifuge' parser ...

Traceback (most recent call last):
  File "/Users/alexaei/miniconda3/bin/anvi-import-taxonomy-for-genes", line 9, in <module>
    import anvio.parsers as parsers
  File "/Users/alexaei/miniconda3/lib/python3.7/site-packages/anvio/parsers/__init__.py", line 9, in <module>
    from anvio.parsers.krakenuniq import KrakenUniq
  File "/Users/alexaei/miniconda3/lib/python3.7/site-packages/anvio/parsers/krakenuniq.py", line 8, in <module>
    from anvio.parsers.base import Parser
  File "/Users/alexaei/miniconda3/lib/python3.7/site-packages/anvio/parsers/base.py", line 13, in <module>
    from anvio.utils import get_TAB_delimited_file_as_dictionary as get_dict
  File "/Users/alexaei/miniconda3/lib/python3.7/site-packages/anvio/utils.py", line 13, in <module>
    import psutil
  File "/Users/alexaei/miniconda3/lib/python3.7/site-packages/psutil/__init__.py", line 156, in <module>
    from . import _psosx as _psplatform
  File "/Users/alexaei/miniconda3/lib/python3.7/site-packages/psutil/_psosx.py", line 16, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Users/alexaei/miniconda3/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so, 2): Symbol not found: ___CFConstantStringClassReference
  Referenced from: /Users/alexaei/miniconda3/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/alexaei/miniconda3/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so
```

**Comment by ozcan** [comment]
Hi,
Can you try reinstalling psutil using conda or pip?, problem seems to related to psutil module.

Best
