### ISSUE TITLE
Mini-test errror

### ISSUE THREAD

**Issue by hannah18mit** [merenlab/anvio#1242]
```
$ anvi-self-test --version
```

```
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

Using macOS 10.14.6, I just installed fresh versions of miniconda3 on local computer and then installed anvio using:

```
$ conda create -n anvio55 -c conda-forge -c bioconda anvio=5.5.0
```

Everything looked OK. Activated anvio55 then went to run self test using

```
$ anvi-self-test --suite mini
```
Lots of things happen, seems like many steps work, until I get this message:

```
Traceback (most recent call last):
  File "/Users/hgavin/miniconda3/envs/anvio55/bin/anvi-profile", line 5, in <module>
    import anvio.profiler
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/anvio/profiler.py", line 21, in <module>
    import anvio.clustering as clustering
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/anvio/clustering.py", line 8, in <module>
    from sklearn import manifold
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/manifold/__init__.py", line 5, in <module>
    from .locally_linear import locally_linear_embedding, LocallyLinearEmbedding
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/manifold/locally_linear.py", line 17, in <module>
    from ..neighbors import NearestNeighbors
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/neighbors/__init__.py", line 9, in <module>
    from .graph import kneighbors_graph, radius_neighbors_graph
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/neighbors/graph.py", line 7, in <module>
    from .base import KNeighborsMixin, RadiusNeighborsMixin
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/neighbors/base.py", line 18, in <module>
    from ..metrics import pairwise_distances
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/__init__.py", line 33, in <module>
    from . import cluster
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/cluster/__init__.py", line 20, in <module>
    from .unsupervised import silhouette_samples
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/cluster/unsupervised.py", line 12, in <module>
    from ..pairwise import pairwise_distances
  File "/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 30, in <module>
    from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
ImportError: dlopen(/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/pairwise_fast.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/pairwise_fast.cpython-36m-darwin.so
  Reason: image not found
```
Checked the openblas version and it seems up to date:

```
$ conda list
# packages in environment at /Users/hgavin/miniconda3/envs/anvio55:
#
# Name                    Version                   Build  Channel
anvio                     5.5.0                         0    bioconda
anvio-minimal             5.5.0            py36h94a39f0_0    bioconda
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     19.2.0                     py_0    conda-forge
bcftools                  1.9                  h3a161e8_4    bioconda
biopython                 1.74             py36h01d97ff_0    conda-forge
blas                      2.11                   openblas    conda-forge
blast                     2.6.0               boost1.64_2    bioconda
boost                     1.70.0           py36haf112f3_1    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
bottle                    0.12.13                    py_1    conda-forge
bowtie2                   2.3.5            py36h5c9b4e4_0    bioconda
bwa                       0.7.17               h2573ce8_6    bioconda
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
centrifuge                1.0.4_beta      py36pl526ha92aebf_2    bioconda
certifi                   2019.6.16                py36_1    conda-forge
cffi                      1.12.3           py36hccf1714_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cherrypy                  8.0.0                    py36_0    conda-forge
colored                   1.3.93                     py_0    conda-forge
configargparse            0.13.0                     py_1    conda-forge
cryptography              2.7              py36h212c5bf_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
datrie                    0.8              py36h01d97ff_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
diamond                   0.9.26               hf79dc1e_0    bioconda
django                    2.0.8                    py36_0    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
ete3                      3.1.1                      py_1    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
gsl                       2.4               ha2d443c_1006    conda-forge
h5py                      2.10.0          nompi_py36h6248fd5_100    conda-forge
hdf5                      1.10.5          nompi_h0cbb7df_1103    conda-forge
hmmer                     3.2.1                h0a44026_1    bioconda
htslib                    1.9                  h3a161e8_7    bioconda
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.7                   py36_1002    conda-forge
illumina-utils            2.6                        py_0    bioconda
iqtree                    1.6.12               h2dec4b4_0    bioconda
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.2                    py36_0    conda-forge
kiwisolver                1.1.0            py36h770b8ee_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                         0    conda-forge
libcxxabi                 9.0.0                         0    conda-forge
libdeflate                1.0                  h1de35cc_1    bioconda
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               11_openblas    conda-forge
liblapacke                3.8.0               11_openblas    conda-forge
libopenblas               0.3.6                hd44dcd8_6    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libxcb                    1.13              h1de35cc_1002    conda-forge
libxml2                   2.9.9                h12c6b28_5    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
lxml                      4.4.1            py36h08abf6f_0    conda-forge
matplotlib                2.2.3                    py36_1    conda-forge
matplotlib-base           2.2.3            py36hd64abcd_1    conda-forge
mcl                       14.137          pl526h470a237_4    bioconda
megahit                   1.2.8                hfbae3c0_0    bioconda
mistune                   0.8.1            py36h638d0ca_0
mummer                    3.23                          8    bioconda
muscle                    3.8.1551             h04f5b5a_4    bioconda
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.17.2           py36h6b0580a_0    conda-forge
openblas                  0.3.6                hd44dcd8_6    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pandas                    0.25.1           py36h86efe34_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
pip                       19.2.3                   py36_0    conda-forge
prodigal                  2.6.3                         1    bioconda
psutil                    5.4.3                    py36_0    conda-forge
pthread-stubs             0.4               h1de35cc_1001    conda-forge
pyani                     0.2.7            py36h24bf2e0_1    bioconda
pycparser                 2.19                     py36_1    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py36h2a560b1_4    conda-forge
pyrsistent                0.15.4           py36h01d97ff_0    conda-forge
pysam                     0.15.2           py36h1719d13_3    bioconda
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.7             h94afb7f_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-levenshtein        0.12.0          py36h01d97ff_1001    conda-forge
pytz                      2019.2                     py_0    conda-forge
pyyaml                    5.1.2            py36h01d97ff_0    conda-forge
qt                        5.9.7                h8cf7e54_3    conda-forge
ratelimiter               1.2.0                 py36_1000    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.20.0                py36_1000    conda-forge
samtools                  1.9                 h8aa4d43_12    bioconda
scikit-learn              0.19.2           py36hebd9d1a_0
scipy                     1.3.1            py36hab3da7d_2    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
sip                       4.19.8          py36h0a44026_1000    conda-forge
six                       1.11.0                py36_1001    conda-forge
snakemake-minimal         5.2.4                    py36_0    bioconda
sqlite                    3.29.0               hb7d70f7_1    conda-forge
statsmodels               0.9.0           py36h917ab60_1000    conda-forge
tabulate                  0.8.3                      py_0    conda-forge
tbb                       2019.8               h770b8ee_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
tornado                   6.0.3            py36h01d97ff_0    conda-forge
trimal                    1.4.1                h04f5b5a_3    bioconda
urllib3                   1.23                  py36_1001    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
wrapt                     1.11.2           py36h01d97ff_0    conda-forge
xorg-kbproto              1.0.7             h1de35cc_1002    conda-forge
xorg-libice               1.0.10               h01d97ff_0    conda-forge
xorg-libsm                1.2.3             h01d97ff_1000    conda-forge
xorg-libx11               1.6.8                h01d97ff_0    conda-forge
xorg-libxau               1.0.9                h1de35cc_0    conda-forge
xorg-libxdmcp             1.1.3                h01d97ff_0    conda-forge
xorg-libxext              1.3.4                h01d97ff_0    conda-forge
xorg-libxrender           0.9.10            h01d97ff_1002    conda-forge
xorg-renderproto          0.11.1            h1de35cc_1002    conda-forge
xorg-xextproto            7.3.0             h1de35cc_1002    conda-forge
xorg-xproto               7.0.31            h1de35cc_1007    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge
```
Also tried installing scikit-learn using:

```
$ conda install -c conda-forge scikit-learn
```
Finally tried a fix from a different github thread in case the problem was openblas:

```
$ conda create -n anvio55 -c conda-forge -c bioconda anvio=5.5.0 "blas=*=openblas"
```

However, I'm still getting the same error pasted above. 

```
ImportError: dlopen(/Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/pairwise_fast.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/hgavin/miniconda3/envs/anvio55/lib/python3.6/site-packages/sklearn/metrics/pairwise_fast.cpython-36m-darwin.so
  Reason: image not found
```

Help/insights??

**Comment by meren** [comment]
We will soon have a new version that hopefully will address these anvi'o-independent installation issues that usually stem from conda and python version.

We are very sorry for not being able to help more at the moment. Thank you very much for your interest.
