### ISSUE TITLE
Help needed to test new functional enrichment program

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1244]
We have a new functional enrichment program on the branch `functional_enrichment_v6`, and @adw96 and I need your help in testing it.

After you checkout this branch like this:

```
git checkout functional_enrichment_v6
```

You can download a data package from here (alternatively, you can use your own pangenome if you want :-)):

https://drive.google.com/file/d/1crwvvDpK_AqC2ngivcZfETOyj7brDhPL/view?usp=sharing

Unzip the data folder and `cd` into it:

```bash
tar -xzvf TEST-PACKAGE.tar.gz
cd TEST-PACKAGE
```

And then run the enrichment test:

```bash
anvi-get-enriched-functions-per-pan-group -p PAN.db \
                                          -g GENOMES.db \
                                          -o Functional_enrichment_2_groups.txt \
                                          --category-variable light \
                                          --annotation-source COG_FUNCTION
```

This takes about 30 seconds to run on my local.

And then please [contact me](mailto:alon.shaiber@gmail.com) to let me know what you get. Thank you!

**Comment by efogarty11** [comment]
hey @ShaiberAlon this is the error message I got when I ran it on my local on that branch.

```bash
Traceback (most recent call last):
  File "/Users/efogarty/virtual-envs/anvio-master/bin/anvi-get-enriched-functions-per-pan-group", line 4, in <module>
    __import__('pkg_resources').run_script('anvio===5.4-master', 'anvi-get-enriched-functions-per-pan-group')
  File "/Users/efogarty/virtual-envs/anvio-master/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/efogarty/virtual-envs/anvio-master/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/Users/efogarty/virtual-envs/anvio-master/lib/python3.7/site-packages/anvio-5.4_master-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/anvi-get-enriched-functions-per-pan-group", line 56, in <module>
    groupD.add_argument(*anvio.A('min-function-enrichment'), **anvio.K('min-function-enrichment'))
  File "/Applications/anvio/anvio/__init__.py", line 1994, in A
    return D[param_id][0]
KeyError: 'min-function-enrichment'
```

**Comment by ShaiberAlon** [comment]
@efogarty11, thank you! But it looks like you are not on the correct branch.

**Comment by ivagljiva** [comment]
Hi @ShaiberAlon, I have tested this on a small pangenome (only 13 genomes), and it worked perfectly. It took less than 10 seconds to run. This is what I did:
```
anvi-get-enriched-functions-per-pan-group -p 03_PAN/PAN.db -g 03_PAN/GENOMES.db -o enriched_functions_host.txt --category-variable host --annotation-source COG_FUNCTION
```
And here is the output:
```
Genomes storage .............................................: Initialized (storage hash: hash9916e56f)                              
Num genomes in storage ......................................: 13
Num genomes will be used ....................................: 13
Pan DB ......................................................: Initialized: 03_PAN/PAN.db (v. 13)
Gene cluster homogeneity estimates ..........................: Functional: [YES]; Geometric: [YES]; Combined: [NO]
                                                                                                                                     
* Gene clusters are initialized for all 2140 gene clusters in the database.

Category ....................................................: host                                                                  
Functional annotation source ................................: COG_FUNCTION
Functions enrichment summary ................................: enriched_functions_host.txt  
```
Let me know if you need anything else :)

**Comment by ShaiberAlon** [comment]
@ivagljiva , thank you so much for doing this! but it doesn't look like you used the branch `functional_enrichment_v6 `. Could you repeat this after you checkout this branch?

**Comment by ivagljiva** [comment]
@ShaiberAlon, success! I finally managed to install the required conda packages. The command works now!
`anvi-get-enriched-functions-per-pan-group -p 03_PAN/PAN.db -g 03_PAN/GENOMES.db -o enriched_functions_host.txt --category-variable host --annotation-source COG_FUNCTION`

Output:
```
Genomes storage .............................................: Initialized (storage hash: hash9916e56f)                  
Num genomes in storage ......................................: 13
Num genomes will be used ....................................: 13
Pan DB ......................................................: Initialized: 03_PAN/SFB_PANGENOME-PAN.db (v. 13)
Gene cluster homogeneity estimates ..........................: Functional: [YES]; Geometric: [YES]; Combined: [NO]
                                                                                                                         
* Gene clusters are initialized for all 2140 gene clusters in the database.

Category ....................................................: host                                                      
Functional annotation source ................................: COG_FUNCTION
Exclude ungrouped ...........................................: False
Functional occurrence summary ...............................: /var/folders/g0/l73rg2d95nn2l41qtp3r2zkw0000gn/T/tmptg4a9e9f
Functional enrichment summary log file: .....................: /var/folders/g0/l73rg2d95nn2l41qtp3r2zkw0000gn/T/tmpwt8v6mz2
Functional enrichment summary ...............................: enriched_functions_host.txt
```

**Comment by ShaiberAlon** [comment]
@ivagljiva , that's great! Thank you so much for doing this!

**Comment by ShaiberAlon** [comment]
Closing this, since I got what I needed (the error is reproduced and documented here: #1248, and also we see that when people manage to run it (i.e. Iva :-) ) then they get an appropriate output.
