### ISSUE TITLE
[solved] anvi-compute-completeness fails with TypeError

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1257]
Version:
```
anvi-self-test --version
Anvi'o version ...............................: esther (v6)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```
 
```
Traceback (most recent call last):
  File "/Users/trigodet/anvio-master/anvio/bin/anvi-compute-completeness", line 84, in <module>
    compute_completeness(args)
  File "/Users/trigodet/anvio-master/anvio/bin/anvi-compute-completeness", line 60, in compute_completeness
    p_completion, p_redundancy, domain, domain_probabilities, info_text, results_dict = completeness.get_info_for_splits(splits_of_interest, min_e_value = args.min_e_value)
  File "/Users/trigodet/anvio-master/anvio/anvio/completeness.py", line 389, in get_info_for_splits
    best_matching_domain, domain_probabilities, control_domains, info_text = self.get_best_matching_domain(scg_hmm_hits, observed_genes_per_domain, bin_name)
  File "/Users/trigodet/anvio-master/anvio/anvio/completeness.py", line 186, in get_best_matching_domain
    domain_probabilities, actual_domains, control_domains = self.SCG_domain_predictor.predict_from_observed_genes_per_domain(observed_genes_per_domain)
  File "/Users/trigodet/anvio-master/anvio/anvio/scgdomainclassifier.py", line 267, in predict_from_observed_genes_per_domain
    domain_probabilities = dict(zip(self.rf.classes, self.rf.classifier.predict_proba([features_vector])[0]))
  File "/Users/trigodet/virtual-envs/anvio-master/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 581, in predict_proba
    n_jobs, _, _ = _partition_estimators(self.n_estimators, self.n_jobs)
  File "/Users/trigodet/virtual-envs/anvio-master/lib/python3.6/site-packages/sklearn/ensemble/base.py", line 153, in _partition_estimators
    n_jobs = min(_get_n_jobs(n_jobs), n_estimators)
  File "/Users/trigodet/virtual-envs/anvio-master/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 464, in _get_n_jobs
    if n_jobs < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'```

**Comment by meren** [comment]
This happens because the `sklearn` version you have installed in your environment is not the version anvi'o `v6` wants to work with.

Please run this command in your anvi'o environment, and it will solve this issue:

```
pip install scikit-learn==0.21.2
```

**Comment by meren** [comment]
To make sure you have all the right versions of every Python package, you can also do this:

```
wget https://raw.githubusercontent.com/merenlab/anvio/v6/requirements.txt
pip install -r requirements.txt
rm requirements.txt
```

This will make sure every Python package in your environment matches to `v6`.

**Comment by FlorianTrigodet** [comment]
This solves it! 
Thank you very much Meren
