### ISSUE TITLE
[solved] PyANI fails on self-test conda install stable v6

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#1258]
Hi! I realize this was covered at least partly in a previous issue [(#1227 )](https://github.com/merenlab/anvio/issues/1227) however since this is a new release I thought it was important. 

I was testing a fresh v6 install on both a mac and Centos server. I installed the stable version using the [Installation with conda (painless method suggested for everyone)](http://merenlab.org/2016/06/26/installation-v2/#installation-with-conda-painless-method-suggested-for-everyone) recipe. 

`anvi-self-test --suite mini` ran fine without error but on both installs `anvi-self-test --suite full` failed at the PyANI step.  The error was the same for both systems. This is from the log file...

```
# DATE: 11 Oct 19 16:45:03
# CMD LINE: average_nucleotide_identity.py --outdir output --indir /var/folders/j3/2b3k8fj96vg5jlj0yr8z0j900000gn/T/tmp71yvktos -$
Traceback (most recent call last):
  File "/Users/rad/miniconda3/envs/anvio-6/bin/average_nucleotide_identity.py", line 804, in <module>
    results = methods[args.method][0](infiles, org_lengths)
  File "/Users/rad/miniconda3/envs/anvio-6/bin/average_nucleotide_identity.py", line 574, in unified_anib
    fraglengths=fraglengths, mode=args.method)
  File "/Users/rad/miniconda3/envs/anvio-6/lib/python3.6/site-packages/pyani/anib.py", line 382, in process_blast
    resultvals = parse_blast_tab(blastfile, fraglengths, mode)
  File "/Users/rad/miniconda3/envs/anvio-6/lib/python3.6/site-packages/pyani/anib.py", line 431, in parse_blast_tab
    data = pd.DataFrame.from_csv(filename, header=None, sep='\t')
AttributeError: type object 'DataFrame' has no attribute 'from_csv'
```

```
(anvio-6) Js-MacBook-Pro:~ rad$ anvi-self-test --version
Anvi'o version ...............................: esther (v6)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

```
(anvio-6) [scottjj@hydra-login02 ~]$ anvi-self-test --version
Anvi'o version ...............................: esther (v6)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

**Comment by meren** [comment]
hey @jarrodscott, can you please send the output of this?

``` bash
$ python -c 'import pandas; print(pandas.__version__)'
```

It should say `0.23.1` as per the [`requirements.txt`](https://github.com/merenlab/anvio/blob/master/requirements.txt)

**Comment by jarrodscott** [comment]
hum, looks like it installed 0.25.1. I ran `pip install pandas==0.23.1` and got this...

```
 :: anvi'o v6 ::  ~ >>> pip install pandas==0.23.1
Collecting pandas==0.23.1
  Using cached https://files.pythonhosted.org/packages/5d/45/4d62347c2ce66eb13f05f47b0337d4a5f70bb826e9937668e4593764f545/pandas-0.23.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: numpy>=1.9.0 in ./miniconda3/envs/anvio-6/lib/python3.6/site-packages (from pandas==0.23.1) (1.17.2)
Requirement already satisfied: python-dateutil>=2.5.0 in ./miniconda3/envs/anvio-6/lib/python3.6/site-packages (from pandas==0.23.1) (2.8.0)
Requirement already satisfied: pytz>=2011k in ./miniconda3/envs/anvio-6/lib/python3.6/site-packages (from pandas==0.23.1) (2019.3)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/anvio-6/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas==0.23.1) (1.11.0)
ERROR: anvio 6 requires h5py==2.8.0, which is not installed.
ERROR: anvio 6 has requirement cherrypy==8.9.1, but you'll have cherrypy 8.0.0 which is incompatible.
ERROR: anvio 6 has requirement django==2.0.10, but you'll have django 2.0.8 which is incompatible.
Installing collected packages: pandas
  Found existing installation: pandas 0.25.1
    Uninstalling pandas-0.25.1:
      Successfully uninstalled pandas-0.25.1
Successfully installed pandas-0.23.1

```

**Comment by jarrodscott** [comment]
what happened to `h5py`? anyway after reinstalling pandas I ran `anvi-self-test --suite full` and this time it looks like it cleared the PyANI step but she still needed the new R packages installed.  So I installed

`conda install -c bioconda bioconductor-qvalue`
'conda install -c r r-tidyverse'
`conda install -c conda-forge r-optparse`

and then ran `anvi-self-test --suite full` and it finished on the mac without a problem. on the linux it complained that `tidyverse, qvalue` were not installed but says `# All requested packages already installed.` when i try to install again. curious.
I am going to try a fresh v6 stable install :). 

for the record this is off the `master` install...
```
 :: anvi'o v6 master ::  ~ >>> python -c 'import cherrypy; print(cherrypy.__version__)'
8.9.1
 :: anvi'o v6 master ::  ~ >>> python -c 'import pandas; print(pandas.__version__)'
0.23.1
 :: anvi'o v6 master ::  ~ >>> python -c 'import h5py; print(h5py.__version__)'
2.8.0
 :: anvi'o v6 master ::  ~ >>> python -c 'import django; print(django.__version__)'
2.0.10
```

**Comment by jarrodscott** [comment]
Just for the 'fun' of it I tried this...
`conda install anvio=6 diamond=0.9.14 pandas==0.23.1` but got yelled at.

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package pandas conflicts for:
anvio=6 -> anvio-minimal==6 -> pyani==0.2.7 -> pandas[version='>=0.14']
anvio=6 -> anvio-minimal==6 -> pandas==0.25.1
anvio=6 -> anvio-minimal==6 -> pyani==0.2.7 -> seaborn -> pandas[version='>=0.14.0']
pandas==0.23.1
```

**Comment by meren** [comment]
> what happened to `h5py`?

anvi'o has no longer a dependency for `HDF` :)

> for the record this is off the master install...

now the output perfectly matches to our `requirements.txt` :)

**Comment by meren** [comment]
I'll keep these issues open so if people end up here the next few days they can see how we resolved things. thank you very much @jarrodscott!

**Comment by jarrodscott** [comment]
rad

**Comment by hannah18mit** [comment]
Thanks @jarrodscott and @meren !!

**Comment by MassiMolari** [comment]
Thanks @jarrodscott and @meren !!
