### ISSUE TITLE
argparse error when using an unknown flag with anvi-merge

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1277]
On Midway, using anvi-master, if you add a flag to `anvi-merge` that isn't a recognized flag, it gives this error instead of a friendly anvi'o error:
```
Traceback (most recent call last):
  File "/Users/alonshaiber/github/anvio/bin/anvi-merge", line 49, in <module>
    args = anvio.get_args(parser)
  File "/Users/alonshaiber/github/anvio/anvio/__init__.py", line 47, in get_args
    parser.add_argument(f, action='store_true')
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1367, in add_argument
    return self._add_action(action)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1730, in _add_action
    self._optionals._add_action(action)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1571, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1381, in _add_action
    self._check_conflict(action)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1520, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1529, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --force: conflicting option string: --force
```

I found this error when I mistakenly used a `-p` flag in front of the profiles to merge.

I technically discovered this error using anvi-5.5, but Alon got the same error when using anvi-master. Unfortunately though this means I don't have example files for you. :(

**Comment by meren** [comment]
I don't get to reproduce this. This is what I run:

```
anvi-merge -c CONTIGS.db -p SAMPLE-02/PROFILE.db SAMPLE-03/PROFILE.db
```

And this was the output:

```
usage: anvi-merge [-h] -c CONTIGS_DB [-o DIR_PATH] [-S NAME]
                  [--description TEXT_FILE] [--skip-hierarchical-clustering]
                  [--enforce-hierarchical-clustering]
                  [--distance DISTANCE_METRIC] [--linkage LINKAGE_METHOD] [-W]
                  [--version] [--debug] [--force]
                  SINGLE_PROFILES) [SINGLE_PROFILE(S ...]
anvi-merge: error: unrecognized arguments: -p
```

**Comment by watsonar** [comment]
Ah. I can't reproduce it on master, either. @ShaiberAlon maybe it was some strange Midway phenomenon?
