### ISSUE TITLE
Problem when upgrading old anvi'o files 

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1298]
Tom, using anvi'o V6.1.

I recently upgraded CONTIG and PROFILE databases corresponding to the ~1000 MAGs we published in 2018 regarding TARA Oceans, and I got this error message when trying to visualize the data in the interactive interface:

```
anvi-interactive -c CONTIGS.db -p PROFILE.db
Contigs DB ...................................: Initialized: CONTIGS.db (v. 14)
Interactive mode .............................: full
[14 Nov 19 11:44:02 Initializing the profile database superclass] Setting profile self data dict                                                               Traceback (most recent call last):
  File "/Users/tomdelmonttdelmont/miniconda3/bin/anvi-interactive", line 115, in <module>
    d = interactive.Interactive(args)
  File "/Users/tomdelmonttdelmont/miniconda3/lib/python3.6/site-packages/anvio/interactive.py", line 214, in __init__
    self.load_full_mode()
  File "/Users/tomdelmonttdelmont/miniconda3/lib/python3.6/site-packages/anvio/interactive.py", line 947, in load_full_mode
    ProfileSuperclass.__init__(self, self.args)
  File "/Users/tomdelmonttdelmont/miniconda3/lib/python3.6/site-packages/anvio/dbops.py", line 2330, in __init__
    total_reads_mapped = [int(num_reads) for num_reads in self.p_meta['total_reads_mapped'].split(',')]
KeyError: 'total_reads_mapped'
```

Here I simply report the error,

Thanks to the developers for looking into this. 

Best regards,

Tom

**Comment by meren** [comment]
Hey Tom,

Can you please try this in `master`? Your up-to-date profile databases should now work properly.
