### ISSUE TITLE
anvi-setup-pfams OSError

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1318]
On master (reproducible on midway meren master virtual env):

```bash
anvi-setup-pfams
Traceback (most recent call last):
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-setup-pfams", line 39, in <module>
    setup.get_remote_version()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/pfam.py", line 79, in get_remote_version
    content = read_remote_file(self.database_url + '/Pfam.version.gz')
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/pfam.py", line 47, in read_remote_file
    return fg.read().decode('utf-8')
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<h')
```

**Comment by ozcan** [comment]
Good catch @ekiefl , `b'<h'` gives a clue that URL returned a html page which should not happen as the file url still accessible `http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam.version.gz`. So I assume this was an error on server or something like like captive portal (wifi login page etc.) interfering with the connection.
I will add exception to this part and ask user to re-try and maybe show more of the content of the HTML page to inform user.
