### ISSUE TITLE
Possible new bug: anvi-display-pan "ModuleNotFoundError: No module named 'numba'"

### ISSUE THREAD

**Issue by jaybake5** [merenlab/anvio#1375]
```
anvi-self-test --version
Anvi'o version ...............................: esther (v6.1-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```
Hello Anvi'o team!

The latest update to the master version appears to have broken `anvi-display-pan`:

```
$ anvi-display-pan --help
Traceback (most recent call last):
  File "/usr/local/projdata/0718/projects/jon/conda_envs/github/anvio/bin/anvi-display-pan", line 12, in <module>
    import anvio.utils as utils
  File "/usr/local/projdata/0718/projects/jon/conda_envs/github/anvio/anvio/utils.py", line 27, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'
```

**Comment by mschecht** [comment]
Hi @jaybake5, please run `pip install numba==0.48.0` and see if that fixes the problem.

**Comment by jaybake5** [comment]
Yup, seems to be working now!
