### ISSUE TITLE
Sklearn issue (profiling, generating genomes storage)

### ISSUE THREAD

**Issue by cdiazmun** [merenlab/anvio#1417]
```
Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

I installed anvio-6.2 some weeks ago and I saw this error when running 
```anvi-self-test --suite mini```

```
:: Contigs DB is ready; here are the tables in it: ...

collections_bins_info      hmm_hits
collections_info           hmm_hits_in_splits
collections_of_contigs     hmm_hits_info
collections_of_splits      kmer_contigs
contig_sequences           kmer_splits
contigs_basic_info         nt_position_info
gene_amino_acid_sequences  scg_taxonomy
gene_functions             self
genes_in_contigs           splits_basic_info
genes_in_splits            splits_taxonomy
genes_taxonomy             taxon_names


:: Profiling sample SAMPLE-01 ...

Traceback (most recent call last):
  File "/opt/miniconda2/envs/anvio-6.2/bin/anvi-profile", line 5, in <module>
    import anvio.profiler as profiler
  File "/opt/miniconda2/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 24, in <module>
    import anvio.clustering as clustering
  File "/opt/miniconda2/envs/anvio-6.2/lib/python3.6/site-packages/anvio/clustering.py", line 8, in <module>
    from sklearn import manifold
  File "/opt/miniconda2/envs/anvio-6.2/lib/python3.6/site-packages/sklearn/__init__.py", line 83, in <module>
    from .utils._show_versions import show_versions
  File "/opt/miniconda2/envs/anvio-6.2/lib/python3.6/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS
```
As I already had anvio5.5 installed I did something nasty and copied the sklearn package from anvio5.5 to the folder of anvio6.2. And the problem was solved and I thought I was happy. But of course the problem came back again recently when running

```anvi-self-test --suite pangenomics```
Giving the exact same error than this one previously reported by Tom: 
https://github.com/merenlab/anvio/issues/1293

I don't know if this issue tells you something and if it can be solved or not, but anyway I report it here in case someone else has this problem also. 

Thank you in advance.

**Comment by meren** [comment]
Hi @cdiazmun, thanks for the report.

It seems the first error is due to a bad installation, and the second is a follow-up error also related to installation. I'm not sure of there is anything we can offer (other than an installation recipe, which exists online :)).


Best,
