### ISSUE TITLE
Cryptic Snakemake error in anvi'o workflows for poorly formatted input files

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#1420]
heyo :) 

I was trying to run a snakemake workflow, and I'm getting this error:

```
Traceback (most recent call last):
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-run-workflow", line 77, in <module>
    main(args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-run-workflow", line 50, in main
    M.init()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/workflows/metagenomics/__init__.py", line 161, in init
    self.samples_information = pd.read_csv(self.samples_txt_file, sep='\t', index_col=False)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 950, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 937, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2132, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 32, saw 4
```

This is the command I ran: 
```bash
anvi-run-workflow -w metagenomics -c config.json --additional-params --cluster "clusterize -j={rule} -o={log} -n={threads} -x" --jobs 50 --resource nodes=50 --latency-wait 100 -n
```

As far as I can tell, my fasta.txt, samples.txt and config.json are all standard for the snakemake workflows that I'm running. If you need any more info lmk!

The directory that I ran it in is posted on slack on the thread for this issue. Thank you!

**Comment by efogarty11** [comment]
Ooopsie, so turns out I had an extra tabs in a few lines of the samples.txt. If it's possible to make it so that a non-programmer readable error appears that'd be awesome, but defs not critical :)
