### ISSUE TITLE
anvi-estimate-metabolism and --kegg-data-dir fails with --external-genomes Config Error

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#1461]
Hi! 

Odd little problem. For some reason when I run `anvi-estimate-metabolism --external-genomes external-genomes.txt -O output.txt --kegg-data-dir /PATH/to/DB` I get an error. See below for the error  with `--debug` flag. The odd thing is that I can run the command every other way with `--kegg-data-dir`. For example, using one of the genomes from the `--external-genomes` file works fine like this: `anvi-estimate-metabolism -c _Arcobacter_porcinus_117434-contigs.db  --kegg-data-dir /PATH/to/DB -O output.txt` (INPUT 1). Works with contig.db in metagenome mode (INPUT 1), with a profile.db and a collection/bin (INPUT 2). 

I tried setting path variables before running the command (`KEGG`, `kegg_data_dir`, `kegg_modules_db_path`, `kegg_modules_db`, etc)...No luck. Always defaults back to `data/misc/KEGG`. Although I am not sure this would ever work :) 

The only way I could get it to work was changing line 207 of `kegg.py` from `data/misc/KEGG` to my db path.

 If this is really a bug, sorry I can't offer a real solution :/

```
:: anvi'o v6 master ::  >>> anvi-estimate-metabolism -e arco-phylo-external-genomes.txt  --kegg-data-dir /pool/genomics/stri_istmobiome/dbs/kegg-kofams/ -O arco-phylo-esitimate-metabolism.txt --debug

Num Contigs DBs in file ......................: 76
Metagenome Mode ..............................: False
Completeness threshold: single estimator .....: 0.75
[03 Jul 20 18:57:23 Estimating metabolism for contigs DBs] [1 of 76] _Arcobacter_porcinus_117434                                                                           ETA: ∞:∞:∞
✖ anvi-estimate-metabolism encountered an error after 0:00:21.187645

Traceback for debugging
================================================================================
  File "/home/scottjj/github/anvio/bin/anvi-estimate-metabolism", line 92, in <module>
    main(args)
  File "/home/scottjj/github/anvio/anvio/terminal.py", line 748, in wrapper
    program_method(*args, **kwargs)
  File "/home/scottjj/github/anvio/bin/anvi-estimate-metabolism", line 39, in main
    m.estimate_metabolism()
  File "/home/scottjj/github/anvio/anvio/kegg.py", line 2916, in estimate_metabolism
    kegg_metabolism_superdict_multi, ko_hits_superdict_multi = self.get_metabolism_superdict_multi()
  File "/home/scottjj/github/anvio/anvio/kegg.py", line 2737, in get_metabolism_superdict_multi
    metabolism_super_dict[metagenome_name], ko_hits_super_dict[metagenome_name] = KeggMetabolismEstimator(args, progress=progress_quiet, run=run_quiet).estimate_metabolism(skip_storing_data=True)
  File "/home/scottjj/github/anvio/anvio/kegg.py", line 1300, in __init__
    "you now know what you need to do to make this message go away." % ("MODULES.db", self.kegg_data_dir))
================================================================================


Config Error: It appears that a modules database (MODULES.db) does not exist in the KEGG data
              directory /home/scottjj/github/anvio/anvio/data/misc/KEGG. Perhaps you need to
              specify a different KEGG directory using --kegg-data-dir. Or perhaps you didn't
              run `anvi-setup-kegg-kofams`, though we are not sure how you got to this point
              in that case since you also cannot run `anvi-run-kegg-kofams` without first
              having run KEGG setup. But fine. Hopefully you now know what you need to do to
              make this message go away.

```

```
 :: anvi'o v6 master ::  ~ >>> anvi-self-test --version
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 34
Contigs DB version ...........................: 18
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
```

**Comment by ivagljiva** [comment]
@jarrodscott You have indeed stumbled upon a bug! Thank you very much for bringing this to our attention. :) 

The error occurred because I forgot to initialize the `--kegg-data-dir` parameter in multiple input cases. Rather silly, but it is now fixed, so if you update your master branch and try again, I believe it should work now.

Please let me know if you have any further issues!

**Comment by jarrodscott** [comment]
@ivagljiva success! Thanks for getting this sorted out soooooo fast :)

**Comment by jzrapp** [comment]
Hi @ivagljiva,

getting closer to actually estimating the metabolism in my data. But there are a few things that came up on the way.

I'm working on two co-assemblies for which I created MAGs - one fairly small dataset, one very big. For the smaller one, I ran 

`anvi-run-kegg-kofams -c contigs.db -T 10` without a problem, but for the larger one, the job finished despite config errors along the way. Here is an example of the job log:

```
Output .......................................: /tmp/pbstmp.11697689/tmpzz6lir8b/AA_gene_sequences.fa

HMM Profiling for KOfam
===============================================
Reference ....................................: unknown
Kind .........................................: unknown
Alphabet .....................................: AA
Context ......................................: GENE
Domain .......................................: N/A
HMM model path ...............................: /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm
Number of genes in HMM model .................: 21,785
Noise cutoff term(s) .........................: None
Number of CPUs will be used for search .......: 10
HMMer program used for search ................: hmmsearch
Temporary work dir ...........................: /tmp/pbstmp.11697689/tmpt4es1kuy
Log file for thread 0 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.0_log
Log file for thread 1 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1_log
Log file for thread 2 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2_log
Log file for thread 3 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.3_log
Log file for thread 4 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.4_log
Log file for thread 5 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5_log
Log file for thread 6 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.6_log
Log file for thread 7 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7_log
Log file for thread 8 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.8_log
Log file for thread 9 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.9_log

                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:18:11 Processing] Running hmmsearch in 10 threads...                                                   

  [0mException in thread Thread-3:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2'                       



Exception in thread Thread-2:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1'                       



Exception in thread Thread-8:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7'                       



Exception in thread Thread-6:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5'                       




                                                                                                                        
Number of raw hits ...........................: 8,150,628

                                                                                                                        
Number of weak hits removed ..................: 8,009,752
Number of hits in annotation dict  ...........: 140,876
Gene functions ...............................: 140876 function calls from 1
                                                sources (KOfam) for 136257
                                                unique gene calls has been added
                                                to the contigs database.
Gene functions ...............................: 31091 function calls from 1
                                                sources (KEGG_Module) for 30295
                                                unique gene calls has been added
                                                to the contigs database.
Gene functions ...............................: 31091 function calls from 1
                                                sources (KEGG_Class) for 30295
                                                unique gene calls has been added
                                                to the contigs database.
```

So now, I assume that my output result is incomplete, but the job still finished..  Do you have an idea of how to avoid this?

Also, it would be great if there was a way to specify to run anvi-run-kegg-kofams only on a subset of contigs that are included in a collection in order to reduce run-time (if someone really only wants to use this functionality to apply the estimate metabolism function on a group of MAGs).
