### ISSUE TITLE
[BUG] KeyError when trying to open anvi-interactive in collection mode

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1473]
## Short description of the problem

When I try to open anvi-interactive in collection mode using a contigs.db, profile.db, and collection that I have successfully used in the past, I get a KeyError.

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 34
Contigs DB version ...........................: 18
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
```

## System info

I'm using anvi-master on a Linux system.

## Detailed description of the issue

Command and output, including error:
```bash
$ anvi-interactive -c 03_CONTIGS/CP-contigs.db -p 07_MERGED_RERUN/CP/PROFILE.db -C CP_MAGs_collection
Contigs DB ...................................: Initialized: 03_CONTIGS/CP-contigs.db (v. 18)
Splits taxonomy ..............................: Initiated for taxonomic level for "t_genus"
Interactive mode .............................: collection

WARNING
===============================================
ProfileSuperClass found a collection focus, which means it will be initialized
using only the splits in the profile database that are affiliated with the
collection CP_MAGs_collection and all bins it describes.

Auxiliary Data ...............................: Found: 07_MERGED_RERUN/CP/AUXILIARY-DATA.db (v. 2)
Profile Super ................................: Initialized with 21741 of 58731 splits: 07_MERGED_RERUN/CP/PROFILE.db (v. 34)

THE MORE YOU KNOW 🌈
===============================================
Someone asked the Contigs Superclass to initialize only a subset of contig
sequences. Usually this is a good thing and means that some good code somewhere
is looking after you. Just for your information, this class will only know 17578
contig sequences instead of all th things in the database.

[21 Jul 20 13:24:00 Filtering contig sequences] Filtering out shorter contigs                                                                                                        Traceback (most recent call last):
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-interactive", line 120, in <module>
    d = interactive.Interactive(args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/interactive.py", line 229, in __init__
    self.load_collection_mode()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/interactive.py", line 818, in load_collection_mode
    self.load_full_mode()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/interactive.py", line 965, in load_full_mode
    self.init_split_sequences(min_contig_length=self.p_meta['min_contig_length'])
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/dbops.py", line 331, in init_split_sequences
    contigs_shorter_than_M = self.init_contig_sequences(min_contig_length)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/dbops.py", line 320, in init_contig_sequences
    self.contig_sequences.pop(contig_name)
KeyError: 'CP_000000071532'
```

## Files to reproduce

I will comment on this issue in the Meren Lab Slack github channel with the paths to recreate this. :)

**Comment by meren** [comment]
Can you try again, @watsonar? Sorry for the inconvenience.

**Comment by watsonar** [comment]
The error is gone! Thank you so much :D
