### ISSUE TITLE
Installing anvio 6.2 in Ubuntu 14.04 with conda 4.8.4

### ISSUE THREAD

**Issue by DianaKarina** [merenlab/anvio#1489]
Hi Anvio community,

I am trying to install anvio 6.2 following the instructions with conda, but when running the minitest I get the following error:

:: Profiling sample SAMPLE-01 ...

Traceback (most recent call last):
  File "/home/diana/miniconda3/envs/anvio-6.2/bin/anvi-profile", line 5, in <module>
    import anvio.profiler as profiler
  File "/home/diana/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 24, in <module>
    import anvio.clustering as clustering
  File "/home/diana/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/clustering.py", line 8, in <module>
    from sklearn import manifold
  File "/home/diana/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/sklearn/__init__.py", line 81, in <module>
    from .utils._show_versions import show_versions
  File "/home/diana/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS

Config Error: According to the exit code ('1'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the 
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry 
              just a bit less.  

Any insights are really welcomed!

Thank you,
Diana

**Comment by meren** [comment]
Hi Diana,

It seems downgrading sklearn through conda to version `0.20.3` will solve this issue:

https://github.com/scikit-learn/scikit-learn/issues/14485

**Comment by DianaKarina** [comment]
Thank you Meren! With your suggestion, the mini-test worked perfectly!
