### ISSUE TITLE
[BUG] anvi-compute-genome-similarity - AttributeError: module 'anvio' has no attribute 'summarizer'

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1507]
## Short description of the problem

When running `anvi-compute-genome-similarity` with an internal genomes file and pan db, I receive an attribute error: `AttributeError: module 'anvio' has no attribute 'summarizer'`

## anvi'o version
```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 18
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
```

## System info

I am using the Meren lab's UChicago midway partition.

## Detailed description of the issue

Here is my command and its complete output:
```
$ anvi-compute-genome-similarity --internal-genomes internal-genomes.txt \
                                 -o 03_PAN/XXX-ANI-OUTPUT \
                                 -p 03_PAN/XXX-PAN.db

CITATION
===============================================
Anvi'o will use 'PyANI' by Pritchard et al. (DOI: 10.1039/C5AY02550H) to compute
ANI. If you publish your findings, please do not forget to properly credit their
work.

[PyANI] Num threads to use ...................: 1
[PyANI] Alignment method .....................: ANIb
[PyANI] Log file path ........................: /tmp/jobs/4702303/tmpy_mh8cwr


✖ anvi-compute-genome-similarity encountered an error after 0:00:03.106331
Traceback (most recent call last):
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-compute-genome-similarity", line 121, in <module>
    main(args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/terminal.py", line 840, in wrapper
    program_method(*args, **kwargs)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-compute-genome-similarity", line 35, in main
    d.process()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/genomesimilarity.py", line 1014, in process
    self.temp_dir = directory if directory else self.get_fasta_sequences_dir()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/genomesimilarity.py", line 776, in get_fasta_sequences_dir
    self.name_to_temp_path = utils.create_fasta_dir_from_sequence_sources(self.genome_desc, self.fasta_txt)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/utils.py", line 2457, in create_fasta_dir_from_sequence_sources
    args = anvio.summarizer.ArgsTemplateForSummarizerClass()
AttributeError: module 'anvio' has no attribute 'summarizer'
```

## Files to reproduce

I will put the midway directory and full command to reproduce this error in a comment on this issue in the Meren lab github channel.

Thank you friends ❤️

**Comment by meren** [comment]
Thank you for your report :) Can you please try again, @watsonar?

**Comment by watsonar** [comment]
@meren it worked perfectly, thank you! :D
