### ISSUE TITLE
[BUG] anvi-get-enriched-functions-per-pan-group produces KeyError: 'GC_00000001'

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1533]
## Short description of the problem
I get a KeyError when I run `anvi-get-enriched-functions-per-pan-group`.

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 19
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
tRNA-seq DB version ..........................: 1
```

## System info

I'm using the Meren lab's UChicago midway partition.

## Detailed description of the issue

Here is the anonymized command and its complete output:
```bash
anvi-get-enriched-functions-per-pan-group -p 03_PAN_KOFAM/BUGS-KOs-PAN.db \
                                          -g 03_PAN_KOFAM/BUGS-KOs-GENOMES.db \
                                          --category colonizer \
                                          --annotation-source KOfam \
                                          -o enriched_functions_KOfam.txt
```
```
Genomes storage .............................................: Initialized (storage hash: hashe99fa91e)
Num genomes in storage ......................................: 34
Num genomes will be used ....................................: 34
Pan DB ......................................................: Initialized: 03_PAN_KOFAM/BUGS-KOs-PAN.db (v. 14)
Gene cluster homogeneity estimates ..........................: Functional: [YES]; Geometric: [YES]; Combined: [YES]

* Gene clusters are initialized for all 5384 gene clusters in the database.

[21 Oct 20 16:41:21 Summarizing "KOfam" for gene clusters] Creating a dictionary
Traceback (most recent call last):
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-get-enriched-functions-per-pan-group", line 73, in <module>
    main(args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-get-enriched-functions-per-pan-group", line 38, in main
    s.functional_enrichment_stats()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/summarizer.py", line 376, in functional_enrichment_stats
    self.functional_occurrence_stats()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/summarizer.py", line 474, in functional_occurrence_stats
    gene_clusters_functions_summary_dict = self.get_gene_clusters_functions_summary_dict(functional_annotation_source)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/dbops.py", line 1606, in get_gene_clusters_functions_summary_dict
    gene_clusters_functions_summary_dict[gene_cluster]['gene_cluster_function'] = function
KeyError: 'GC_00000001'
```
## Files to reproduce

The files and command to reproduce this issue will be in a comment on this post in the github channel of the Meren lab Slack.

Thank you as always. 💖

**Comment by meren** [comment]
Can you please try again with an up-to-date `main`, @watsonar?

Thank you :)

**Comment by meren** [comment]
(and please let me know if it doesn't work)

**Comment by watsonar** [comment]
It works now! Thank you so much!! 😁
