### ISSUE TITLE
[Technical Problem] Config Error: List index out of range during anvi-setup-kegg-kofams

### ISSUE THREAD

**Issue by jzrapp** [merenlab/anvio#1554]
## Short description of the problem

Dear anvio team, @ivagljiva and @meren,

I'm trying to play with your new estimate-metabolism functionality, and in order to do so setup kegg kofams. However, the setup keeps getting interrupted when it gets to Parsing KEGG Module M00006.

## anvi'o version
```
anvi-self-test --version
```

Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 19
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
tRNA-seq DB version ..........................: 1

## System info
I'm working on a remote server and followed the instructions for a conda setup for Linux/Windows users to install the anvio master branch

```
conda create -y --name anvio-master python=3.6
conda activate anvio-master

conda install -y -c conda-forge -c bioconda prodigal \
                 mcl \
                 muscle \
                 hmmer \
                 diamond==0.9.14 \
                 blast \
                 megahit \
                 bowtie2 \
                 bwa \
                 samtools \
                 centrifuge \
                 trimal \
                 iqtree \
                 fastani \
                 fasttree \
                 r-base \
                 r-stringi \
                 r-tidyverse \
                 r-magrittr \
                 r-optparse \
                 bioconductor-qvalue \
                 trnascan-se


# setup the code directory and get the anvi'o codebase
mkdir -p ~/github && cd ~/github/
git clone --recursive https://github.com/meren/anvio.git

cd ~/github/anvio/
pip install -r requirements.txt

#while still in anvio env, copy this:

cat <<EOF >${CONDA_PREFIX}/etc/conda/activate.d/anvio.sh
export PYTHONPATH=\$PYTHONPATH:~/github/anvio/
export PATH=\$PATH:~/github/anvio/bin:~/github/anvio/sandbox
echo -e "\033[1;34mUpdating from the master repository in GitHub \033[0;31m(press CTRL+C to cancel)\033[0m ..."
cd ~/github/anvio && git pull && cd -
EOF


echo -e "\n# >>> ANVI'O STUFF >>>" >> ~/.bash_profile
echo 'alias anvi-activate-master="conda activate anvio-master"' >> ~/.bash_profile
echo "# <<< ANVI'O STUFF <<<" >> ~/.bash_profile
source ~/.bash_profile

```

## Detailed description of the issue

I'm attempting to do
` anvi-setup-kegg-kofams`

Everything is downloaded successfully..

#Kofam Profile Database URL ...................: ftp://ftp.genome.jp/pub/db/kofam
#Downloaded successfully ......................: /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/ko_list.gz                                          
#Downloaded successfully ......................: /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/profiles.tar.gz                                     
#KEGG Module Database URL .....................: http://rest.kegg.jp/get                                                                                     
#Downloaded successfully ......................: /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/modules.keg                                         
#Number of KEGG Modules .......................: 419  
#KEGG Pathway Database URL ....................: http://rest.kegg.jp/get
#Downloaded successfully ......................: /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/pathways.keg                                        
#Number of KEGG Pathways ......................: 445  

But then this happens:

[11 Nov 20 08:22:11 Loading 419 KEGG modules into Modules DB...] Parsing KEGG Module M00006                                                                list index out of range

✖ anvi-setup-kegg-kofams encountered an error after 0:29:48.791304

Config Error: While attempting to build the MODULES.db, anvi'o encountered an error, which    
              should be printed above. If you look at that error and it seems like something  
              you cannot handle, please contact the developers for assistance, as it may be   
              possible that a recent update to KEGG has broken our setup process. If that is  
              the case, we may be able to provide you with a legacy KEGG data archive that you
              can use to set up KEGG with the --kegg-archive flag, while we try to fix things.
              :)                                                                              

<img width="1104" alt="Screen Shot 2020-11-11 at 3 20 25 PM" src="https://user-images.githubusercontent.com/16957339/98822956-c3171780-2431-11eb-8525-46abf5294cb2.png">

Could you help on that? I don't understand what the list index error means to be honest.. 
Thanks a lot!

Josephine

**Comment by ivagljiva** [comment]
Hi @jzrapp, thank you very much for testing this tool, and also for this very detailed bug report :) 

This was probably caused by a recent update to KEGG. I am looking into it now.

**Comment by ivagljiva** [comment]
Indeed, this bug was caused by the 'REFERENCE' lines in the module files `M00006` and `M00007`. Typically these lines have a `PMID` in the subsequent field, but these two modules, for some reason, no longer have this:
```
iva $ grep REFERENCE KEGG/modules/*
data/misc/KEGG/modules/M00006:REFERENCE
data/misc/KEGG/modules/M00007:REFERENCE
data/misc/KEGG/modules/M00013:REFERENCE   PMID:24497638
data/misc/KEGG/modules/M00040:REFERENCE   PMID:22554242
data/misc/KEGG/modules/M00040:REFERENCE   PMID:22303258
[...]
```

I have fixed our parsing function so that it no longer fails in these circumstances. The setup should now work. 

@jzrapp Please run `git pull` in your local anvi'o folder and then try `anvi-setup-kegg-kofams --reset`; let me know if you have any further issues.

**Comment by meren** [comment]
The perks of working directly with the dynamic upstream data :)

Thank you very much for your patience, @jzrapp, and thank you for fixing it so quickly, @ivagljiva!

**Comment by jzrapp** [comment]
Thanks a lot, @ivagljiva, for looking into this so quickly! And shout out to the whole team for never letting me wait on any issue for more than one day.. I'm so impressed! 
I'm rerunning it now, and will reach out in case your fix didn't solve my issue!

**Comment by jzrapp** [comment]
Hi @ivagljiva,

getting closer to actually estimating the metabolism in my data. But there are a few things that came up on the way.

I'm working on two co-assemblies for which I created MAGs - one fairly small dataset, one very big. For the smaller one, I ran 

`anvi-run-kegg-kofams -c contigs.db -T 10` without a problem, but for the larger one, the job finished despite config errors along the way. Here is an example of the job log:

```
Modules database .............................: An existing database,
                                                /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/MODULES.db,
                                                has been loaded.
Kegg Modules .................................: 419 found

CITATION
===============================================
Anvi'o will annotate your database with the KEGG KOfam database, as described in
Aramaki et al (doi:10.1093/bioinformatics/btz859) When you publish your
findings, please do not forget to properly credit this work.


                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Setting contigs self data dict                                             [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Reading **ALL** data from `splits basic info` table :(                     [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Reading **ALL** data from `genes in splits` table :(                       [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Reading **ALL** data from `contigs basic info` table :(                    [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Reading **ALL** data from `genes in contigs` table :(                      [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Reading **ALL** entries in the nucleotide positions info table :(          [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Populating gene lengths dict                                               [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Populating contig name to gene IDs dict                                    [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Identifying HMM searches for single-copy genes and others                  [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Generating "split name" to "gene entry ids" mapping dict                   [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:15:10 Loading the contigs DB] Generating "gene caller id" to "split name" mapping dict                   [0m
                                                                                                                        
Contigs DB ...................................: Initialized: contigs.db (v. 19)

WARNING
===============================================
You did not provide any gene caller ids. As a result, anvi'o will give you back
sequences for every 1297088 gene call stored in the contigs database. Brace
yourself.


                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:16:43 Loading contig sequences] Reading **ALL** data from `contig sequences` table :(                    [0m
                                                                                                                        

                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:16:59 Filtering contig sequences] Identifying contigs shorter than M                                     [0m
                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:16:59 Filtering contig sequences] Filtering out shorter contigs                                          [0m
                                                                                                                        

                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:17:20 Working on sequences data structure] ...                                                           [0m
                                                                                                                        

                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:17:24 Storing sequences] ...                                                                             [0m
                                                                                                                        

WARNING
===============================================
Gene caller IDs 1297088, 1297089, 1297090, 1297091, 1297092, 1297093, 1297094,
1297095, 1297096, 1297097, 1297098, 1297099, 1297100, 1297101, 1297102, 1297103,
1297104, 1297105, 1297106, 1297107, 1297108, 1297109, 1297110, 1297111, 1297112,
1297113, 1297114, 1297115, 1297116, 1297117, 1297118, 1297119, 1297120, 1297121,
1297122, 1297123, 1297124, 1297125, 1297126, 1297127, 1297128, 1297129, 1297130,
1297131, 1297132, 1297133, 1297134, 1297135, 1297136, 1297137, 1297138, 1297139,
1297140, 1297141, 1297142, 1297143, 1297144, 1297145, 1297146, 1297147, 1297148,
1297149, 1297150, 1297151, 1297152, 1297153, 1297154, 1297155, 1297156, 1297157,
1297158, 1297159, 1297160, 1297161, 1297162, 1297163, 1297164, 1297165, 1297166,
1297167, 1297168, 1297169, 1297170, 1297171, 1297172, 1297173, 1297174, 1297175,
1297176, 1297177, 1297178, 1297179, 1297180, 1297181, 1297182, 1297183, 1297184,
1297185, 1297186, 1297187, 1297188, 1297189, 1297190, 1297191, 1297192, 1297193,
1297194, 1297195, 1297196, 1297197, 1297198, 1297199, 1297200, 1297201, 1297202,
1297203, 1297204, 1297205, 1297206, 1297207, 1297208, 1297209, 1297210, 1297211,
1297212, 1297213, 1297214, 1297215, 1297216, 1297217, 1297218, 1297219, 1297220,
1297221, 1297222, 1297223, 1297224, 1297225, 1297226, 1297227, 1297228, 1297229,
1297230, 1297231, 1297232, 1297233, 1297234, 1297235, 1297236, 1297237, 1297238,
1297239, 1297240, 1297241, 1297242, 1297243, 1297244, 1297245, 1297246, 1297247,
1297248, 1297249, 1297250, 1297251, 1297252, 1297253, 1297254, 1297255, 1297256,
1297257, 1297258, 1297259, 1297260, 1297261, 1297262, 1297263, 1297264, 1297265,
1297266, 1297267, 1297268, 1297269, 1297270, 1297271, 1297272, 1297273, 1297274,
1297275, 1297276, 1297277, 1297278, 1297279, 1297280, 1297281, 1297282, 1297283,
1297284, 1297285, 1297286, 1297287, 1297288, 1297289, 1297290 have empty AA
sequences and skipped.

Output .......................................: /tmp/pbstmp.11697689/tmpzz6lir8b/AA_gene_sequences.fa

HMM Profiling for KOfam
===============================================
Reference ....................................: unknown
Kind .........................................: unknown
Alphabet .....................................: AA
Context ......................................: GENE
Domain .......................................: N/A
HMM model path ...............................: /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm
Number of genes in HMM model .................: 21,785
Noise cutoff term(s) .........................: None
Number of CPUs will be used for search .......: 10
HMMer program used for search ................: hmmsearch
Temporary work dir ...........................: /tmp/pbstmp.11697689/tmpt4es1kuy
Log file for thread 0 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.0_log
Log file for thread 1 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1_log
Log file for thread 2 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2_log
Log file for thread 3 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.3_log
Log file for thread 4 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.4_log
Log file for thread 5 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5_log
Log file for thread 6 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.6_log
Log file for thread 7 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7_log
Log file for thread 8 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.8_log
Log file for thread 9 ........................: /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.9_log

                                                                                                                        
[48;5;6m[38;5;0m
[12 Nov 20 13:18:11 Processing] Running hmmsearch in 10 threads...                                                   

  [0mException in thread Thread-3:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.2'                       



Exception in thread Thread-2:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.1'                       



Exception in thread Thread-8:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.7'                       



Exception in thread Thread-6:
Traceback (most recent call last):
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/users/PAA0034/jzrapp/.conda/envs/anvio-master/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/drivers/hmmer.py", line 264, in hmmer_worker
    utils.run_command(cmd_line, log_file)
  File "/users/PAA0034/jzrapp/github/anvio/anvio/utils.py", line 462, in run_command
    raise ConfigError("Command failed to run. What command, you say? This: '%s'" % ' '.join(cmdline))
anvio.errors.ConfigError: 

Config Error: Command failed to run. What command, you say? This: 'hmmsearch -o              
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5_output --cpu 1 --tblout
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5_table                  
              /users/PAA0034/jzrapp/github/anvio/anvio/data/misc/KEGG/HMMs/Kofam.hmm         
              /tmp/pbstmp.11697689/tmpt4es1kuy/AA_gene_sequences.fa.5'                       




                                                                                                                        
Number of raw hits ...........................: 8,150,628

                                                                                                                        
Number of weak hits removed ..................: 8,009,752
Number of hits in annotation dict  ...........: 140,876
Gene functions ...............................: 140876 function calls from 1
                                                sources (KOfam) for 136257
                                                unique gene calls has been added
                                                to the contigs database.
Gene functions ...............................: 31091 function calls from 1
                                                sources (KEGG_Module) for 30295
                                                unique gene calls has been added
                                                to the contigs database.
Gene functions ...............................: 31091 function calls from 1
                                                sources (KEGG_Class) for 30295
                                                unique gene calls has been added
                                                to the contigs database.

* Cleaning up the temp directory (you can use `--debug` if you would like to keep
it for testing purposes)


✓ anvi-run-kegg-kofams took 11:58:13.754329

```

So now, I assume that my output result is incomplete, but the job still finished..  Do you have an idea of how to avoid this?

Also, it would be great if there was a way to specify to run anvi-run-kegg-kofams only on a subset of contigs that are included in a collection in order to reduce run-time (if someone really only wants to use this functionality to apply the estimate metabolism function on a group of MAGs).

**Comment by ivagljiva** [comment]
@jzrapp This is an interesting error that I have not seen before. 

>So now, I assume that my output result is incomplete, but the job still finished.

I think you are right. The job finished successfully because some of the threads finished, but 4 of the threads were killed for some reason. That reason is unclear - the only thing I can tell you from those Config Errors is that the thread command returned with a negative status code (a termination signal). I suspect that this happened because the job was very large and using too many resources (maybe too much memory). 

> Do you have an idea of how to avoid this?
If you have access to a computer cluster, you could run this larger job on it and allocate more resources to it. If not, it may be more tricky to get the job to finish. You could try using fewer threads - it will take longer but then each thread will have access to more memory. But that is not guaranteed to work; you still may run out of resources.

> Also, it would be great if there was a way to specify to run anvi-run-kegg-kofams only on a subset of contigs

This is a great idea! I will look into this. Perhaps then we can solve your problem this way.

**Comment by meren** [comment]
Yeah, this is kind of an interesting error. I think we should keep an eye on exceptions thrown in threads and kill the entire parent process by terminating all threads when we see one, @ivagljiva (please LMK if you need more input for this).

It will be difficult to test it, but perhaps you can have a random number generator that causes an error in threads that generates even numbers or something :)

**Comment by meren** [comment]
thank you for reporting this, @jzrapp! I agree with @ivagljiva that this looks like doing of the operating system :)

**Comment by jzrapp** [comment]
Thank you both! Yes, I think it would be better if the whole job was killed when individual threads are terminated. So sad when you think it finished and then realize that something's wrong :( 
I'm rerunning it with more allocated resources and fewer threads! The other dataset finished without error and I'm excited to play with the output! If I have more ideas or comments on the usability of estimate-metabolism is there a dedicated forum where I should add these thoughts, @ivagljiva ?

**Comment by ivagljiva** [comment]
> is there a dedicated forum

Not yet, but I would be thrilled if you were to open new Feature Request issue(s) with any ideas or comments you have for improving this section of the code base. Thank you very much @jzrapp :)

**Comment by ekiefl** [comment]
To anyone who wants to address this, I recently implemented something similar in `anvi-profile` multithreading: if one of the threads gives an error, it sends back an error which the main thread catches and relays.

**Comment by ivagljiva** [comment]
Dear @jzrapp, 

> Also, it would be great if there was a way to specify to run anvi-run-kegg-kofams only on a subset of contigs

I have just implemented this, so in the future, if you want to annotate KOs in only certain bins, you can save those bins in a collection and run
```
anvi-run-kegg-kofams -c CONTIGS.db -p PROFILE.db -C COLLECTION_NAME
```

**Comment by meren** [comment]
Hey @ivagljiva, I am impressed that the module is flexible enough to be able to run KOfams on a single bin, but I think it is a step towards a dangerous direction.

When you allow users to annotate only some contigs in their contigs databases with functions, and then set the `self` table that those functions were run, the fact that they were only run on a subset of contigs will not be obvious anywhere. This can create a lot of misunderstandings in the long run.

But anvi'o allows users to 'split' a bin from a collection into its own standalone database files. A better practice to work with a single bin with `anvi-run-kegg-kofams` would be to first run `anvi-split` on a collection to get a bin and its data out, and run `anvi-run-kegg-kofams` on that contigs db.

In all circumstances tools like `anvi-run-ncbi-cogs`, `anvi-run-kegg-kofams`, or `anvi-run-scg-taxonomy` that modify the `self` table to leave behind a piece of information regarding the fact that they _were_ run should run on all contigs for consistency.

**Comment by ivagljiva** [comment]
@meren That makes sense. I will revert all related commits.

@jzrapp Please use the strategy that Meren suggested with `anvi-split` if you want to annotate only a few bins.
