### ISSUE TITLE
Issue with anvi-profile

### ISSUE THREAD

**Issue by chandnisidhu** [merenlab/anvio#1555]
Hi,

I am getting this error while using anvi-profile:

Traceback (most recent call last):
  File "/home/csidhu/miniconda3/envs/anvio-6.2/bin/anvi-profile", line 5, in <module>
    import anvio.profiler as profiler
  File "/home/csidhu/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 24, in <module>
    from anvio.tables.indels import TableForIndels
ModuleNotFoundError: No module named 'anvio.tables.indels'

Kindly look into this,

Thank you in advance.

**Comment by meren** [comment]
Something must have gone wrong with your profile database. Please remove it and re-run anvi-profile. If you get the same error, please let us know.

**Comment by chandnisidhu** [comment]
Hi,

It is giving the following error now:

Traceback (most recent call last):
  File "/home/csidhu/miniconda3/envs/anvio-6.2/bin/anvi-profile", line 5, in <module>
    import anvio.profiler as profiler
  File "/home/csidhu/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 19, in <module>
    import anvio.clustering as clustering
  File "/home/csidhu/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/clustering.py", line 8, in <module>
    from sklearn import manifold
  File "/home/csidhu/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/sklearn/__init__.py", line 81, in <module>
    from .utils._show_versions import show_versions
  File "/home/csidhu/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS

**Comment by meren** [comment]
Sorry, this is a problem related to your system and outside the scope of anvi'o related problems. Google may be more effective helping you solve this one :)

Please make sure `anvi-self-test --suite mini` runs properly on your computer first before trying to profile things.

Best,
