### ISSUE TITLE
[BUG] anvi-script-get-primer-matches summary bug

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1606]
## Short description of the problem

`anvi-script-get-primer-matches` failed to summarized the output.

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 20
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
tRNA-seq DB version ..........................: 1
```

## Detailed description of the issue

Here was the output of my command:
```
HITS PER SAMPLE
===============================================
Summary ......................................:

* After processing 4,036,679,064 reads in 51 samples, anvi'o found 307213 hits for
your 200 sequences in the primer sequences file. What is shown below breaks
these numbers down per sample because that's how anvi'o rolls (SAM: Shortest
sequence after match; LAM: Longest sequence after match; ALAM: Average length
after match).


KC_D_01 ......................................: 70,730,044 total reads
    TTTTATCCAATTACGGCTCTGTTATAG ..............: 55 hits / SAM: 7 / LAM: 123 /
                                                ALAM: 67.59
    AGCCGCCGTTGCCGCTTTGGC ....................: 336 hits / SAM: 6 / LAM: 128 /
                                                ALAM: 476.82
    AAAACAGGGAGATTTACGATTAGACAATTTACGATT .....: 28 hits / SAM: 9 / LAM: 112 /
                                                ALAM: 29.57
    AATATAAGTATTCCGGTAA ......................: 36 hits / SAM: 17 / LAM: 132 /
                                                ALAM: 58.29
    TGACTTGGAAGTGTTTTTTAAACGTTCGTTTAATGGAC ...: 34 hits / SAM: 20 / LAM: 110 /
                                                ALAM: 41.45
    ATATATTTATTCGCCGGAGGTCCGCTTGCCATGCGCTGCACACCGGTGGTATATGCTC : 64 hits / SAM: 10 / LAM: 91 /
                                                ALAM: 66.29
[...]
    AACAAACTATAGTTCTTGAGGAACTATGGAA ..........: 8 hits / SAM: 12 / LAM: 109 /
                                                ALAM: 7.86
Traceback (most recent call last):
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/sandbox/anvi-script-get-primer-matches", line 240, in <module>
    main(args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/sandbox/anvi-script-get-primer-matches", line 159, in main
    run.info(f"    {primer_sequence}", f"{pp(samples_dict[sample_name]['hits'][primer_sequence])} hits / SAM: {min(seq_lengths_after_match)} / LAM: {max(seq_lengths_after_match)} / ALAM: {sum(seq_lengths_after_match) / len(primers_dict[primer_sequence]['matching_sequences']):.2f}")
ValueError: min() arg is an empty sequence
```

**Comment by meren** [comment]
Apologies for the bug. It is now good to go :)
