### ISSUE TITLE
Interactive interface not working

### ISSUE THREAD

**Issue by SofiMarcos** [merenlab/anvio#1610]
## Interactive interface not working

Hi Anvi'o team! When running anvi-self-test --suite mini in a virtual machine (Ubuntu 18.04), previous steps go well but in the interactive part something goes wrong. 

## code error:
Traceback (most recent call last):                                                                                                                                                                          
  File "/home/lan/miniconda3/envs/anvio-6.2/bin/anvi-interactive", line 120, in <module>
    d = interactive.Interactive(args)
  File "/home/lan/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/interactive.py", line 187, in __init__
    self.completeness = Completeness(self.contigs_db_path)
  File "/home/lan/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/completeness.py", line 45, in __init__
    self.SCG_domain_predictor = scgdomainclassifier.Predict(argparse.Namespace(), run=terminal.Run(verbose=False), progress=self.progress)
  File "/home/lan/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/scgdomainclassifier.py", line 234, in __init__
    SCGDomainClassifier.__init__(self, args, run, progress)
  File "/home/lan/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/scgdomainclassifier.py", line 73, in __init__
    self.rf.initialize_classifier()
  File "/home/lan/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/learning.py", line 103, in initialize_classifier
    classifier_obj = pickle.load(open(self.classifier_object_path, 'rb'))
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

Config Error: According to the exit code ('1'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the 
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry 
              just a bit less.                                    
```
anvi-self-test --suite mini
```

## System info

I installed Anvio using Mamba because with conda the solving environment step was killed:
conda create -y --name anvio-6.2 python=3.6    
conda activate anvio-6.2
conda install mamba -c conda-forge
mamba install anvio==6.2 -c conda-forge -c bioconda
mamba install anvio-minimal==6.2=py_1 -c conda-forge -c bioconda

Thank you for your time, 
SofiM

**Comment by meren** [comment]
Hi @SofiMarcos,

I became aware of this issue yesterday while preparing for `v7`. This is due to a change in newer versions of scikit-learn. Perhaps `mamba` is faster because it doesn't necessarily resolve exact dependencies and takes the liberty of installing newer versions of libraries. I am not sure.

But nevertheless, If you run the following command, this is the output you want to see for things to work with `v6.2`:

```bash
python -c "import sklearn; print(sklearn.__version__)"
0.23.1
```

You can try to run the following in your anvi'o environment to ensure that:

```
cona install -c bioconda scikit-learn==0.23.1
```

If this doesn't work, perhaps this would solve it:

```
pip install scikit-learn==0.23.1
```

Sorry for all the trouble! We will release `v7` within a few weeks and hopefully things will be much more smooth then.


Best wishes,
