### ISSUE TITLE
[BUG] anvi-display-functions only returns key error

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#1651]
## Short description of the problem

No matter what inputs I give to `anvi-display-functions` it returns a key error. 

## anvi'o version

anvio dev (on midway).

## Detailed description of the issue

I tried to run `anvi-display-functions`, but no matter what version of the command I ran I got the same key error.

Here are all the commands that I tried out:
```bash
anvi-display-functions -g GENOMES.db --list-annotation-source
anvi-display-functions -g GENOMES.db --annotation-source KOfam
anvi-display-functions -g GENOMES.db --annotation-source KOfam --aggregate-based-on-accession
anvi-display-functions -g GENOMES.db --annotation-source COG20_CATEGORY
```

They all give this error:
```
Traceback (most recent call last):
  File "/project2/meren/PEOPLE/efogarty/github/anvio-emily/bin/anvi-display-functions", line 43, in <module>
    groupB.add_argument(*anvio.A('aggregate-based-on-accession'), **anvio.K('aggregate-based-on-accession'))
  File "/project2/meren/GITHUB/anvio/anvio/__init__.py", line 3065, in A
    return D[param_id][0]
KeyError: 'aggregate-based-on-accession'
```

I can't get past this error to display functions in the interactive interface.

## Files to reproduce

The path to the genomes storage is on slack on this issue notification. Thanks! :)

**Comment by efogarty11** [comment]
Note: This turned out to be a problem with my env so I'm closing this.
