### ISSUE TITLE
[BUG] anvi-estimate-functional-enrichment does not work with metagenome mode modules output

### ISSUE THREAD

**Issue by ivagljiva** [merenlab/anvio#1654]
## Short description of the problem

If you run `anvi-estimate-metabolism --metagenome-mode` and then use the modules mode output for `anvi-estimate-functional-enrichment`, the enrichment script is sad and dies. This is due to a non-unique index.

## anvi'o version

Replace this text with the output of this command:

```
Anvi'o .......................................: hope (v7-dev)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```
(but also applies to `v7`)

## Detailed description of the issue

Here is the bug we get:
```
[27 Jan 21 17:31:49 Enrichment analysis] Converting modules mode output into input for enrichment script                                                                                                                                   Traceback (most recent call last):
  File "/Users/iva/opt/miniconda3/envs/anvio-dev/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4730, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 126, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 141, in pandas._libs.index.IndexEngine._get_loc_duplicates
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/iva/software/anvio/bin/anvi-compute-functional-enrichment", line 128, in <module>
    main(args)
  File "/Users/iva/software/anvio/bin/anvi-compute-functional-enrichment", line 58, in main
    e.run_enrichment_stats()
  File "/Users/iva/software/anvio/anvio/kegg.py", line 4608, in run_enrichment_stats
    self.get_enrichment_input(enrichment_input_path)
  File "/Users/iva/software/anvio/anvio/kegg.py", line 4567, in get_enrichment_input
    mod_name = samples_with_mod_df['module_name'][0]
  File "/Users/iva/opt/miniconda3/envs/anvio-dev/lib/python3.6/site-packages/pandas/core/series.py", line 1068, in __getitem__
    result = self.index.get_value(self, key)
  File "/Users/iva/opt/miniconda3/envs/anvio-dev/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4750, in get_value
    raise IndexError(key)
IndexError: 0
```

This is happening when the modules mode input is being converted into a nice format for the enrichment script. The problem (I think) is that the `db_name` column which is used for the dataframe index has duplicate values (since multiple contigs in the metagenome can have modules which have completeness score over the threshold).

## Files to Reproduce

These exist. I have them.

**Comment by ivagljiva** [comment]
[Done](https://github.com/merenlab/anvio/pull/1655). BOOM 💥

**Comment by meren** [comment]
🎊
