### ISSUE TITLE
[BUG] --help can't encode ascii chars

### ISSUE THREAD

**Issue by GodloveD** [merenlab/anvio#1667]
## Short description of the problem

Many, most, or all commands will not display --help and fail with errors like the following:
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3684-3763: ordinal not in range(128)
```

## anvi'o version

```
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info

Problem within Ubuntu 18 container, CentOS 7 container, and CentOS 7 bare metal all installed within conda environments. 

## Detailed description of the issue

Here are a few examples: 
```
$ anvi-export-locus --help
Traceback (most recent call last):
  File "/opt/conda/envs/anvio/bin/anvi-export-locus", line 99, in <module>
    args = parser.get_args(parser)
  File "/opt/conda/envs/anvio/lib/python3.6/site-packages/anvio/argparse.py", line 189, in get_args
    args, unknown = parser.parse_known_args()
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1024, in __call__
    parser.print_help()
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 2372, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7108-7187: ordinal not in range(128)

$ anvi-gen-contigs-database --help
Traceback (most recent call last):
  File "/opt/conda/envs/anvio/bin/anvi-gen-contigs-database", line 60, in <module>
    args = parser.get_args(parser)
  File "/opt/conda/envs/anvio/lib/python3.6/site-packages/anvio/argparse.py", line 189, in get_args
    args, unknown = parser.parse_known_args()
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 1024, in __call__
    parser.print_help()
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/conda/envs/anvio/lib/python3.6/argparse.py", line 2372, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11495-11574: ordinal not in range(128)

```

**Comment by meren** [comment]
Hi @GodloveD, 

This is due to the fact that your terminal settings / locale does not support UTF8. Here is an example:

```
export LANG="en_US" && export LC_ALL="C" && anvi-interactive -h
```

```
Traceback (most recent call last):
  File "/Users/meren/github/anvio/bin/anvi-interactive", line 119, in <module>
    args = parser.get_args(parser)
  File "/Users/meren/github/anvio/anvio/argparse.py", line 189, in get_args
    args, unknown = parser.parse_known_args()
  File "/Users/meren/miniconda3/envs/anvio-master/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/meren/miniconda3/envs/anvio-master/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/meren/miniconda3/envs/anvio-master/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/Users/meren/miniconda3/envs/anvio-master/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/meren/miniconda3/envs/anvio-master/lib/python3.6/argparse.py", line 1024, in __call__
    parser.print_help()
  File "/Users/meren/miniconda3/envs/anvio-master/lib/python3.6/argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "/Users/meren/miniconda3/envs/anvio-master/lib/python3.6/argparse.py", line 2372, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18366-18445: ordinal not in range(128)
```

In contrast,

```
export LANG="en_US.UTF-8" && export LC_ALL="en_US.UTF-8" && anvi-interactive -h
```

```
(...)
  --password-protected  If this flag is set, command line tool will ask you to
                        enter a password and interactive interface will be
                        only accessible after entering same password. This
                        option is recommended for shared machines like
                        clusters or shared networks where computers are not
                        isolated. (default: False)
  --user-server-shutdown
                        Allow users to shutdown an anvi'server via web
                        interface. (default: False)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 Program description:

   Start an anvi'o server for the interactive interface

🧀 Can consume:

   profile-db / single-profile-db / contigs-db / genes-db / bin / view-data /
   dendrogram / phylogeny

🍕 Can provide:

   collection / bin / interactive / svg

🍺 More on `anvi-interactive`:

   https://merenlab.org/software/anvio/help/main/programs/anvi-interactive

🍻 All anvi'o programs and artifacts:

   https://merenlab.org/software/anvio/help/main

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

I hope this is something you can solve by setting your locale to support UTF-8.

Best,

**Comment by GodloveD** [comment]
Very helpful.  Thank you.
