### ISSUE TITLE
anvi-setup-ncbi-cogs issue

### ISSUE THREAD

**Issue by juliette-thieb** [merenlab/anvio#1671]
Hello everyone,

I am trying to annotate genes on a hundred genome/contigs databases files by running cogs but I have a UnicodeDecodeError problem with the anvi-setup-ncbi-cogs command, I first got this message:

```Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.cog.csv
Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.def.tab
Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/fun-20.tab
Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.fa.gz
Traceback (most recent call last):
  File "/home/ju/miniconda3/envs/anvio-7/bin/anvi-setup-ncbi-cogs", line 47, in <module>
    setup.create()
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 617, in create
    self.setup_raw_data()
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 831, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 637, in format_p_id_to_cog_id_cPickle
    num_lines_in_file = filesnpaths.get_num_lines_in_file(input_file_path)
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/filesnpaths.py", line 327, in get_num_lines_in_file
    return sum(bl.count("\n") for bl in blocks(f))
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/filesnpaths.py", line 327, in <genexpr>
    return sum(bl.count("\n") for bl in blocks(f))
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/filesnpaths.py", line 322, in blocks
    b = files.read(size)
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 27932: invalid start byte
```

Then, I tried anvi-setup-ncbi-cogs --reset and still got the same issue with this message:

```Traceback (most recent call last):
  File "/home/ju/miniconda3/envs/anvio-7/bin/anvi-setup-ncbi-cogs", line 47, in <module>
    setup.create()
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 617, in create
    self.setup_raw_data()
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 831, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 637, in format_p_id_to_cog_id_cPickle
    num_lines_in_file = filesnpaths.get_num_lines_in_file(input_file_path)
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/filesnpaths.py", line 327, in get_num_lines_in_file
    return sum(bl.count("\n") for bl in blocks(f))
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/filesnpaths.py", line 327, in <genexpr>
    return sum(bl.count("\n") for bl in blocks(f))
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/filesnpaths.py", line 322, in blocks
    b = files.read(size)
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 45223: invalid continuation byte
```

I don't know how to solve this, does anyone had this issue ? Thank you.

## System and anvi'o version
I am using Python 3.8.5 version (base), anvio-7 version and Python 3.6.12 while anvi'o activated.
I installed and use anvi'o on a virtual machine from VirtualBox and my operating system is Ubuntu (Ubuntu 18.04.5 LTS) on this VM.

**Comment by meren** [comment]
Hi @juliette-thieb,

How did you install anvi'o?

**Comment by juliette-thieb** [comment]
Hi @meren,
I installed it with conda (version conda 4.9.2) and followed the "slower and more reliable option" of the installation page

**Comment by meren** [comment]
Hi @juliette-thieb, if you try to re-run the same command with `--reset` flag, do you get the same error?

**Comment by juliette-thieb** [comment]
Yes I did and still got the same error, I also tried with the just-do-it flag

**Comment by juliette-thieb** [comment]
I retried this morning at the lab with the command anvi-setup-ncbi-cogs --reset and got a new error message (I was at home with poor internet connection the previous times, I'm not sure it had an impact though):

```Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.cog.csv
Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.def.tab
Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/fun-20.tab
Downloaded successfully ......................: /home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.fa.gz
[15 Feb 21 09:47:13 Formatting protein ids to COG ids file] 79.41%      ETA: 2sTraceback (most recent call last):
  File "/home/ju/miniconda3/envs/anvio-7/bin/anvi-setup-ncbi-cogs", line 47, in <module>
    setup.create()
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 617, in create
    self.setup_raw_data()
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 831, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/ju/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 659, in format_p_id_to_cog_id_cPickle
    p_id = fields[2].replace('.', '_')
IndexError: list index out of range
```

**Comment by meren** [comment]
Anyone who is willing to help with this error can switch to the active branch (explained [here](https://merenlab.org/2016/06/26/installation-v2/#5-follow-the-active-development-youre-a-wizard-arry)), run the following command,

```
anvi-setup-ncbi-cogs --reset
```

And follow the instructions in the error message to send necessary files to us.
