### ISSUE TITLE
last mistune python module breaks anvi'o V7

### ISSUE THREAD

**Issue by EricDeveaud** [merenlab/anvio#1692]
hello 

while testing a fresh install of anvi'o from https://github.com/merenlab/anvio/archive/v7.tar.gz

FYI while running anvio-self-test I had the folownig error:

```
THE MORE YOU KNOW 🌈
===============================================
Someone asked the Contigs Superclass to initialize only a subset of contig
sequences. Usually this is a good thing and means that some good code somewhere
is looking after you. Just FYI, this class will only know about 3 contig
sequences instead of all the things in the database.

                                                                                         
* FYI: A subset of split sequences are being initialized (35 of 38 the contigs
database knows about, to be precise). Nothing to worry about. Probably.

Traceback (most recent call last):                                                       
  File "/opt/gensoft/exe/anvio/7/bin/anvi-summarize", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==7', 'anvi-summarize')
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio-7-py3.8.egg/EGG-INFO/scripts/anvi-summarize", line 123, in <module>
    main(args)
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio-7-py3.8.egg/EGG-INFO/scripts/anvi-summarize", line 69, in main
    summary.process()
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio-7-py3.8.egg/anvio/summarizer.py", line 865, in process
    self.init()
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio-7-py3.8.egg/anvio/summarizer.py", line 807, in init
    renderer = mistune.Renderer(escape=False)
AttributeError: module 'mistune' has no attribute 'Renderer'


Config Error: According to the exit code ('1'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the 
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry 
              just a bit less.                                                              
```
while running anvi'o v7 with mistune-2.0.0rc1

reverting to mistune-0.8.4 fixed the problem.

regards

Eric

**Comment by meren** [comment]
Thanks a lot for the heads-up, @EricDeveaud.

**Comment by meren** [comment]
Now this is actually solved in the main repository, but I will also update the documentation to make sure people downgrade their mistune.


Thanks again,
