### ISSUE TITLE
anvi-self-test --suite metagenomics-full :: failure on error

### ISSUE THREAD

**Issue by EricDeveaud** [merenlab/anvio#1699]
Hello

anvio-v7
`anvi-self-test --suite metagenomics-full`  fails on error/

```
anvi-self-test --suite metagenomics-full --no-interactive
... SNIP ...
GENE LEVEL COVERAGE STATS STORED
===============================================
Mode .........................................: STANDARD
Num genes ....................................: 23
Num entries ..................................: 69
Genes database ...............................: /tmp/tmpbypbc95x/SAMPLES-MERGED/GENES/CONCOCT-Bin_1.db
Collection name ..............................: CONCOCT
Bin name .....................................: Bin_1
Auxiliary Data ...............................: Found:
                                                /tmp/tmpbypbc95x/SAMPLES-MERGED/AUXILIARY-DATA.db
                                                (v. 2)
Profile Super ................................: Initialized with 18 of 35 splits:
                                                /tmp/tmpbypbc95x/SAMPLES-MERGED/PROFILE.db
                                                (v. 35)
                                                                                         
THE MORE YOU KNOW 🌈
===============================================
Someone asked the Contigs Superclass to initialize only a subset of contig
sequences. Usually this is a good thing and means that some good code somewhere
is looking after you. Just FYI, this class will only know about a single contig
sequence instead of all the things in the database.

                                                                                         
* FYI: A subset of split sequences are being initialized (18 of 38 the contigs
database knows about, to be precise). Nothing to worry about. Probably.

Traceback (most recent call last):                                                       
  File "/opt/gensoft/exe/anvio/7/venv/bin/anvi-mcg-classifier", line 104, in <module>
    main(args)
  File "/opt/gensoft/exe/anvio/7/venv/bin/anvi-mcg-classifier", line 64, in main
    mcg.classify()
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio/mcgclassifier.py", line 547, in classify
    self.init_gene_class_df()
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio/mcgclassifier.py", line 481, in init_gene_class_df
    self.init_gene_coverage_consistency_information()
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio/mcgclassifier.py", line 363, in init_gene_coverage_consistency_information
    self.init_samples_coverage_stats_dict()
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/anvio/mcgclassifier.py", line 218, in init_samples_coverage_stats_dict
    samples_information = pd.DataFrame(index=self.samples, columns=MCG_samples_information_table_structure[1:])
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 242, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/opt/gensoft/exe/anvio/7/venv/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1221, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'


Config Error: According to the exit code ('1'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the 
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry 
              just a bit less.                                                              
```

regards

Eric

**Comment by meren** [comment]
Interesting. It works for me :/ What is your pandas version?

```
python -c "import pandas; print(pandas.__version__)"
0.25.1
```

**Comment by EricDeveaud** [comment]
ouch !!!
0.25.2 as I was not abble to install pandas 0.25.1 ;-(

**Comment by EricDeveaud** [comment]
with pandas 0.25.1 it runs fine 

FYI due to https://github.com/pandas-dev/pandas/issues/34969 I had to force `numpy==1.18.5` in order to be abble to install pandas 0.25.1 

regards

Eric
