### ISSUE TITLE
[BUG] anvi-run-hmm failed with Archaea_76

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1718]
## Short description of the problem

anvi-run-hmm failed with Archaea_76.

## anvi'o version

Using github main version. 

## System info

MacOS and Linux

## Detailed description of the issue

anvi-run-hmm failed with this error:
```
>>> anvi-run-hmms -c 03_CONTIGS/Akkermansia_W48-contigs.db -I Archaea_76 --hmmer-out test
Contigs DB ...................................: 03_CONTIGS/Akkermansia_W48-contigs.db
HMM sources ..................................: Archaea_76
Alphabet/context target found ................: AA:GENE

HMM Profiling for Archaea_76
===============================================
Reference ....................................: Lee, https://doi.org/10.1093/bioinformatics/btz188
Kind .........................................: singlecopy
Alphabet .....................................: AA
Context ......................................: GENE
Domain .......................................: archaea
HMM model path ...............................: /var/folders/5s/pwnhr97n22l9p2sr7kcmh6lr0000gq/T/tmprh54fqdn/Archaea_76.hmm
Number of genes in HMM model .................: 76
Noise cutoff term(s) .........................: --cut_ga
Number of CPUs will be used for search .......: 1
HMMer program used for search ................: hmmscan
Temporary work dir ...........................: /var/folders/5s/pwnhr97n22l9p2sr7kcmh6lr0000gq/T/tmp0i68q2i8
Log file for thread 0 ........................: /var/folders/5s/pwnhr97n22l9p2sr7kcmh6lr0000gq/T/tmp0i68q2i8/AA_gene_sequences.fa.0_log
Number of raw hits in table file .............: 37
HMMER output directory .......................: test

✖ anvi-run-hmms encountered an error after 0:00:08.634666
Traceback (most recent call last):
  File "/Users/frigodet/github/anvio/bin/anvi-run-hmms", line 147, in <module>
    main(args)
  File "/Users/frigodet/github/anvio/anvio/terminal.py", line 866, in wrapper
    program_method(*args, **kwargs)
  File "/Users/frigodet/github/anvio/bin/anvi-run-hmms", line 102, in main
    search_tables.populate_search_tables(sources)
  File "/Users/frigodet/github/anvio/anvio/tables/hmmhits.py", line 250, in populate_search_tables
    parser = parser_modules['search']['hmmer_table_output'](hmm_scan_hits_txt, alphabet=alphabet, context=context, program=self.hmm_program)
  File "/Users/frigodet/github/anvio/anvio/parsers/hmmer.py", line 582, in __init__
    fixed_hmmer_table_txt =  self.fix_sad_hmmer_table_output(hmmer_table_txt, col_names)
  File "/Users/frigodet/github/anvio/anvio/parsers/hmmer.py", line 750, in fix_sad_hmmer_table_output
    hmmer_df = pd.read_csv(hmmer_table_txt, sep="\s+", names=col_names_plus_description_cols, index_col=False)
  File "/Users/frigodet/virtual-envs/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/frigodet/virtual-envs/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/Users/frigodet/virtual-envs/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/Users/frigodet/virtual-envs/anvio-master/lib/python3.6/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 973, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1049, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1366, in pandas._libs.parsers.TextReader._get_column_name
IndexError: list index out of range
```

Here is the faulty `hmm.table`: [hmm_table.txt](https://github.com/merenlab/anvio/files/6326163/hmm_table.txt)

**Comment by meren** [comment]
DEAR DR. FLORIAN TRIGODET, THANK YOU VERY MUCH FOR REPORTING THIS IMPORTANT BUG FOR "Replace this text with a short but descriptive title". WE WILL PROMPTLY LOOK INTO THIS.

**Comment by ivagljiva** [comment]
dis was my fault. but i fixed it 😇
