### ISSUE TITLE
[BUG] anvi-split 'ProfileSummarizer' object has no attribute 'collection_name'

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1725]
## Short description of the problem

When running anvi-split, I get the following error:
```
AttributeError: 'ProfileSummarizer' object has no attribute 'collection_name'
```

## anvi'o version

```bash
Anvi'o .......................................: hope (v7-dev)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

The Meren lab's Midway partition.

## Detailed description of the issue

My command:
```bash
anvi-split -p PROFILE.db -c CONTIGS.db -C default -b DB_MAG_00001 -o SPLIT_PROFILES
```

I expected it to make a split profile of the MAG DB_MAG_00001 in the SPLIT_PROFILES directory. Instead, I get the following error output:
```bash
Contigs DB ...................................: Initialized: CONTIGS.db (v. 20)
Traceback (most recent call last):
  File "/project2/meren/GITHUB/anvio/bin/anvi-split", line 70, in <module>
    splitter.DBSplitter(args).get()(args).process()
  File "/project2/meren/GITHUB/anvio/anvio/splitter.py", line 187, in process
    self.sanity_check()
  File "/project2/meren/GITHUB/anvio/anvio/splitter.py", line 174, in sanity_check
    self.summary = summarizer.ProfileSummarizer(self.args, r=self.run, p=self.progress)
  File "/project2/meren/GITHUB/anvio/anvio/summarizer.py", line 706, in __init__
    DatabasesMetaclass.__init__(self, self.args, self.run, self.progress)
  File "/project2/meren/GITHUB/anvio/anvio/dbops.py", line 3544, in __init__
    ProfileSuperclass.__init__(self, self.args, self.run, self.progress)
  File "/project2/meren/GITHUB/anvio/anvio/dbops.py", line 2698, in __init__
    elif self.collection_name:
AttributeError: 'ProfileSummarizer' object has no attribute 'collection_name'
```

I have confirmed that this collection exists using `anvi-export-collections` with the `--list-collections` flag.

## Files to reproduce

To reproduce on the Meren lab Midway partition:
```bash
cd /project2/meren/PROJECTS/FMT/2017-Louie-Samples/MAPPING_BINNING_donor/000_Watson_et_al_2021_data_pack/FMT_DONOR_B_AND_RECIPIENTS

anvi-split -p PROFILE.db -c CONTIGS.db -C default -b DB_MAG_00001 -o SPLIT_PROFILES
```

**Comment by mschecht** [comment]
I can reproduce this error on the `main` branch with the Infant Gut dataset

```
curl -L https://ndownloader.figshare.com/files/26218961 -o INFANT-GUT-TUTORIAL.tar.gz
tar -zxvf INFANT-GUT-TUTORIAL.tar.gz && cd INFANT-GUT-TUTORIAL

anvi-migrate --migrate-dbs-safely *.db


anvi-script-add-default-collection -p PROFILE.db \
                                   -c CONTIGS.db \
                                   -C EVERYTHING


anvi-summarize -c CONTIGS.db \
               -p PROFILE.db \
               -C EVERYTHING
```
![image](https://user-images.githubusercontent.com/8404575/116156149-b9683000-a6b0-11eb-8724-7fceafdc406d.png)

**Comment by meren** [comment]
My fault. Looking into this immediately.

**Comment by meren** [comment]
@watsonar, @mschecht, this is now resolved.

**Comment by watsonar** [comment]
Thank you, @meren 😃
