### ISSUE TITLE
anvi-cluster-contigs (anvi-dev) fails after commit 0d4a507

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#1754]
## Short description of the problem

The function `anvi-cluster-contigs` fails after commit 0d4a507.

## anvi'o version

```
anvi-self-test --version
Anvi'o .......................................: hope (v7-dev)

Profile database .............................: 36
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core)
Release:	7.6.1810
Codename:	Core
```

## Detailed description of the issue

After updating my dev build, I get the following error when running `anvi-cluster-contigs`:

```
WARNING
===============================================
You are running an experimental workflow not every part of which may be fully
and thoroughly tested :) Please scrutinize your output carefully after analysis,
and keep us posted if you see things that surprise you.

Contigs DB ...................................: 03_CONTIGS/WA-contigs.db
Profile DB ...................................: 06_MERGED/WA/PROFILE.db
Binning module ...............................: CONCOCT
Cluster type .................................: contig
Working directory ............................: /pool/genomics/stri_istmobiome/dbs/tmp_data_TRANS/tmps4c38_x_
Traceback (most recent call last):
  File "/home/scottjj/github/anvio/bin/anvi-cluster-contigs", line 278, in <module>
    main(args, unknown)
  File "/home/scottjj/github/anvio/bin/anvi-cluster-contigs", line 195, in main
    input_files = prepare_input_files(working_dir, merged_profile_db, contigs_db)
  File "/home/scottjj/github/anvio/bin/anvi-cluster-contigs", line 104, in prepare_input_files
    contig_names = set([x['__parent__'] for x in split_coverages.values()])
  File "/home/scottjj/github/anvio/bin/anvi-cluster-contigs", line 104, in <listcomp>
    contig_names = set([x['__parent__'] for x in split_coverages.values()])
KeyError: '__parent__'
```

`anvi-cluster-contigs` worked last night so I assume it has something to do with the latest commit? I tried re-merging individual PROFILE.dbs and running `anvi-cluster-contigs` again but got the same error (first I had to run `anvi-migrate`). I have tried on three different datasets, same result :/

Here are the commands I ran:

```
for sample in `cat list.txt`
do 
	anvi-migrate 05_ANVIO_PROFILE/WA/$sample/PROFILE.db --migrate-dbs-safely
done
anvi-merge 05_ANVIO_PROFILE/WA/*/PROFILE.db -c 03_CONTIGS/WA-contigs.db -o 06_MERGED/WA
anvi-cluster-contigs -p 06_MERGED/WA/PROFILE.db -c 03_CONTIGS/WA-contigs.db -C CONCOCT_75 --driver concoct -T 2 --clusters 75 --just-do-it
```

FYI, here is the output of `anvi-cluster-contigs -h`

```
usage: anvi-cluster-contigs [-h] -p PROFILE_DB -c CONTIGS_DB -C
                            COLLECTION_NAME --driver DRIVER [-T NUM_THREADS]
                            [--log-file FILE_PATH] [--just-do-it]

A program to cluster items in a merged anvi'o profile using automatic binning
algorithms

optional arguments:
  -h, --help            show this help message and exit
  -p PROFILE_DB, --profile-db PROFILE_DB
                        Anvi'o profile database
  -c CONTIGS_DB, --contigs-db CONTIGS_DB
                        Anvi'o contigs database generated by 'anvi-gen-
                        contigs-database'
  -C COLLECTION_NAME, --collection-name COLLECTION_NAME
                        Collection name.
  --driver DRIVER       Automatic binning drivers. Available options 'concoct,
                        metabat2, maxbin2, dastool, binsanity'.
  -T NUM_THREADS, --num-threads NUM_THREADS
                        Maximum number of threads to use for multithreading
                        whenever possible. Very conservatively, the default is
                        1. It is a good idea to not exceed the number of CPUs
                        / cores on your system. Plus, please be careful with
                        this option if you are running your commands on a SGE
                        --if you are clusterizing your runs, and asking for
                        multiple threads to use, you may deplete your
                        resources very fast.
  --log-file FILE_PATH  File path to store debug/output messages.
  --just-do-it          Don't bother me with questions or warnings, just do
                        it.
 
CONCOCT
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  --clusters INT        specify maximal number of clusters for VGMM, default
                        400
  --kmer-length INT     pecify kmer length, default 4
  --length-threshold INT
                        specify the sequence length threshold, contigs shorter
                        than this value will not be included. Defaults to 1000
  --read-length INT     specify read length for coverage, default 100
  --no-cov-normalization
                        By default the coverage is normalized with regards to
                        samples, then normalized with regards of contigs and
                        finally log transformed. By setting this flag you skip
                        the normalization and only do log transorm of the
                        coverage.
  --total-percentage-pca INT
                        The percentage of variance explained by the principal
                        components for the combined data.
  --epsilon FLOAT       Specify the epsilon for VBGMM. Default value is 1.0e-6
  --iterations INT      Specify maximum number of iterations for the VBGMM.
                        Default value is 500
  --seed INT            Specify an integer to use as seed for clustering. 0
                        gives a random seed, 1 is the default seed and any
                        other positive integer can be used. Other values give
                        ArgumentTypeError.

METABAT2 [NOT FOUND]

MAXBIN2 [NOT FOUND]

DASTOOL [NOT FOUND]

BINSANITY [NOT FOUND]

**Comment by meren** [comment]
Brilliant. Thank you very much for the report, I am looking into this immediately.

**Comment by meren** [comment]
Hey @jarrodscott, can you please see if the latest changes fixes the issue for you? Apologies for the inconvenience and thank you for patience :)

**Comment by jarrodscott** [comment]
No problem @meren and no inconvenience!

Hit another snag. Here is the output...

```
WARNING
===============================================
You are running an experimental workflow not every part of which may be fully
and thoroughly tested :) Please scrutinize your output carefully after analysis,
and keep us posted if you see things that surprise you.

Contigs DB ...................................: 03_CONTIGS/WA-contigs.db
Profile DB ...................................: 06_MERGED/WA/PROFILE.db
Binning module ...............................: CONCOCT
Cluster type .................................: contig
Working directory ............................: /pool/genomics/stri_istmobiome/dbs/tmp_data_TRANS/tmprgakok3h
Traceback (most recent call last):
  File "/home/scottjj/github/anvio/bin/anvi-cluster-contigs", line 280, in <module>
    main(args, unknown)
  File "/home/scottjj/github/anvio/bin/anvi-cluster-contigs", line 197, in main
    input_files = prepare_input_files(working_dir, merged_profile_db, contigs_db)
  File "/home/scottjj/github/anvio/bin/anvi-cluster-contigs", line 106, in prepare_input_files
    contig_names = set([x['__parent__'] for x in split_coverages.values()])
AttributeError: 'tuple' object has no attribute 'values'
```

**Comment by meren** [comment]
I really feel 8f390272d339315cfb65c0501d5dea3b61d17707 will solve this :p

**Comment by jarrodscott** [comment]
Its running now :) Nice work! I will let you know if there are any other issues and I can close if there are not.

```
[48;5;6m[38;5;0m
[16 Jun 21 13:59:26 concoct] Running using 2 threads...                        [0m
```

**Comment by jarrodscott** [comment]
Clusters like a charm. Closing.

**Comment by meren** [comment]
Thank you! :)
