### ISSUE TITLE
anvi-script-process-genbank-metadata - potential BUG

### ISSUE THREAD

**Issue by srisvs33** [merenlab/anvio#1774]
Hi Anvio team, 

I am currently using ANVIO-master branch. 

 I am trying to download a bunch of genome assemblies from NCBI. I have downloaded Genbank taxa IDs using a ncbi-genome-download algorithm. Then I was trying to use anvi-script-process-genbank-metadata. When I ran the script, I have encountered with the following error. Can you pls take a look at the issue.  

## anvi'o version

ANVIO-Master

## System info

Linux Centos , HPC server

## Detailed description of the issue

```
Input metadata file ..........................: Planococcus-NCBI-METADATA.txt
Output directory .............................: /home/NCAOR/venkat/Femi_isolate_genome/NCBI_Genome_Download/01_Planococcus-NCBI-GENOMES
Num entries in metadata ......................: 42
[29 Jul 21 12:07:47 GenBank to anvi'o] Processing GCA_003664125.1 ...                                                           ETA: NoneTraceback (most recent call last):
  File "/home/NCAOR/venkat/github/anvio/sandbox/anvi-script-process-genbank-metadata", line 58, in <module>
    genbank_to_anvio.process()
  File "/home/NCAOR/venkat/github/anvio/anvio/contigops.py", line 636, in process
    output_fasta_dict[final_name] = g.process()
  File "/home/NCAOR/venkat/github/anvio/anvio/contigops.py", line 747, in process
    aa_sequences_present = True if 'translation' in genes[0].qualifiers else False
IndexError: list index out of range  ..
```

## For Reproducible workflow 

```
gimme_taxa.py 1372 \
              -o Planococcus_TAX-IDs-SIMPLE.txt \
			  --just-taxids
```

```
ncbi-genome-download -t Planococcus_TAX-IDs-SIMPLE.txt \
                     bacteria \
                     -o 00_Planococcus_Genbank \
                     --metadata Planococcus-NCBI-METADATA.txt \
                     -s genbank
```

```
anvi-script-process-genbank-metadata -m Planococcus-NCBI-METADATA.txt \
                                     -o 01_Planococcus-NCBI-GENOMES \
                                     --output-fasta-txt Planococcus-fasta.txt \
                                     --exclude-gene-calls-from-fasta-txt
```

Many thanks in Advance.  

Venkat

**Comment by meren** [comment]
Hey @srisvs33, thanks a lot for the commands to reproduce this.

This was indeed due to a very recent change in the codebase. Please let me know if this addresses your issues or not.

Thank you!
