### ISSUE TITLE
[BUG] issue with plotext

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1838]
## Short description of the problem

When using `anvi-report-inversion` with the `--verbose` flag, I got an error due to plotext.

## anvi'o version

Anvi'o dev version.

## System info

Centos, with numpy 1.19.2

## Detailed description of the issue

Here is the error:
```
✖ anvi-report-inversions encountered an error after 0:00:05.938804
Traceback (most recent call last):
  File "/project2/meren/GITHUB/anvio/bin/anvi-report-inversions", line 101, in <module>
    main(args)
  File "/project2/meren/GITHUB/anvio/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/project2/meren/GITHUB/anvio/bin/anvi-report-inversions", line 26, in main
    I.process()
  File "/project2/meren/GITHUB/anvio/anvio/inversions.py", line 391, in process
    self.process_db(entry_name, profile_db_path, bam_file_path)
  File "/project2/meren/GITHUB/anvio/anvio/inversions.py", line 233, in process_db
    self.plot_coverage(f"{sequence_name}", stretch_sequence_coverage)
  File "/project2/meren/GITHUB/anvio/anvio/inversions.py", line 349, in plot_coverage
    plt.plot(coverage, fillx = True)
  File "/project2/meren/VIRTUAL-ENVS/anvio-dev/lib/python3.6/site-packages/plotext/_core.py", line 137, in plot
    label = label)
  File "/project2/meren/VIRTUAL-ENVS/anvio-dev/lib/python3.6/site-packages/plotext/_subplot.py", line 120, in draw
    self.add_data(*args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-dev/lib/python3.6/site-packages/plotext/_subplot.py", line 145, in add_data
    x, y = set_data(*args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-dev/lib/python3.6/site-packages/plotext/_utility/data.py", line 11, in set_data
    if x == None and y == None :
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

It does not work on the server with numpy 1.19.2 but works on my laptop with 1.17.0. Maybe the numpy version is the issue here?

**Comment by meren** [comment]
I solved it by adding a secondary check so things don't crash.
