### ISSUE TITLE
[BUG] anvi-setup-ncbi-cogs decompressing issue

### ISSUE THREAD

**Issue by clarelou0128** [merenlab/anvio#1889]
## Short description of the problem

I am trying to download COG2014 using anvio but have been running into the error about data decompressing.

## anvi'o version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

```
anvi-self-test --version
```

## System info

I installed anvio using conda (I followed your installation step: https://anvio.org/install/)

## Detailed description of the issue

Here is the detailed error:
```
Downloaded successfully ......................: /user/COG_2014/COG14/RAW_DATA_FROM_NCBI/cog2003-2014.csv
Downloaded successfully ......................: /user/COG_2014/COG14/RAW_DATA_FROM_NCBI/cognames2003-2014.tab
Downloaded successfully ......................: /user/COG_2014/COG14/RAW_DATA_FROM_NCBI/fun2003-2014.tab
Downloaded successfully ......................: /user/COG_2014/COG14/RAW_DATA_FROM_NCBI/prot2003-2014.fa.gz

Config Error: Something went wrong while decompressing the downloaded file :/ It is likely
              that the download failed and only part of the file was downloaded. If you would
              like to try again, please run the setup command with the flag `--reset`. Here is
              what the downstream library said: 'Error -3 while decompressing data: invalid
              distance code'.
```

Thank you!

**Comment by meren** [comment]
Unfortunately this is not a bug on our end, @clarelou0128 :/ I just run it, and it worked for me.

Please see #1738 for more info.

**Comment by clarelou0128** [comment]
Thanks for reply.

I flagged the `anvi-setup-ncbi-cogs` run with `--debug` and I got following messages:
```
Traceback for debugging
================================================================================
  File "/home/clarelou/miniconda3/envs/anvio-7.1/bin/anvi-setup-ncbi-cogs", line 46, in <module>
    setup.create()
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/cogs.py", line 615, in create
    self.setup_raw_data()
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/cogs.py", line 844, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/cogs.py", line 770, in format_protein_db
    raise ConfigError(f"Something went wrong while decompressing the downloaded file :/ It is likely that "
================================================================================


Config Error: Something went wrong while decompressing the downloaded file :/ It is likely
              that the download failed and only part of the file was downloaded. If you would
              like to try again, please run the setup command with the flag `--reset`. Here is
              what the downstream library said: 'Error -3 while decompressing data: invalid
              block type'.
```

I then looked into `cogs.py` by running `python cogs.py -h` and here is what I see:
```
Traceback (most recent call last):
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/cogs.py", line 13, in <module>
    import anvio
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/__init__.py", line 93, in <module>
    import anvio.constants as constants
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/constants.py", line 7, in <module>
    import numpy
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/numpy/__init__.py", line 223, in <module>
    from .testing import Tester
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/numpy/testing/__init__.py", line 8, in <module>
    from unittest import TestCase
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/unittest/__init__.py", line 64, in <module>
    from .main import TestProgram, main
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/unittest/main.py", line 4, in <module>
    import argparse
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/argparse.py", line 14, in <module>
    import anvio.terminal as terminal
  File "/home/clarelou/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/terminal.py", line 22, in <module>
    import anvio.constants as constants
AttributeError: module 'anvio' has no attribute 'constants'
```

**Comment by ivagljiva** [comment]
Hi @clarelou0128, 

> Not sure if this issue I am encountering is indeed related to the internet speed :/

Actually, it probably is. Some users have reported that they had to run `anvi-setup-ncbi-cogs --reset` multiple times before it worked (see #1647 for more examples and discussion).

Your only option is to keep trying again, I'm afraid.

Regardless,
> I then looked into cogs.py by running python cogs.py -h

This will never work and tells us nothing. `cogs.py` is a module, not a script. You can't run it like that.

**Comment by clarelou0128** [comment]
Thanks!

I eventually figured out. It does have something to do with the fact that download is not complete. So I downloaded all files anvio needs directly from the NCBI site and used the anvio-setup script and no more decompressing issues.

**Comment by ivagljiva** [comment]
Excellent, I'm so glad you found a solution!
