### ISSUE TITLE
[BUG] anvi-self-test --suite pangenomics -- many errors

### ISSUE THREAD

**Issue by HMorrison** [merenlab/anvio#1898]
## Short description of the problem

"anvi-self-test --suite pangenomics" runs, but with lots of errors. Is it worth going through it?

also tested instructions for 
"A real example for committed tutorial readers: A Prochlorococcus pangenome"

And it too, generated a lot of errors. 

## anvi'o version
Anvi'o .......................................: hope (v7.1-dev)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 3
tRNA-seq database ............................: 2

## System info
MacOS Monterey 12.1; installation of anvio-dev following instructions

## Detailed description of the issue
WARNING
===============================================
VERY BAD NEWS. The alignment of sequences with 'Muscle' in the gene cluster
'GC_00000001' failed for some reason. Since the real answer to 'why' is too deep
in the matrix, there is no reliable solution for anvi'o to find it for you, BUT
THIS WILL AFFECT YOUR SCIENCE GOING FORWARD, SO YOU SHOULD CONSIDER ADDRESSING
THIS ISSUE FIRST. If you re-run your last command with a `--debug` flag, anvi'o
will generate more information for you about the contenets of this gene cluster
(but if you are seeing millions of these warnings, it may not be a good idea
since with the `--debug` flag anvi'o will generate a FASTA file in a temporary
directory with the contents of the gene cluster, and will not attempt to delete
them later).

WARNING
===============================================
VERY BAD NEWS. The alignment of sequences with 'Muscle' in the gene cluster
'GC_00000116' failed for some reason. Since the real answer to 'why' is too deep
in the matrix, there is no reliable solution for anvi'o to find it for you, BUT
THIS WILL AFFECT YOUR SCIENCE GOING FORWARD, SO YOU SHOULD CONSIDER ADDRESSING
THIS ISSUE FIRST. If you re-run your last command with a `--debug` flag, anvi'o
will generate more information for you about the contenets of this gene cluster
(but if you are seeing millions of these warnings, it may not be a good idea
since with the `--debug` flag anvi'o will generate a FASTA file in a temporary
directory with the contents of the gene cluster, and will not attempt to delete
them later).

WARNING
===============================================
You did not provide a contigs database. Fine. So be it. But know this: anvi'o
has no way to check the consistency of names you provide in the input file. So
if you made a mistake while generating this collection, it probably will cause
issues later on.

Item names in input ..........................: 117
Num bins in input ............................: 3
Items in pan database ........................: 121
Item names shared between input and db .......: 117

WARNING
==============================================================
Please read carefully. At this part of the code anvi'o attempts to get sequences
for the gene clusters you are interested in. While it was the amino acid
sequences that were aligned here, you are you are asking for DNA sequences. Even
though the amino acid sequence alignment summary (the anvi'o way of storing
alignment information) can be used to align DNA sequences instantaneously, due
to intricacies associated with the gene calling step, the amino acid sequence of
a gene stored in the contigs database may differ from its DNA sequence (true
story). For those rare instances, the alignment summary for the amino acid
sequence may no longer be used to make sense of the DNA sequence (see
https://github.com/merenlab/anvio/issues/772 for more information). What needs
to be done is to do another alignment on the fly. But as you probably already
have already guessed, anvi'o will not do that for you, and instead it will
report your DNA sequences for your genes in your gene clusters unaligned. If you
really really want to try and see whether it will work for your gene clusters
here, you can try to include `--just-do-it` flag in your command line.

Sequence type ...............................................: DNA
Num sequences reported ......................................: 309
Output FASTA file ...........................................: aligned_gene_sequences_in_GENE_CLUSTER_BIN_1_CORE_DNA.fa

Config Error: Something went wrong during the functional enrichment analysis :( We don't know
              what happened, but this log file could contain some clues:
              /var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmpq6q3cp11

Config Error: According to the exit code ('255'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry
              just a bit less.

[tmpq6q3cp11.txt](https://github.com/merenlab/anvio/files/8209867/tmpq6q3cp11.txt)

**Comment by meren** [comment]
I'll look into this. Most of them are warnings that we should report as a single one (although I'm not sure why there are so many issues with alignment of gene clusters). The last one is due to an R library, that we still haven't found a way to get installed properly the first time.

Thank you for the report, Hilary.

**Comment by meren** [comment]
Hey @HMorrison, 

I've made some changes in the codebase that should make your error logs much more readable. I still am not sure why the alignment for, say `GC_00000116` fails. But you shouldn't worry about it. The output messages will now help you pinpoint the problem when you are working on your own pangenomes.

**Comment by meren** [comment]
(you can run `git pull` in the anvi'o code directory to update your copy of the development branch)

**Comment by HMorrison** [comment]
Since I am not a wizard, nor a git regular, 'rebase' means restriction enzyme digest database to me. :). "git pull" by itself threw an error, but activating anvio-dev in a conda terminal window seems to have updated anvio-dev, but with hints. I think I'm going to follow the metagenomic tutorial at the start, to make sure I generate the contigs-db correctly. I seem to recall a contigs renaming step...

GENE CLUSTERS SEQUENCE ALIGNMENT WARNING: fewer occurrences, thanks. Still scary. Will see what happens with my own contigs.

**Comment by meren** [comment]
The funny thing is that `anvi-self-test` should generate no "GENE CLUSTERS SEQUENCE ALIGNMENT WARNING" at all. That is the case on my own computer for instance. So I am not sure what is going on with yours :)

**Comment by HMorrison** [comment]
It's not the anvi-self-test, it's anvi-self-test --suite pangenomics.

**Comment by meren** [comment]
Yes, that's what I meant :)

**Comment by HMorrison** [comment]
muscle itself with align those sequences just fine, but were they supposed to be in an alignment file already? 

>g01_38
------------------------------------------------------MPAFP-
------------------------------------------------------------
--------YT-------------------------------------ADYFSGLTATTAA
LAALHKARETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYK
CADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWL
ATHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKF
KNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED
>g02_38
------------------------------------------------------MPAFP-
------------------------------------------------------------
--------YT-------------------------------------ADYFSGLTATTAA
LAALHKARETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYK
CADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWL
ATHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKF
KNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED
>g03_34
MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQ
LSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVI
AHLSGFGQYGTEEYTNLPAYNTIAQAFSGYLIQNGDVDQPMPAFPYTADYFSGLTATTAA
LAALHKVRETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYK
CADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWL
AAHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKF
KNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED
>g01_39
MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQ
LSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVI
AHLSGFGQYG-------------------------------------TEEYTNLPA----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>g02_39
MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQ
LSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVI
AHLSGFGQYG-------------------------------------TEEYTNLPA----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------


/Users/morrison/miniconda3/envs/anvio-dev/bin/muscle

**Comment by meren** [comment]
> 117 failed alignments.

WHAT?! :)

This means NONE of your gene clusters are aligned. Let's look a bit deeper. Can you please save this as test.py on your terminal where you have anvi'o environment activated,

``` python
gene_sequences = [('g01_38', 'MPAFPYTADYFSGLTATTAALAALHKARETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYKCADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWLATHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKFKNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED'), ('g02_38', 'MPAFPYTADYFSGLTATTAALAALHKARETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYKCADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWLATHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKFKNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED'), ('g03_34', 'MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQLSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVIAHLSGFGQYGTEEYTNLPAYNTIAQAFSGYLIQNGDVDQPMPAFPYTADYFSGLTATTAALAALHKVRETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYKCADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWLAAHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKFKNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED'), ('g01_39', 'MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQLSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVIAHLSGFGQYGTEEYTNLPA'), ('g02_39', 'MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQLSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVIAHLSGFGQYGTEEYTNLPA')]
[('g01_20', 'MATNKFDVVFSYCGDNIKEFILLLPYNKSLEMYELNDQKIQYLTAPNINIHKMSLSNITIEKSNLSYGYYFSCVLSNISCFESDLSNTIFSNGEINNLFIKKSNIFGASFTNTRIKNLLCEDIMPGRWTTQLVNKHLGYRYTGVFKTLASIDDKPSRFEILIPLVQTLVRDNVKLNNDVYKELKKFMHDYDKTSPEMRKYLQSINESMFLMKNIAHQN'), ('g02_20', 'MATNKFDVVFSYCGDNIKEFILLLPYNKSLEMYELNDQKIQYLTAPNINIHKMSLSNITIEKSNLSYGYYFSCVLSNISCFESDLSNTIFSNGEINNLFIKKSNIFGASFTNTRIKNLLCEDIMPGRWTTQLVNKHLGYRYTGVFKTLASIDDKPSRFEILIPLVQTLVRDNVKLNNDVYKELKKFMHDYDKTSPEMRKYLQSINESMFLMKNIAHQN'), ('g03_18', 'MTNGISTSPHCLYKSNIVDDVIINKTRQNELVKVFCEYKTEFLILFDDFFRSHNLPKPSPVLHHFFQYTHLRDAYFYRCKLIEHTVQFYFFKHKGITLLRLDVFDDRTSECLSEEIKIYQECHEKFVNFLKANFNQEIYPQLYTPEIFYEACRNLQSFYDHQETSQNAKYSAIDKKKSHLNQEIKKLIKKNIFPELYNEQCNKIPSSSIDDNQGIMWQNFKTSNIAYSQLCKKLSLFKSIPSRLIKKSAYCSTENTITNKFDVVFSYCGNNVKEFILLLPYNKSLEMHELNEQNIQYLTALNINIHKMLLSNITIEKSDLSYGYYFGCVLPNILCFESDLSNTIFSNGEINNLFIKKSNIFGASFTNTRIKNLLCEDIMPGRWTTQLVNKHLGYRYTGVFKTLASIDDKPSRFEILIPLVQTLVRDNVKLNNDVYKELNKFMHDYDKTSSEMRKYLKSINECMFLMKNIAHQN'), ('g01_23', 'MTDGISTSPHCLYKSNIVDDVIINKTRQNELVKVFCEYKTEFLILFDDFFRSQDFPKPSPVLHHFFQYTHLRDAHFYRCKLIEHTVQFYFLNTKASHYLDWMFLMTEQANVFLKRW'), ('g02_23', 'MTDGISTSPHCLYKSNIVDDVIINKTRQNELVKVFCEYKTEFLILFDDFFRSQDFPKPSPVLHHFFQYTHLRDAHFYRCKLIEHTVQFYFLNTKASHYLDWMFLMTEQANVFLKRW')]
[('g01_105', 'MPPRRYNPDTRRDELLERINLDIPGAVAQALREDLGGTVDANNDITAKLLPENSRSHATVITRENGVFCGKRWVEEVFIQLAGDDVTIIWHVDDGDVINANQSLFELEGPSRVLLTGERTALNFVQTLSGVASKVRHYVELLEGTNTQLLDTRKTLPGLRSALKYAVLCGGGANHRLGLSDAFLIKENHIIASGSVRQAVEKASWLHPDAPVEVEVENLEELDEALKAGADIIMLDNFETEQMREAVKRTNGKALLEVSGNVTDKTLREFAETGVDFISVGALTKHVQALDLSMRFR'), ('g02_105', 'MPPRRYNPDTRRDELLERINLDIPGAVAQALREDLGGTVDANNDITAKLLPENSRSHATVITRENGVFCGKRWVEEVFIQLAGDDVTIIWHVDDGDVINANQSLFELEGPSRVLLTGERTALNFVQTLSGVASKVRHYVELLEGTNTQLLDTRKTLPGLRSALKYAVLCGGGANHRLGLSDAFLIKENHIIASGSVRQAVEKASWLHPDAPVEVEVENLEELDEALKAGADIIMLDNFETEQMREAVKRTNGKALLEVSGNVTDKTLREFAETGVDFISVGALTKHVQALDLSMRFR'), ('g03_102', 'MPPRRYNPDTRRDELLERINLDIPGAVAQALREDLGGTVDANNDITAKLLPENSRSHATVITRENGVFCGKRWVEEVFIQLAGDDVTIIWHVDDGDVINANQSLFELEGPSRVLLTGERTALNFVQTLSGVASKVRHYVELLEGTNTQLLDTRKTLPGLRSALKYAVLCGGGANHRLGLSDAFLIKENHIIASGSVRQAVEKASWLHPDAPVEVEVENLEELDEALKAGADIIMLDNFETEQMREAVKRTNGKALLEVSGNVTDKTLREFAETGVDFISVGALTKHVQALDLSMRFR')]

from anvio.drivers import Aligners
import anvio.terminal as terminal

aligners = Aligners()

aligner = aligners.select(None, quiet=False)
alignments = aligner(run=terminal.Run()).run_stdin(gene_sequences, debug=True)

print()
print("Alignments:")
print()
print(alignments)
```

And run it like this:

```
python test.py
```

Please send the terminal output, as well as the log file, along with the output of this command please:

```
muscle --version
```

**Comment by HMorrison** [comment]
(anvio-dev) morrison2: which python
/Users/morrison/miniconda3/envs/anvio-dev/bin/python
(anvio-dev) morrison2: muscle --version
muscle 5.1.osx64 []
Built Feb 10 2022 07:52:24

(anvio-dev) morrison2: which muscle
/Users/morrison/miniconda3/envs/anvio-dev/bin/muscle
(anvio-dev) morrison2: python test.py

CITATION
===============================================
The workflow you are using will likely use 'muscle' by Edgar,
doi:10.1093/nar/gkh340 (http://www.drive5.com/muscle) to align your sequences.
If you publish your findings, please do not forget to properly credit this tool.

Running muscle ...............................: 5 sequences will be aligned
Log file path ................................: /var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmppjwq4vut/00_log.txt
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    alignments = aligner(run=terminal.Run()).run_stdin(gene_sequences, debug=True)
  File "/Users/morrison/github/anvio/anvio/drivers/muscle.py", line 67, in run_stdin
    "sequences :/ You can find the output in this log file: %s" % (len(sequences_list), log_file_path))
anvio.errors.ConfigError:

Config Error: Drivers::Muscle: Something went wrong with this alignment that was working on 5
              sequences :/ You can find the output in this log file:
              /var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmppjwq4vut/00_log.txt

**Comment by meren** [comment]
And what does the log file says?

```
/var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmppjwq4vut/00_log.txt
```

I also need the output of this please:

```
muscle --version
```

**Comment by meren** [comment]
How come your `muscle` is `v5.1.osx64` and mine is `v3.8.1551`?

I guess you didn't install muscle via conda?

**Comment by meren** [comment]
Can you please also run this, Hilary:

```
conda list | grep muscle
muscle                    3.8.1551             h770b8ee_5    bioconda
```

**Comment by HMorrison** [comment]
> /var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmppjwq4vut/00_log.txt

(anvio-dev) morrison2: cat /var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmppjwq4vut/00_log.txt
# DATE: 09 Mar 22 14:35:51
# CMD LINE: muscle -quiet
# THIS IS THE OUTPUT YOU ARE LOOKING FOR:


(anvio-dev) morrison2:

**Comment by meren** [comment]
Maybe I am a bit behind with `muscle`. I will try to install your version.

**Comment by HMorrison** [comment]
> 

I followed your tutorial--figured muscle was one of the packages.

**Comment by HMorrison** [comment]
(anvio-dev) morrison2: conda list | grep muscle
muscle                    5.1                  he1e422e_0    bioconda

**Comment by meren** [comment]
Meanwhile, can you please try to downgrade `muscle` with this and re-run the `test.py` if this step works well:

```
conda install -c bioconda muscle=3.8.1551
```

**Comment by HMorrison** [comment]
Trying muscle uninstall but I have a meeting with Blair before I can get back to it.

**Comment by HMorrison** [comment]
(anvio-dev) morrison2: conda list | grep muscle
muscle                    3.8.1551             hb280591_6    bioconda


(anvio-dev) morrison2: python test.py

CITATION
===============================================
The workflow you are using will likely use 'muscle' by Edgar,
doi:10.1093/nar/gkh340 (http://www.drive5.com/muscle) to align your sequences.
If you publish your findings, please do not forget to properly credit this tool.

Running muscle ...............................: 5 sequences will be aligned
Log file path ................................: /var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmpjqy_1lp5/00_log.txt

Alignments:

{'g01_38': '------------------------------------------------------MPAFP---------------------------------------------------------------------YT-------------------------------------ADYFSGLTATTAALAALHKARETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYKCADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWLATHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKFKNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED', 'g02_38': '------------------------------------------------------MPAFP---------------------------------------------------------------------YT-------------------------------------ADYFSGLTATTAALAALHKARETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYKCADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWLATHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKFKNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED', 'g03_34': 'MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQLSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVIAHLSGFGQYGTEEYTNLPAYNTIAQAFSGYLIQNGDVDQPMPAFPYTADYFSGLTATTAALAALHKVRETGKGESIDIAMYEVMLRMGQYFMMDYFNGGEMCPRMSKGKDPYYAGCGLYKCADGYIVMELVGITQIEECFKDIGLAHLLGTPEIPEGTQLIHRIECPYGPLVEEKLDAWLAAHTIAEVKERFAELNIACAKVLTVPELESNPQYVARESITQWQTMDGRTCKGPNIMPKFKNNPGQIWRGMPSHGMDTAAILKNIGYSENDIQELVSKGLAKVED', 'g01_39': 'MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQLSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVIAHLSGFGQYG-------------------------------------TEEYTNLPA-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------', 'g02_39': 'MDHLPMPKFGPLAGLRVVFSGIEIAGPFAGQMFAEWGAEVIWIENVAWADTIRVQPNYPQLSRRNLHALSLNIFKDEGREAFLKLMETTDIFIEASKGPAFARRGITDEVLWQHNPKLVIAHLSGFGQYG-------------------------------------TEEYTNLPA-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'}

**Comment by meren** [comment]
Great :) This should run now without any unaligned gene clusters :)

```
anvi-self-test --suite pangenomics
```

**Comment by HMorrison** [comment]
I tested it. 

A few errors, but not of alignment. 

WARNING
===============================================
You did not provide a contigs database. Fine. So be it. But know this: anvi'o
has no way to check the consistency of names you provide in the input file. So
if you made a mistake while generating this collection, it probably will cause
issues later on.

WARNING
===============================================
4 item(s) that were in the database, but were not in the input file, will not be
described by any bin in the collection test_collection. That is totally fine,
but anvi'o hopes that you are aware of that. This means you have more things in
your database than the number of things your input file describes. Here is an
example of something that is in your database but not in any bin in your input
file: GC_00000121.

WARNING
===============================================
As per your request, 4 items that were not in any of the bins in the collection
'test_collection' are stored in the output file under the bin name
'UNBINNED_ITEMS_BIN'.

WARNING
==============================================================
Some of your groups have very few genomes in them, so if you are running
functional enrichment, the statistical test may not be very reliable. The
minimal number of genomes in a group for the test to be reliable depends on a
number of factors, but we recommend proceeding with great caution because the
following groups have fewer than 8 genomes: G1, G2.


...and this produced a final "Config Error", as predicted. 

Config Error: Something went wrong during the functional enrichment analysis :( We don't know
              what happened, but this log file could contain some clues:
              /var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/tmphcu27c5k




Config Error: According to the exit code ('255'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry
              just a bit less.

**Comment by meren** [comment]
Only one error, which is from the functional enrichment analysis due to R libraries (probably the tidyverse, a true PITA).

I will update the installation instructions to specify the muscle version. Thank you for your help, Hilary!

**Comment by HMorrison** [comment]
You might include the suggestion to uninstall muscle before trying to downgrade the version--I had to do that.

**Comment by meren** [comment]
Hey Hilary,

In case you'd like to take a look, there is this new chapter in the installation document that may solve your functional enrichment errors:

https://anvio.org/install/#when-i-run-anvio-test-for-pangenomics-i-get-errors-related-to-the-functional-enrichment-step

**Comment by HMorrison** [comment]
Hahaha--

> install.packages("stringi", "tidyverse", "magrittr", "optparse"), repos="https://cloud.r-project.org")
Error: unexpected ',' in "install.packages("stringi", "tidyverse", "magrittr", "optparse"),"

**Comment by HMorrison** [comment]
> help(install.packages)
> install.packages("stringi", "tidyverse", "magrittr", "optparse", repos="https://cloud.r-project.org")
Warning in install.packages("stringi", "tidyverse", "magrittr", "optparse",  :
  'lib = "tidyverse"' is not writable
Would you like to use a personal library instead? (yes/No/cancel)



Deleted the extra parenthesis, but there's a new error.

**Comment by meren** [comment]
Stupid me. Fixed the typo:

```
install.packages("stringi", "tidyverse", "magrittr", "optparse", repos="https://cloud.r-project.org")
```

**Comment by meren** [comment]
I think we needed to add a parenthesis, not remove one :) Can you please try this one:

```
install.packages(c("stringi", "tidyverse", "magrittr", "optparse"), repos="https://cloud.r-project.org")
```

**Comment by HMorrison** [comment]
Same error:

> install.packages(c("stringi", "tidyverse", "magrittr", "optparse"), repos="https://cloud.r-project.org")
Warning in install.packages(c("stringi", "tidyverse", "magrittr", "optparse"),  :
  'lib = "/Library/Frameworks/R.framework/Versions/3.6/Resources/library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel)

Different version of R?

**Comment by meren** [comment]
When I run this on my terminal,

```
Rscript -e 'install.packages(c("stringi", "tidyverse", "magrittr", "optparse"), repos="https://cloud.r-project.org")'
```

It looks like this:
![image](https://user-images.githubusercontent.com/197307/157903444-a25ded62-1715-4158-85b7-0651a11bc9fb.png)

R version:

```
R --version
R version 3.6.1
```

**Comment by HMorrison** [comment]
I'm version 3.6.2. Should I downgrade again? :)

But the 'not writable' error suggests that it's a permissions problem. Not worth trying to fix now.

**Comment by meren** [comment]
That 'not writable' error comes from a typo in the command line, Hilary. R doesn't realize they're all packages. Are you sure you are getting that error when you run this:

```
Rscript -e 'install.packages(c("stringi", "tidyverse", "magrittr", "optparse"), repos="https://cloud.r-project.org")'
```

**Comment by HMorrison** [comment]
Okay--it ran this time (in anvio-dev), but with lots of errors. 

icu55/i18n/decNumber.h:87:5: note: array 'lsu' declared here
    decNumberUnit lsu[DECNUMUNITS];
    ^
icu55/i18n/decNumber.h:71:27: note: expanded from macro 'decNumberUnit'
    #define decNumberUnit uint8_t
                          ^
10 warnings generated.

....

Error in library.dynam(lib, package, package.lib) :
  shared object ‘rlang.dylib’ not found
Calls: <Anonymous> ... loadNamespace -> namespaceImport -> loadNamespace -> library.dynam
Execution halted
ERROR: lazy loading failed for package ‘tidyverse’
* removing ‘/Users/morrison/Library/R/3.6/library/tidyverse’
* restoring previous ‘/Users/morrison/Library/R/3.6/library/tidyverse’

The downloaded source packages are in
	‘/private/var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/RtmpG7Govq/downloaded_packages’
Warning messages:
1: In install.packages(c("stringi", "tidyverse", "magrittr", "optparse"),  :
  installation of package ‘stringi’ had non-zero exit status
2: In install.packages(c("stringi", "tidyverse", "magrittr", "optparse"),  :
  installation of package ‘tidyverse’ had non-zero exit status

**Comment by meren** [comment]
What a mess :/ Stackoverflow is filled with similar errors, but I'm not sure which one to follow :/

**Comment by HMorrison** [comment]
Here's more:
(anvio-dev) morrison2: Rscript -e "library('tidyverse')"
Error: package or namespace load failed for ‘tidyverse’ in library.dynam(lib, package, package.lib):
 shared object ‘rlang.dylib’ not found
In addition: Warning message:
package ‘tidyverse’ was built under R version 3.6.2
Execution halted
(anvio-dev) morrison2: Rscript -e 'install.packages(c("tidyverse"), repos="https://cloud.r-project.org")'
Installing package into ‘/Users/morrison/Library/R/3.6/library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/tidyverse_1.3.1.tar.gz'
Content type 'application/x-gzip' length 702779 bytes (686 KB)
==================================================
downloaded 686 KB

* installing *source* package ‘tidyverse’ ...
** package ‘tidyverse’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in library.dynam(lib, package, package.lib) :
  shared object ‘rlang.dylib’ not found
Calls: <Anonymous> ... loadNamespace -> namespaceImport -> loadNamespace -> library.dynam
Execution halted
ERROR: lazy loading failed for package ‘tidyverse’
* removing ‘/Users/morrison/Library/R/3.6/library/tidyverse’
* restoring previous ‘/Users/morrison/Library/R/3.6/library/tidyverse’

The downloaded source packages are in
	‘/private/var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/RtmpFdWSYt/downloaded_packages’
Warning message:
In install.packages(c("tidyverse"), repos = "https://cloud.r-project.org") :
  installation of package ‘tidyverse’ had non-zero exit status

**Comment by HMorrison** [comment]
Nope, see next email. It's not just a typo.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> On Mar 11, 2022, at 10:57 AM, A. Murat Eren ***@***.***> wrote:
> 
> 
> Stupid me. Fixed the typo:
> 
> install.packages("stringi", "tidyverse", "magrittr", "optparse", repos="https://cloud.r-project.org")
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.
>
