### ISSUE TITLE
[BUG] anvi-run-pfams throws a "UnicodeDecodeError" with Pfam database version  32.0 (2018-08)

### ISSUE THREAD

**Issue by Jtrachsel** [merenlab/anvio#1907]
## Short description of the problem

`anvi-run-pfams` throws an "UnicodeDecodeError" with Pfam database version  32.0 (2018-08)

## anvi'o version

```
Anvi'o .......................................: hope (v7.1) 
Profile database .............................: 38 
Contigs database .............................: 20 
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info
I am using an HPC linux server with a SLURM queue
```
$ lsb_release -a   
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core


 ```

## Detailed description of the issue

I am trying to run through the test suite for PlasX:  https://github.com/michaelkyu/PlasX#step-1-identify-genes-and-annotate-cogs-and-pfams-using-anvio 
  
I installed anvio into a conda environment and tested the install as recommended here: https://anvio.org/install/ 

Everything was working well until this line of code:
``` anvi-run-pfams -T $THREADS --pfam-data-dir Pfam_v32 -c $PREFIX.db ```

I tried multiple times to reset the pfam database including letting it install to the standard directory
ie with :   

```anvi-setup-pfams --pfam-version 32.0 --pfam-data-dir Pfam_v32```
and
```anvi-setup-pfams --pfam-version 32.0```

However, each time I setup the pfam database the result is the same.

Here is the full error message:  
```
$ anvi-run-pfams -T $THREADS -c $PREFIX.db   

Pfam database directory ......................: /project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/data/misc/Pfam
Pfam database version ........................: 32.0 (2018-08)
Traceback (most recent call last):
  File "/project/fsepru/conda_envs/anvio-7.1/bin/anvi-run-pfams", line 41, in <module>
    main(args)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/project/fsepru/conda_envs/anvio-7.1/bin/anvi-run-pfams", line 24, in main
    p = pfam.Pfam(args)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/pfam.py", line 230, in __init__
    self.load_catalog()
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/pfam.py", line 282, in load_catalog
    no_header=True
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/utils.py", line 3400, in get_TAB_delimited_file_as_dictionary
    filesnpaths.is_file_tab_delimited(file_path, separator=separator)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/filesnpaths.py", line 212, in is_file_tab_delimited
    num_fields_set = set([len(line.split(separator)) for line in f.readlines()])
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8163: ordinal not in range(128)
```

I would appreciate any help you could give me for remedying this problem.

Thanks!

**Comment by meren** [comment]
This is very interesting, @Jtrachsel. I can't seem to be able to reproduce the error. I wonder if it is related to the CentOS system by any chance.

Can you please download [issue_1907.tar.gz](https://github.com/merenlab/anvio/files/8344020/issue_1907.tar.gz) to your server, and run the following in that directory (both directly and through the HPC) to see if you get the same error:

```
python test.py
```
 
Thank you for your help!

**Comment by Jtrachsel** [comment]
Thanks for the quick response.

Here is the output from the python test.py command:

```
$ which python
/project/fsepru/conda_envs/anvio-7.1/bin/python

$ python test.py

Traceback (most recent call last):
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/filesnpaths.py", line 193, in is_file_tab_delimited
    line = f.readline().strip(' ')
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    filesnpaths.is_file_tab_delimited('test.txt')
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/filesnpaths.py", line 202, in is_file_tab_delimited
    raise FilesNPathsError("The probability that `%s` is a tab-delimited file is zero." % file_path)
anvio.errors.FilesNPathsError:

File/Path Error: The probability that `test.txt` is a tab-delimited file is zero.```

**Comment by Jtrachsel** [comment]
This seems to be an issue with my anvio install.  Other commands, though not all are having troubles parsing text files.

```

$ anvi-help
Traceback (most recent call last):
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/filesnpaths.py", line 262, in is_file_plain_text
    open(os.path.abspath(file_path), 'rU').read(512)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6612: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/fsepru/conda_envs/anvio-7.1/bin/anvi-help", line 285, in <module>
    ProgramSearch(args).process()
  File "/project/fsepru/conda_envs/anvio-7.1/bin/anvi-help", line 63, in __init__
    anvio_programs = p.AnvioPrograms(args)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/programs.py", line 163, in __init__
    AnvioAuthors.__init__(self, r=self.run, p=self.progress)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/authors.py", line 38, in __init__
    self.init_authors()
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/authors.py", line 52, in init_authors
    authors_yaml = utils.get_yaml_as_dict(self.authors_yaml_file_path)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/utils.py", line 4085, in get_yaml_as_dict
    filesnpaths.is_file_plain_text(file_path)
  File "/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-packages/anvio/filesnpaths.py", line 273, in is_file_plain_text
    raise FilesNPathsError("The file at '%s' does not seem to be plain a text file :/" % file_path)
anvio.errors.FilesNPathsError:

File/Path Error: The file at '/project/fsepru/conda_envs/anvio-7.1/lib/python3.6/site-
                 packages/anvio/data/misc/AUTHORS/AUTHORS.yaml' does not seem to be plain a text
                 file :/

```

**Comment by xvazquezc** [comment]
Likely related to UTF-8 vs ascii encoding. Do you have any UTF-8 character
without ascii equivalent in your path name? E.g. ` ñ ...
Also it could be due to your system locale.
Check this out
https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal

**Comment by Jtrachsel** [comment]
@xvazquezc you were right, the system locale was not set correctly on this server.  

```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

```

I used `export LC_ALL="en_US.UTF-8"` to set the locale.  Now all the commands are working perfectly.  Thanks for the help @meren and @xvazquezc.

**Comment by meren** [comment]
thanks for figuring this out! I put a reminder for future references. but I feel like it would have been better for anvi'o to check the locale every time it is initialized (such as in `anvio/__init__.py`) to cover all future instances.

**Comment by meren** [comment]
(although I'm not sure how to do it best)

**Comment by meren** [comment]
hey @Jtrachsel, do you still have access to your environment with broken locale? If yes, can you please run this command there and send the output?

```
python -c "import locale; print(locale.getdefaultlocale())"
```

No worries if it is no longer possible.

**Comment by Jtrachsel** [comment]
No problem.


locale is still unset:
```

$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

```

And here's the command you requested:

```
$ python -c "import locale; print(locale.getdefaultlocale())"
('en_US', 'UTF-8')

```

**Comment by meren** [comment]
Thanks, @Jtrachsel. I was hoping to see `(None, None)` :/ so a global solution to this problem is not going to be very easy.
