### ISSUE TITLE
[BUG] anvi-gen-contigs-database gives AttributeError

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#1933]
## Short description of the problem

When I run 
```bash
anvi-gen-contigs-database -f fasta.fa -o test.db
```

I get the error:
```
Traceback (most recent call last):
  File "/Users/efogarty/github/anvio/bin/anvi-gen-contigs-database", line 63, in <module>
    main(args)
  File "/Users/efogarty/github/anvio/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/Users/efogarty/github/anvio/bin/anvi-gen-contigs-database", line 31, in main
    a.create(args)
  File "/Users/efogarty/github/anvio/anvio/dbops.py", line 4452, in create
    gene_calls_tables.populate_genes_in_splits_tables()
  File "/Users/efogarty/github/anvio/anvio/tables/genecalls.py", line 563, in populate_genes_in_splits_tables
    contigs_without_any_gene_calls = list(set(self.contigs_info.keys()) - set(gene_calls_in_contigs_dict.keys()))
AttributeError: 'TablesForGeneCalls' object has no attribute 'contigs_info'
```
![image](https://user-images.githubusercontent.com/38365171/168127030-51dafe97-0872-48f7-99fb-0fa2207d6c2b.png)

## anvi'o version

Master

## Files to reproduce

Any fasta file should work with the command `anvi-gen-contigs-database -f fasta.fa -o test.db`

**Comment by meren** [comment]
Hmm. Intersting. I'm on it.

**Comment by meren** [comment]
Should be fine now, Emily. Sorry about that :)

**Comment by efogarty11** [comment]
np, thanks so much for fixing it! 😄
