### ISSUE TITLE
[BUG] Profile.db from anvi-export-locus have wrong info values

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1949]
## Short description of the problem

When using `anvi-export-locus`, it creates a contigs.db and a profile.db for each locus. Some profile.db info are NoneType (like min_coverage_for_variability: None, instead of 10 by default) which is problematic for downstream summary and maybe other commands. 

## anvi'o version

Github Main

## Detailed description of the issue

When using `anvi-export-locus`, it creates a contigs.db and a profile.db for each locus. I wanted to use `anvi-summarize` so I create a default collection and summarized it. 
I had the following error:
```
Traceback (most recent call last):
  File "/Users/ftrigodet/github/anvio/bin/anvi-summarize", line 122, in <module>
    main(args)
  File "/Users/ftrigodet/github/anvio/bin/anvi-summarize", line 68, in main
    summary.process()
  File "/Users/ftrigodet/github/anvio/anvio/summarizer.py", line 843, in process
    self.init()
  File "/Users/ftrigodet/github/anvio/anvio/summarizer.py", line 800, in init
    ('Min coverage for variability', humanize_n(int(self.p_meta['min_coverage_for_variability']))),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I've compared the db info of a regular profile.db and the one generated by `anvi-export-locus` and noticed that some value are 'None' instead of 0. I'm guessing that's why python is not happy about the 'NoneType'.

Normal profile.db:
```
DB Info (no touch)
===============================================
Database Path ................................: PROFILE.db
Description ..................................: _No description is provided_
db_type ......................................: profile (variant: None)
version ......................................: 38


DB Info (no touch also)
===============================================
anvio ........................................: 7.1-dev
sample_id ....................................: toto
samples ......................................: toto
merged .......................................: 0
blank ........................................: 1
default_view .................................: mean_coverage
min_contig_length ............................: 1000
max_contig_length ............................: 9223372036854775807
SNVs_profiled ................................: 1
SCVs_profiled ................................: 0
INDELs_profiled ..............................: 1
min_percent_identity .........................: 0
fetch_filter .................................: None
min_coverage_for_variability .................: 10
report_variability_full ......................: 0
contigs_db_hash ..............................: hash6bee38d8
creation_date ................................: 1656450742.62982
num_splits ...................................: 237
num_contigs ..................................: 51
total_length .................................: 4717681
available_item_orders ........................: tnf-splits:euclidean:ward,tnf:euclidean:ward
items_ordered ................................: 1
default_item_order ...........................: tnf:euclidean:ward
```

`anvi-export-locus` profile.db:
```
DB Info (no touch)
===============================================
Database Path ................................: PROFILE.db
Description ..................................: _No description is provided_
db_type ......................................: profile (variant: None)
version ......................................: 38


DB Info (no touch also)
===============================================
anvio ........................................: 7.1-dev
sample_id ....................................: titi
samples ......................................: titi
merged .......................................: 0
blank ........................................: 1
default_view .................................: mean_coverage
min_contig_length ............................: 0
max_contig_length ............................: 9223372036854775807
SNVs_profiled ................................: 1
SCVs_profiled ................................: None
INDELs_profiled ..............................: 1
min_percent_identity .........................: 0
fetch_filter .................................: None
min_coverage_for_variability .................: None
report_variability_full ......................: None
contigs_db_hash ..............................: hashe976c76f
creation_date ................................: 1656449488.99113
num_splits ...................................: 1
num_contigs ..................................: 1
total_length .................................: 22645
available_item_orders ........................: tnf-splits:euclidean:ward,tnf:euclidean:ward
items_ordered ................................: 1
default_item_order ...........................: tnf:euclidean:ward
```

## Files to reproduce
Here is a contig.db and blank profile.db for a single genome.
Use the following command to generate the output of `anvi-export-locus`:
```
anvi-export-locus -c CONTIGS.db -s nifH -n 10,10 -O nifH
```
Add a default collection and summarize (it will fail):
```
anvi-script-add-default-collection -c nifH_0001.db -p nifH_0001-PROFILE/PROFILE.db

anvi-summarize -c nifH_0001.db -p nifH_0001-PROFILE/PROFILE.db -C DEFAULT -o nifH-summary
```
[test.tar.gz](https://github.com/merenlab/anvio/files/9005391/test.tar.gz)

**Comment by meren** [comment]
The problem and the solution was not as simple as adding the default `10`. This is a blank profile, there shouldn't be any SNV/INDEL associated anything in it's self table. I've made a series of commits that corrects this logic.

Also, now you can simply do this, since the default collections will be added to blank profiles from `anvi-export-locus` automatically because it is 2022:

```
anvi-export-locus -c CONTIGS.db -s nifH -n 10,10 -O nifH
anvi-summarize -c nifH_0001.db -p nifH_0001-PROFILE/PROFILE.db -C DEFAULT -o nifH-summary
```

**Comment by meren** [comment]
Thank you and GOOD DAY, SIR.
