### ISSUE TITLE
[BUG] anvi-report-inversions another error message fix 

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#2006]
## Short description of the problem

Another error message spotted with @hdore. In this case, the bam file had some sequences with ... no sequence! 
This happens when you keep secondary mapping in your bam file and the rational is that the sequence is already stored at the other location where the read map. 

Anyhow, the error message could be more explicit and say that sequences are missing from the bam file - maybe due to secondary mapping. 

## anvi'o version

anvio dev

## Detailed description of the issue

Here is the error message:
```
✖ anvi-report-inversions encountered an error after 0:01:16.596704
Traceback (most recent call last):
  File "/home/hdore/github/anvio/bin/anvi-report-inversions", line 147, in <module>
    main(args)
  File "/home/hdore/github/anvio/anvio/terminal.py", line 879, in wrapper
    program_method(*args, **kwargs)
  File "/home/hdore/github/anvio/bin/anvi-report-inversions", line 26, in main
    I.process()
  File "/home/hdore/github/anvio/anvio/inversions.py", line 1238, in process
    self.process_db(entry_name, profile_db_path, bam_file_path)
  File "/home/hdore/github/anvio/anvio/inversions.py", line 409, in process_db
    true_inversions = self.get_true_inversions_in_stretch(inversion_candidates, bam_file, contig_name, start, stop)
  File "/home/hdore/github/anvio/anvio/inversions.py", line 692, in get_true_inversions_in_stretch
    true_inversions_in_stretch = self.test_inversion_candidates_using_short_reads(inversion_candidates, reads)
  File "/home/hdore/github/anvio/anvio/inversions.py", line 575, in test_inversion_candidates_using_short_reads
    if inversion_candidate.v1_left in read:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by FlorianTrigodet** [comment]
Solved with #2049
