### ISSUE TITLE
[BUG] Replace this text with a short but descriptive title

### ISSUE THREAD

**Issue by SilasK** [merenlab/anvio#2020]
## Short description of the problem

Replace this text with a single-sentence description of the problem.

## anvi'o version

I want to do a pangenome analysis of eukaryote genomes

I run this command with the files below and got the folowing error:

````
        "anvi-gen-contigs-database "
        " -f {input.fasta} "
        " -o {output} "
        " --external-gene-calls {input.genes} "
        " --ignore-internal-stop-codons &> {log} "
```

```
Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info
OSX, 10.14.6 
Recomended with conda and pip

## Detailed description of the issue

```
EXTERNAL GENE CALLS PARSER REPORT
===============================================
Num gene calls in file .......................: 8,410
Non-coding gene calls ........................: 0
Partial gene calls ...........................: 0
Num amino acid sequences provided ............: 8,410
  - For complete gene calls ..................: 8,410
  - For partial gene calls ...................: 0
Frames predicted .............................: 0
  - For complete gene calls ..................: 0
  - For partial gene calls ...................: 0
Gene calls marked as NONCODING ...............: 0
  - For complete gene calls ..................: 0
  - For partial gene calls ...................: 0
Gene calls with internal stops ...............: 5
  - For complete gene calls ..................: 5
  - For partial gene calls ...................: 0

                                                                                                                    
CONTIGS DB CREATE REPORT
===============================================
Split Length .................................: 20,000
K-mer size ...................................: 4
Skip gene calling? ...........................: False
External gene calls provided? ................: True
External gene calls file have AA sequences? ..: True
Proper frames will be predicted? .............: True
Ignoring internal stop codons? ...............: True
Splitting pays attention to gene calls? ......: True
[06 Dec 22 14:41:57 The South Loop] Contig "690" has 30 genes, and 51835 nts. Now computing: auxiliary ...  ETA: 9s 
✖ anvi-gen-contigs-database encountered an error after 0:00:32.440256
Traceback (most recent call last):
  File "/Users/silas/miniconda3/envs/anvio-7.1/bin/anvi-gen-contigs-database", line 63, in <module>
    main(args)
  File "/Users/silas/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/Users/silas/miniconda3/envs/anvio-7.1/bin/anvi-gen-contigs-database", line 31, in main
    a.create(args)
  File "/Users/silas/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/dbops.py", line 4356, in create
    nt_position_info_list = self.compress_nt_position_info(contig_length, genes_in_contig, genes_in_contigs_dict)
  File "/Users/silas/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/dbops.py", line 4475, in compress_nt_position_info
    nt_position_info_list[nt_position + 2] = 1
IndexError: list assignment index out of range

```
## Files to reproduce


[Archive 2.zip](https://github.com/merenlab/anvio/files/10167028/Archive.2.zip)

**Comment by meren** [comment]
Hey @SilasK, this is happening because you have partial gene calls in your external gene calls file (that are not marked as partial, by the way), and they explode something in the code. I am on it.

One option is to ignore such genes -- you have only two of them out of 8410 gene calls.

The other option is to do something slightly better, which I will try first and keep this issue updates.

**Comment by meren** [comment]
This particular problem, which will now produce a snafu warning, occurs in rare conditions, but also teaches us some lessons regarding the ability of anvi'o to recover information about which nucleotides that occur in ORFs occur in which positions in codons (i.e., 1st, 2nd, or 3rd). Not a show-stopper for MANY things, but it is something to keep in mind for others.

## The problem

Let me start by describing the problem. The following error happens,

``` pyhon
nt_position_info_list[nt_position + 2] = 1
      IndexError: list assignment index out of range
```

when the upstream code that loops the variable `nt_positions` via `range(start, stop, 3)`, where `start` and `stop` indicate gene boundaries, includes more items than "the length of the actual contig", which defines the size of the array `nt_position_info_list`. This only happens when **(1)** the gene length is not divisible by 3, where, the gene call is not necessarily a perfect list of codons even though the `3` in `range(start, stop, 3)` assumes that it is the case, AND **(2)** the gene happens to occur at the very beginning or end of the contig, so the rounding of the floating point ends up running out of the length of the contig, and yields an IndexError.

## The solution

The commit 1c10f1bf1801b3196ff83c3d5d6a74ccb79a004b solves this issue now by simply reporting those genes as 'bad genes', so the rest of the process can move on. @SilasK, you can track anvio-dev to avoid this problem.

But this highlights a much bigger issue to keep in mind, **especially for those who work with eukaryotic gene calls in anvi'o**: there are many cases we don't run into this problem, but it doesn't mean it is not there and it doesn't mean our codon position information for nucleotides are accurate for all genes. In eukaryotes we will often have the case of `gene_length % 3 > 0` due to their introns. But the vast majority will not even reported as bad genes because they will not be occurring at extremities of contigs to invoke this check. Another reason bad genes will not be reported as bad because they will happen to have `gene_length %3 == 0`, EVEN THOUGH they are partial or contain introns and as a result the information for them in `nt_position_info` (which aims to keep track of nucleotides to determine whether they are the first, second, or third nucleotides of codons in which they occur) will be flat out incorrect. Which means this information will be irrelevant in most cases for eukaryotes.

## Should I really care or go back to my work?

Probably you can complete ignore this and you'd be fine as there are only a few cases where the accuracy of nt position information is relevant:

* If you are looking at single-nucleotide variants in anvi'o interactive interface, colors of SNVs are defined by their position in the codon (where the third position shown in green, and the first and second position is red). For most genes, those colors will be uselsess.
* If you are relying on codon position information reported by the program `anvi-gen-variability-profile` for downstream analyses, that information will be misleading.

Apart from these negligible issues, everything else should be fine since no one else relies on this information. But I thought I'd mention them here for future references.

Please let me know if you have any questions.
