### ISSUE TITLE
[BUG] Replace this text with a short but descriptive title

### ISSUE THREAD

**Issue by xiongqian123456789** [merenlab/anvio#2065]
Hello
I meet the problem when used the Anvio-7.1, as follews:
(anvio-7.1) [xiongqian@mu02 TB19]$ anvi-gen-contigs-database -f final.fa -o contigs.db  -n "TB"
Input FASTA file .............................: /newlustre/home/xiongqian/anvi/TB19/final.fa
Name .........................................: TB
Description ..................................: No description is given

✖ anvi-gen-contigs-database encountered an error after 0:00:05.562413
Traceback (most recent call last):
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/bin/anvi-gen-contigs-database", line 63, in <module>
    main(args)
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/bin/anvi-gen-contigs-database", line 31, in main
    a.create(args)
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/dbops.py", line 4253, in create
    self.touch(db_variant)
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/dbops.py", line 3966, in touch
    self.db = db.DB(self.db_path, anvio.__contigs__version__, new_database=True)
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/db.py", line 87, in __init__
    self.table_names_in_db = self.get_table_names()
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/db.py", line 995, in get_table_names
    response = self._exec("""select name from sqlite_master where type='table'""")
  File "/newlustre/home/xiongqian/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/db.py", line 362, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: disk I/O error

However, the disk is enough，and the conda version is: conda 23.1.0
And I have no root right.

Much appreciate fir the reply and help!

**Comment by meren** [comment]
Hi @xiongqian123456789, there may be multiple explanations for the disk I/O error (files system integrity to accessibility to storage space left on the device), but none of these are related to anvi'o :/ Sorry.

Maybe you can try the anvio-dev version, and if the problem persists, you can try it on a different machine just to make sure it is not about the disk.
