### ISSUE TITLE
TypeError with anvi-profile

### ISSUE THREAD

**Issue by roo-weed** [merenlab/anvio#2079]
Hi all! I am trying to run anvi-profile and running into the following error (see below).
I am using Anvio 7.1 and Python 3.6.1. This looks similar to the error discussed here: https://github.com/merenlab/anvio/issues/1414, but that bug I believe was fixed in the 7.1 release. I've tried to run this with two separate bam file and database combinations and I got the same error both times, so I think it's something with my Anvio setup that is making this happen. Happy to share files if needed. Thanks so much for your help!

[12 May 23 11:16:35 Profiling w/1 thread] contigs are being pr (...)  ETA: ∞:∞:∞
✖ anvi-profile encountered an error after 0:00:07.756985
Traceback (most recent call last):
  File "/home/lweed/scratch-midway2/RooAnvio/bin/anvi-profile", line 104, in <module>
    main(args)
  File "/home/lweed/scratch-midway2/RooAnvio/lib/python3.6/site-packages/anvio/terminal.py", line 875, in wrapper
    program_method(*args, **kwargs)
  File "/home/lweed/scratch-midway2/RooAnvio/bin/anvi-profile", line 39, in main
    profiler.BAMProfiler(args)._run()
  File "/home/lweed/scratch-midway2/RooAnvio/lib/python3.6/site-packages/anvio/profiler.py", line 533, in _run
    self.profile_single_thread()
  File "/home/lweed/scratch-midway2/RooAnvio/lib/python3.6/site-packages/anvio/profiler.py", line 1014, in profile_single_thread
    contig = self.process_contig(bam_file, contig_name, contig_length)
  File "/home/lweed/scratch-midway2/RooAnvio/lib/python3.6/site-packages/anvio/profiler.py", line 967, in process_contig
    split.auxiliary.process(bam_file)
  File "/home/lweed/scratch-midway2/RooAnvio/lib/python3.6/site-packages/anvio/contigops.py", line 204, in process
    self.run_SNVs_and_indels(bam)
  File "/home/lweed/scratch-midway2/RooAnvio/lib/python3.6/site-packages/anvio/contigops.py", line 484, in run_SNVs_and_indels
    aligned_sequence_as_ord, reference_positions = read.get_aligned_sequence_and_reference_positions()
  File "/home/lweed/scratch-midway2/RooAnvio/lib/python3.6/site-packages/anvio/bamops.py", line 496, in get_aligned_sequence_and_reference_positions
    constants.cigar_consumption,
TypeError: can't unbox array from PyObject into native value.  The object maybe of a different type

**Comment by meren** [comment]
Hey @roo-weed,

Which mapping software did you use to generate your BAM files?

Would you mind trying the anvio-dev branch (installation instructions are on the web) and see if the problem persists?

**Comment by roo-weed** [comment]
Hi @meren!

I used bowtie2 to generate the SAM files and then converted them to BAM using samtools. 

Yes, I will try the anvio-dev branch! Thanks for the suggestion.

-Roo

**Comment by roo-weed** [comment]
Update: It works great on the dev branch! Thanks for the suggestion!
