### ISSUE TITLE
error :tarfile.ReadError: not a gzip file

### ISSUE THREAD

**Issue by 17863952296** [merenlab/anvio#2113]
all software is installed successfully, but when I run the command :pip install anvio-7.1.tar.gz, an error occur：
Processing ./anvio-7.1.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1092, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 278, in unpack_url
    return unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 251, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 261, in unpack_file
    untar_file(filename, location)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 177, in untar_file
    tar = tarfile.open(filename, mode)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
(anvio-7.1) [root@localhost dengziguang]# cd /root/mambaforge/envs/anvio-7.1/lib/python3.6/
(anvio-7.1) [root@localhost python3.6]# pip install anvio-7.1.tar.gz 
Processing ./anvio-7.1.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1092, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 278, in unpack_url
    return unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 251, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 261, in unpack_file
    untar_file(filename, location)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 177, in untar_file
    tar = tarfile.open(filename, mode)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
(anvio-7.1) [root@localhost python3.6]# pip install ./anvio-7.1.tar.gz 
Processing ./anvio-7.1.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1092, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 278, in unpack_url
    return unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 251, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 261, in unpack_file
    untar_file(filename, location)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/pip/_internal/utils/unpacking.py", line 177, in untar_file
    tar = tarfile.open(filename, mode)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/root/mambaforge/envs/anvio-7.1/lib/python3.6/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

**Comment by meren** [comment]
Hi @17863952296, you should try to re-download the file, because it certainly is a gzip file.

By the way, I'm not sure in what environment you're working, but you should never install anvi'o (nor any other software for that matter) with root privileges.
