### ISSUE TITLE
[BUG] anvi-help not working anymore

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#2146]
## Short description of the problem

With v8 or dev version, `anvi-help` is not working anymore. 

## anvi'o version

v8 and dev version.

## Detailed description of the issue

Example command: 
```
anvi-help gene
```

Here is the first error: 
```
Traceback (most recent call last):
  File "/gss/work/nand5072/SOFTWARE/anvio/bin/anvi-help", line 35, in <module>
    TABLE_BG = back.GREY_11
AttributeError: 'function' object has no attribute 'GREY_11'
```

This is an error I can fix. The package colored has changed a little bit and all 'back', 'fore' and 'style' need to be replaced with a capital letter: 'Back', 'Fore', 'Style'. 

But even when I fix this issue, I have a new error and I don't know what's happening:
```
Traceback (most recent call last):
  File "/Users/fltrig002/github/anvio/bin/anvi-help", line 5, in <module>
    from anvio.argparse import ArgumentParser
  File "/Users/fltrig002/github/anvio/anvio/argparse.py", line 7, in <module>
    import argparse
  File "/Users/fltrig002/github/anvio/anvio/argparse.py", line 11, in <module>
    from rich_argparse import RichHelpFormatter
  File "/Users/fltrig002/miniconda3/envs/anvio-dev/lib/python3.10/site-packages/rich_argparse/__init__.py", line 25, in <module>
    class RichHelpFormatter(argparse.HelpFormatter):
AttributeError: partially initialized module 'argparse' has no attribute 'HelpFormatter' (most likely due to a circular import)
```

**Comment by FlorianTrigodet** [comment]
I made a mistake with the above error. Forget about the second issue: it is because I ran the anvi'o command from the anvio directory 🤦 

fixed with #2147
