### ISSUE TITLE
Problems about Structure Display with anvi-display-structure

### ISSUE THREAD

**Issue by YongyiPeng** [merenlab/anvio#2166]
Hi, thanks for developing this powerful tool! I appreciate for its exceptional performance, but I encountered a specific issue while attempting to display structure (anvio's interactive stuck at still loading).

**Anvio's version**
Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.13

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2

**System info**
masOS high sierra 10.13.2

**Detailed description**
`anvi-display-structure -c CONTIGS.db -p PROFILE.db -s STRUCTURE_889488.db --gene-caller-ids 889488`

The output is:
* The server is up and running 🎉

WARNING
===============================================
If you are using OSX and if the server terminates prematurely before you can see
anything in your browser, try running the same command by putting 'sudo ' at the
beginning of it (you will be prompted to enter your password if sudo requires
super user credentials on your system). If your browser does not show up, try
manually entering the URL shown below into the address bar of your favorite
browser. *cough* CHROME *cough*.

Server address ...............................: http://0.0.0.0:8080

* When you are ready, press CTRL+C once to terminate the server and go back to the
  command line.

The website loads into the Chrome browser, but it remains stuck in a continuous loading state.

**Messages in the console of Chrome Developer tools**
`Failed to load resource: net::ERR_CONNECTION_RESET bootstrap-slider.css:1
Failed to load resource: net::ERR_CONNECTION_RESET bootstrap-slider.min.js:1     
Failed to load resource: net::ERR_CONNECTION_RESET d3.min.js:1     
Failed to load resource: net::ERR_CONNECTION_RESET jszip.min.js:1     
Failed to load resource: net::ERR_CONNECTION_RESET FileSaver.js:1     
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT ngl.js:1     
Uncaught TypeError:  structure.js?rand=edf3395fa85040d922fbaf29cb276773:1134 
$(...).slider is not a function
    at structure.js?rand=edf3395fa85040d922fbaf29cb276773:1134:43
    at Array.forEach (<anonymous>)
    at Object.success (structure.js?rand=edf3395fa85040d922fbaf29cb276773:1105:25)
    at j (jquery.js:3148:30)
    at Object.fireWith [as resolveWith] (jquery.js:3260:7)
    at x (jquery.js:9314:14)
    at XMLHttpRequest.b (jquery.js:9718:8)
Uncaught (in promise) ReferenceError: NGL is not defined  structure.js?rand=edf3395fa85040d922fbaf29cb276773:255 
    at create_single_ngl_view (structure.js?rand=edf3395fa85040d922fbaf29cb276773:255:17)
    at create_ngl_views (structure.js?rand=edf3395fa85040d922fbaf29cb276773:225:15)
    at load_sample_group_widget (structure.js?rand=edf3395fa85040d922fbaf29cb276773:191:9)
    at HTMLSelectElement.<anonymous> (structure.js?rand=edf3395fa85040d922fbaf29cb276773:95:9)
    at HTMLSelectElement.dispatch (jquery.js:4670:9)
    at r.handle (jquery.js:4338:28)
    at Object.trigger (jquery.js:4579:12)
    at HTMLSelectElement.<anonymous> (jquery.js:5289:17)
    at Function.each (jquery.js:384:23)
    at m.fn.init.each (jquery.js:136:17)`

I have used different ip address and port numbers, but it didn't help. 
I would be grateful if you could provide any suggestion.

**Comment by meren** [comment]
Hi @YongyiPeng,

Can you please send the output for these two commands after running them in your anvi'o environment?

```
ls `python -c 'import anvio; import os; print(os.path.dirname(anvio.__file__))'`/data/interactive/lib/
```

```
ls `python -c 'import anvio; import os; print(os.path.dirname(anvio.__file__))'`/data/interactive/lib/bootstrap
```

**Comment by YongyiPeng** [comment]
Thanks for your quick reply!

I get these after running the first command:

JavaScript-MD5		bootstrap-sortable	d3.js			jquery-ui		svg-crowbar
bootstrap		bootstrap-waitingfor	jquery			marked			toastr
bootstrap-markdown	colpick			jquery-svgpan		randomColor		treelib-js

After running the second command:
CNAME		LICENSE		bower.json	docs		js		package.json
CONTRIBUTING.md	README.md	composer.json	fonts		less		test-infra
Gruntfile.js	_config.yml	dist		grunt		package.js

**Comment by YongyiPeng** [comment]
The output is:
00.sh
__init__.py
__pycache__
misc
run_component_tests_for_SCVs_SAAVs_structure.sh
run_component_tests_for_SNVs.sh
run_component_tests_for_alons_classifier.sh
run_component_tests_for_cazymes.sh
run_component_tests_for_display_functions.sh
run_component_tests_for_export_locus.sh
run_component_tests_for_gene_level_stats.sh
run_component_tests_for_indels.sh
run_component_tests_for_inversions.sh
run_component_tests_for_manual_interactive.sh
run_component_tests_for_metabolism.sh
run_component_tests_for_metagenomics.sh
run_component_tests_for_minimal_metagenomics.sh
run_component_tests_for_pangenomics.sh
run_component_tests_for_trnaseq.sh
run_migration_tests_for_ancient_anvio_databases.sh
run_unit_tests_for_consensus_taxonomy.py
run_workflow_tests_for_all_workflows.sh
run_workflow_tests_for_contigs.sh
run_workflow_tests_for_ecophylo.sh
run_workflow_tests_for_metagenomics.sh
run_workflow_tests_for_metapangenomics.sh
run_workflow_tests_for_pangenomics.sh
run_workflow_tests_for_phylogenomics.sh
run_workflow_tests_for_sra_download.sh
sandbox
unit

**Comment by meren** [comment]
Good. Can you please run these two commands:

``` bash
# change directory
cd `python -c 'import anvio; import os; print(os.path.dirname(anvio.__file__))'`/tests

# run test
./run_component_tests_for_SCVs_SAAVs_structure.sh new
```

At the end of this test, I get the following display on my browser, please let me know if you're getting the same exact error:

![image](https://github.com/merenlab/anvio/assets/197307/16393043-1c0d-4863-8481-0c81a8ba429b)

**Comment by YongyiPeng** [comment]
I get this error:

:: anvi-gen-structure-database with DSSP ...


Traceback for debugging
================================================================================
  File "/opt/anaconda3/envs/anvio-8/bin/anvi-gen-structure-database", line 151, in <module>
    main(args)
  File "/opt/anaconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/terminal.py", line 915, in wrapper
    program_method(*args, **kwargs)
  File "/opt/anaconda3/envs/anvio-8/bin/anvi-gen-structure-database", line 34, in main
    structops.StructureSuperclass(args, create=True)._run()
  File "/opt/anaconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/structureops.py", line 399, in __init__
    self.dssp = DSSPClass(skip_sanity_check=self.skip_DSSP) # If we skip DSSP, skip sanity_check
  File "/opt/anaconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/structureops.py", line 1084, in __init__
    self.set_executable()
  File "/opt/anaconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/structureops.py", line 1155, in set_executable
    raise ConfigError("'mkdssp' or 'dssp' must be installed on your system, but "
================================================================================


Config Error: 'mkdssp' or 'dssp' must be installed on your system, but neither seem to appear
              in your path :/ If you are certain you have either on your system (for instance
              you can run either by typing 'mkdssp' or 'dssp' in your terminal window), you
              may want to send a detailed bug report. If you want to install DSSP, check out
              http://merenlab.org/2016/06/18/installing-third-party-software/#dssp. If you
              want to skip secondary structure and solvent accessibility annotation, provide
              the flag --skip-DSSP.

**Comment by meren** [comment]
Good. Please address this problem by following the instructions on the message until you don't see it anymore when you run `./run_component_tests_for_SCVs_SAAVs_structure.sh new` in this directory.
