### ISSUE TITLE
[BUG] anvi-setup-kegg-data encountered an error

### ISSUE THREAD

**Issue by Zerong0513** [merenlab/anvio#2372]
## Short description of the problem

anvi-setup-kegg-data encountered an error when running anvi-setup-kegg-data --download-from-kegg -D -T 4 --reset

## anvi'o version

Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.15
Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2

## System info

Windows 11.  Anvio installed followed the instructions by conda.

## Detailed description of the issue

Traceback (most recent call last):
  File "/home/zerong/miniconda3/envs/anvio-8/bin/anvi-setup-kegg-data", line 179, in <module>
    main(args, unknown_args)
  File "/home/zerong/miniconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/terminal.py", line 915, in wrapper
    program_method(*args, **kwargs)
  File "/home/zerong/miniconda3/envs/anvio-8/bin/anvi-setup-kegg-data", line 126, in main
    KODatabase.set_up(num_threads = args.num_threads, dir = setup_directory, reset = args.reset)
  File "/home/zerong/miniconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/biochemistry/reactionnetwork.py", line 1262, in set_up
    if line[0] == ' ':
IndexError: string index out of range

**Comment by semiller10** [comment]
Hi @Zerong0513, sorry for the delayed response. Here is my recommendation of what to do.

First, I notice that you have two redundant flags in your command, `--download-from-kegg` and `-D`. `-D` is just the abbreviated version of `--download-from-kegg`.

If you wish to use the most advanced anvi'o capabilities for manipulating KEGG data, I suggest using the development version, which you can find installation instruction for [here](https://anvio.org/install/). I expect that downloading the current version of the KEGG database with your command will work fine in `dev` since we have recently tested that. New additions for manipulating KEGG data include [`anvi-draw-kegg-pathways`](https://anvio.org/help/main/programs/anvi-draw-kegg-pathways/) and a better version of the [reaction network](https://anvio.org/help/main/artifacts/reaction-network/). A drawback to switching from `v8` to `dev` is that you will have to remake your databases.

If you wish to continue using `v8`, I recommend using the following command to download the most recent KEGG data without the files needed for the reaction network: `anvi-setup-kegg-data  -D -T 4 --reset --mode KOfam modules`. This will still download the files needed for KOfam annotation of contigs databases, calculating module completeness, and a few other functions.

Let me know how that works.
Best of luck,
Sam
