### ISSUE TITLE
Can't upgrade PROFILE.db from v19 to v20

### ISSUE THREAD

**Issue by brymerr921** [merenlab/anvio#471]
I tried to upgrade my PROFILE.db from v17 to v20 using the scripts to go from v17 to v18, v18 to v19, and finally v19 to v20. The v19 to v20 upgrade script didn't work. Here is the error message.

```
Traceback (most recent call last):
  File "/home/sonnenburglab/virtual-envs/anvio-2.2.2/bin/anvi-script-upgrade-profile-db-v19-to-v20", line 80, in <module>
    update_profile_db(args.profile_db, just_do_it = args.just_do_it)
  File "/home/sonnenburglab/virtual-envs/anvio-2.2.2/bin/anvi-script-upgrade-profile-db-v19-to-v20", line 51, in update_profile_db
    profile_db._exec('COMMIT')
  File "/home/sonnenburglab/virtual-envs/anvio-2.2.2/lib/python3.5/site-packages/anvio/db.py", line 133, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: cannot commit - no transaction is active
```

Another time it said:
```
Traceback (most recent call last):
  File "/home/sonnenburglab/virtual-envs/anvio-2.2.2/bin/anvi-script-upgrade-profile-db-v19-to-v20", line 80, in <module>
    update_profile_db(args.profile_db, just_do_it = args.just_do_it)
  File "/home/sonnenburglab/virtual-envs/anvio-2.2.2/bin/anvi-script-upgrade-profile-db-v19-to-v20", line 48, in update_profile_db
    profile_db._exec('DROP TABLE gene_coverages;')
  File "/home/sonnenburglab/virtual-envs/anvio-2.2.2/lib/python3.5/site-packages/anvio/db.py", line 133, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: no such table: gene_coverages
```

Thanks!

**Comment by meren** [comment]
Hi!

This is not good :) I will send you a script very soon that will fix this. In the meantime can you please give us some details about your operating system, sqlite version, etc?


Best,

**Comment by meren** [comment]
Sorry about this unexpected problem.

## Solution

**Download the updated script** (which is [here](https://raw.githubusercontent.com/merenlab/anvio/6c4ee59f01fc84714cffdfa39ccb6c7273d2082f/sandbox/anvi-script-upgrade-profile-db-v19-to-v20) if you want to download it manually):

``` bash
wget https://goo.gl/AtbmWn -O anvi-script-upgrade-profile-db-v19-to-v20-fixy
```

Make it executable:

``` bash
chmod +x anvi-script-upgrade-profile-db-v19-to-v20-fixy
```

Overwrite the existing script:

``` bash
target_dir=$(dirname `which anvi-script-upgrade-profile-db-v19-to-v20`)
sudo mv anvi-script-upgrade-profile-db-v19-to-v20-fixy $target_dir/anvi-script-upgrade-profile-db-v19-to-v20
```

Re-run your upgrade:

``` bash
anvi-script-upgrade-profile-db-v19-to-v20 YOUR_PROFILE_DB --just-do-it
```

This should resolve it.

Sorry about the hiccup!

**Comment by meren** [comment]
We would be very happy if you can let us know whether it works!

**Comment by jvineis** [comment]
This works!

**Comment by meren** [comment]
Thank you, Joe.
