### ISSUE TITLE
Issue with anvi-gen-genomes-storage & anvi-pan-genome (anvi'o v2.1.0/2.2.2)

### ISSUE THREAD

**Issue by rprops** [merenlab/anvio#493]
Hi,

I have been trying to setup a pangenomic analysis (with internal genomes) but seem to have hit a bump in both v2.1.0 and v2.2.2.

Per instruction I created the internal list file (`internal_genome_list`):
```
name    bin_id  collection_id   profile_db_path contigs_db_path
Bin1      bin1   final_bins      SAMPLES-MERGED/PROFILE.db       contigs.db
Bin2      bin2   final_bins      SAMPLES-MERGED/PROFILE.db       contigs.db
...
```

The `anvi-gen-genomes-storage` command I was able to run on v2.1.0 to get the `.h5` file but it crashed on v2.2.2.:
```
[rprops@nyx7011 anvio_v2.2.2]$ anvi-gen-genomes-storage -o PAN-GENOMES.h5 -i internal_genome_list

Traceback (most recent call last):
  File "/sw/lsa/centos7/anvio/2.2.2/bin/anvi-gen-genomes-storage", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==2.2.2', 'anvi-gen-genomes-storage')
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/anvi-gen-genomes-storage", line 56, in <module>
    pan.create_genomes_data_storage()
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/panops.py", line 267, in create_genomes_data_storage
    self.load_genomes_descriptions()
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/panops.py", line 109, in load_genomes_descriptions
    self.genomes[genome_name]['genome_hash'] = self.get_genome_hash_for_internal_genome(self.genomes[genome_name])
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/panops.py", line 424, in get_genome_hash_for_internal_genome
    genome_hash = hashlib.sha224('_'.join([''.join(split_names_of_interest), contigs_db.meta['contigs_db_hash']])).hexdigest()[0:12]
TypeError: Unicode-objects must be encoded before hashing
```

For both v2.1.0 and v2.2.2. I got the exact same error message when running `anvi-pan-genome`:

```
[rprops@nyx7011 anvio_v2.2.2]$ anvi-pan-genome -g PAN-GENOMES.h5 -J TEST_PANGENOME --num-threads 20

WARNING
===============================================
If you publish results from this workflow, please do not forget to cite DIAMOND
(doi:10.1038/nmeth.3176), unless you use it with --use-ncbi-blast flag, and MCL
(http://micans.org/mcl/ and doi:10.1007/978-1-61779-361-5_15)

Genomes storage ..............................: Initialized (storage hash: d4e58c90)
Num genomes in storage .......................: 6
Num genomes will be used .....................: 6
Pan database .................................: A new database, /scratch/vdenef_fluxm/rprops/metaG_SCK/data/coassembly/anvio_v2.2.2/TEST_PANGENOME/TEST_PANGENOME-PAN.db, has been created.
Exclude partial gene calls ...................: False

[06 Apr 17 17:05:54 Uniquing the output FASTA file] ...                                                                                                                                                                                     Traceback (most recent call last):
  File "/sw/lsa/centos7/anvio/2.2.2/bin/anvi-pan-genome", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==2.2.2', 'anvi-pan-genome')
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/anvi-pan-genome", line 100, in <module>
    pan.process()
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/panops.py", line 1084, in process
    unique_proteins_FASTA_path, unique_proteins_names_dict = self.genomes_storage.gen_combined_protein_sequences_FASTA(combined_proteins_FASTA_path, exclude_partial_gene_calls=self.exclude_partial_gene_calls)
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/auxiliarydataops.py", line 364, in gen_combined_protein_sequences_FASTA
    unique_proteins_FASTA_path, unique_proteins_names_file_path, unique_proteins_names_dict = utils.unique_FASTA_file(output_file_path, store_frequencies_in_deflines=False)
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/utils.py", line 1009, in unique_FASTA_file
    input_fasta = u.SequenceSource(input_file_path, unique=True)
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/fastalib.py", line 101, in __init__
    raise FastaLibError("File '%s' does not seem to be a FASTA file." % self.fasta_file_path)
anvio.fastalib.FastaLibError: Fasta Lib Error: File '/scratch/vdenef_fluxm/rprops/metaG_SCK/data/coassembly/anvio_v2.2.2/TEST_PANGENOME/combined-proteins.fa' does not seem to be a FASTA file.
```

Any insight would be appreciated.

Ruben

**Comment by meren** [comment]
If any of the contigs databases addressed from your internal genomes file is generated with anvi'o 2.1.0 and older, you will get a `TypeError` in `v2.2.2` :/  Which sucks a lot.

I fixed it in the `master` repo (see #473), but we haven't made any official release yet.

There are multiple options: One is to start using the `master`, the other is to wait a little, the third is to re-generate the contigs database (but then you will have update the hash of the profile dbs that relies on that contig, so you will do more and more hacky stuff).

I would start using the master. Here: http://merenlab.org/2016/06/26/installation-v2/#installation-for-developers-youre-a-wizard-arry

**Comment by rprops** [comment]
I did remake the contig database with `v2.2.2` but still got the same error :(. I'll try to get our sysadmin to install the master branch.

**Comment by meren** [comment]
You don't ned our sysadmin, you can install it yourself following the link I sent.

**Comment by rprops** [comment]
After updating to the master branch `anvi-gen-genomes-storage` ran fine (as it did in v2.1.0) but the `anvi-pan-genome` function popped the same error as before. I will wait for the next release. Thanks for the feedback.
```
raceback (most recent call last):
  File "/sw/lsa/centos7/anvio/2.2.2/bin/anvi-pan-genome", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==2.2.2', 'anvi-pan-genome')
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/anvi-pan-genome", line 100, in <module>
    pan.process()
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/panops.py", line 1084, in process
    unique_proteins_FASTA_path, unique_proteins_names_dict = self.genomes_storage.gen_combined_protein_sequences_FASTA(combined_proteins_FASTA_path, exclude_partial_gene_calls=self.exclude_partial_gene_calls)
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/auxiliarydataops.py", line 364, in gen_combined_protein_sequences_FASTA
    unique_proteins_FASTA_path, unique_proteins_names_file_path, unique_proteins_names_dict = utils.unique_FASTA_file(output_file_path, store_frequencies_in_deflines=False)
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/utils.py", line 1009, in unique_FASTA_file
    input_fasta = u.SequenceSource(input_file_path, unique=True)
  File "/sw/lsa/centos7/anvio/2.2.2/lib/python3.6/site-packages/anvio-2.2.2-py3.6-linux-x86_64.egg/anvio/fastalib.py", line 101, in __init__
    raise FastaLibError("File '%s' does not seem to be a FASTA file." % self.fasta_file_path)
anvio.fastalib.FastaLibError: Fasta Lib Error: File '/scratch/vdenef_fluxm/rprops/metaG_SCK/data/coassembly/anvio_v2.2.2/TEST_PANGENOME/combined-proteins.fa' does not seem to be a FASTA file.
```

The `combined-proteins.fa` file does seem to be a FASTA file:
```
[rprops@flux-login2 anvio_v2.2.2]$ head combined-proteins.fa
>e28228b467d3_1816
MEVVAKLPVADQREGELRQLLKALGAFRRGETGLTLPTEWDGLYGKIAAEFNELSAQAARHSNRLHGLDPAQRSAGRANRRLPDEKLTGFWQQDVAAINNVLDHCELLSEHTRTFLGALTDLKKGSAAAQLPRDWTGVFGKVADAFNDVVAENLHMAQELARLSRVVGKEGKLKERAQVPSASGFWRESADSINSLISDLVHPTSEVARVIGAVAQGDLSKSMALEADGRPLEGEFLRTAMIINKMVQQLGTFAAEVTRVAREVGTEGKLGGQADVQGVAGTWKDLTDSVNFMASNLTAQVRNIADVTKAVAAGDLSKKITVEVKGEILELKNTINTMVDQLSSFASEVTRVAREVGTEGKLGGQADVQGVAGTWKDLTDNVNFMAGNLTSQVRNIADVTTAVAAGDLSKKITVNVKGEILELKNTINTM
>e28228b467d3_1817
MQMKYKLTVLAAVAAISGVALAQDVQVVKIGHVAPMSGPQAHYGKDNENGVRMAIEDLNAQGVVIAGKKVKLEIQAEDDAADPKQGTAAAQKLCDAKVAGVVGHLNSGTTIPASKVYNDCGIPHITGAATNPALTKPGYDTTYRIIANDNALGAQLALYAADTLKLKSVAIIDDRTAYGQGVAEIFKKTAESKGVKVVDSQYTNDKATDFMAILTSIKAKKPDAIFYGGMDTQAGPMLRQMEQLGMSDVKFFGGDGICTTEIAKLAAGAKTLGGVVCAEGGLSIDKMPGGKAWKARYDAKFPGQFQIYSPYTYDATFVLVDAMKRAGSTDPKKYIPELKKTNFKGITATIQFEPNGELKNAAATLSTYKDGKKVTLN
```

**Comment by meren** [comment]
Can you please send me the entire `combined-proteins.fa` file gzip'd?

Thank you,

**Comment by rprops** [comment]
[combined-proteins.fa.gz](https://github.com/merenlab/anvio/files/905876/combined-proteins.fa.gz)

**Comment by meren** [comment]
Hi Ruben,

I have not been able to reproduce this error :/ The FASTA file for combined proteins seems OK, and the library parses it properly.

The `Fasta Lib Error` you are getting is thrown only when the first character of the FASTA file is not a `>` character. Which clearly is the case with your file, so I am a bit confused here :/

**Comment by rprops** [comment]
Hi Eren,

Bizar. Anvi'o is installed as a central module on our university HPC cluster. I'll try and troubleshoot together with our sysadmin and get back to you when/if we figure it out! Thanks already for the aid!
