### ISSUE TITLE
CPR-Classifier

### ISSUE THREAD

**Issue by adityabandla** [merenlab/anvio#514]
Hi 

When I try to run the CPR classifier, with Brown et al. SCG collection, as mentioned in the tutorial, I end up with the following error

Traceback (most recent call last):
File "/.local/bin/anvi-script-gen-CPR-classifier", line 79, in <module>
main(args)
File "/.local/bin/anvi-script-gen-CPR-classifier", line 57, in main
for j in random.sample(list(range(0, dim)), random.randint(0, dim / 2)):
File "/miniconda3/lib/python3.6/random.py", line 220, in randint
return self.randrange(a, b+1)
File "/miniconda3/lib/python3.6/random.py", line 193, in randrange
raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()

Not sure what could be wrong

**Comment by adityabandla** [comment]
Hi,

An update, I just saw Ozcan's commit on the master repo (17 days ago), correcting for this error

So I simply copied this updated script to my ~/.local/bin folder replacing the older script. 
The command works, but throws up another error

Traceback (most recent call last):                                                                                                  
  File "/.local/bin/anvi-script-gen-CPR-classifier", line 79, in <module>
    main(args)
  File "/.local/bin/anvi-script-gen-CPR-classifier", line 63, in main
    rf.train(features, data, labels)
  File "/.local/lib/python3.6/site-packages/anvio-2.3.1-py3.6-linux-x86_64.egg/anvio/learning.py", line 52, in train
    pickle.dump({'features': features, 'classes': rf.classes_, 'classifier': rf}, open(self.classifier_object_path, 'w'))
TypeError: write() argument must be str, not bytes

**Comment by adityabandla** [comment]
I updated anvio from the master repo and it worked!
