### ISSUE TITLE
File Path Error

### ISSUE THREAD

**Issue by adityabandla** [merenlab/anvio#515]
Hi
While running the cpr-classifier script, I run into the error, which says

File/Path Error: No input file is declared...

Though the error seems quite obvious, I can't find a mistake in the path to the files. For context, previous steps worked with these files

**Comment by adityabandla** [comment]
Seems to work when an output directory is mentioned through the -o option. However, the help for this script nor the error message displayed point to this

**Comment by adityabandla** [comment]
But I ran into the following error

Traceback (most recent call last):
  File "/data/phdproject/aditya/.local/bin/anvi-script-predict-CPR-genomes", line 148, in <module>
    main(args)
  File "/.local/bin/anvi-script-predict-CPR-genomes", line 81, in main
    rf.initialize_classifier()
  File "/.local/lib/python3.6/site-packages/anvio/learning.py", line 93, in initialize_classifier
    classifier_obj = pickle.load(open(self.classifier_object_path))
  File "/miniconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
