### ISSUE TITLE
conda installation of anvio error with Anaconda3-4.4.0-Linux-x86_64.sh?

### ISSUE THREAD

**Issue by liuxianghui** [merenlab/anvio#557]
I tried to install anvio on a Linux centos system. 
I downloaded the latest version of anaconda  Anaconda3-4.4.0-Linux-x86_64.sh
and then ran 
conda create -n anvio232 -c bioconda -c conda-forge gsl anvio
Everything seems to be fine but when I tried to run the mini test. It showed me the error of python version error.
I verified the python version. It is python 3.6.1
However, I found in the conda create command. It tried to install  python 3.5.3. Is this the problem?
Why does conda not try to install the latest python 3.6.1 at conda create? 
Please kindly suggest

   pyopenssl:        16.2.0-py35_0                      conda-forge
    pyqt:             4.11.4-py35_2                      conda-forge
    pysam:            0.11.1-py35_0                      bioconda
    pysocks:          1.6.7-py35_0                       conda-forge
    python:           3.5.3-3                            conda-forge
    pytz:             2017.2-py35_0                      conda-forge
    qt:               4.8.7-7                            conda-forge

(anvio232) [xianghui@login-c01 ~]$ python --version
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
(anvio232) [xianghui@login-c01 ~]$ which python
alias python='/home/xianghui/anaconda3/bin/python'
	~/anaconda3/bin/python

[xianghui@login-c01 ~]$ source activate anvio232
(anvio232) [xianghui@login-c01 ~]$ anvi-self-test --suite mini
/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'h5py._errors' does not match runtime version 3.5
  return f(*args, **kwds)
/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'h5py._conv' does not match runtime version 3.5
  return f(*args, **kwds)
/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'h5py.h5r' does not match runtime version 3.5
  return f(*args, **kwds)
/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'h5py._objects' does not match runtime version 3.5
  return f(*args, **kwds)
/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'h5py.defs' does not match runtime version 3.5
  return f(*args, **kwds)
/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'h5py.h5t' does not match runtime version 3.5
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xianghui/anaconda3/envs/anvio232/bin/anvi-self-test", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==2.3.2', 'anvi-self-test')
  File "/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/gpfs0/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/site-packages/anvio-2.3.2-py3.5-linux-x86_64.egg-info/scripts/anvi-self-test", line 13, in <module>
    import anvio.filesnpaths as filesnpaths
  File "/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/site-packages/anvio/filesnpaths.py", line 6, in <module>
    import h5py
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/h5py/_conv.py", line 7, in <module>
    __bootstrap__()
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/h5py/_conv.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "h5py/h5t.pxd", line 14, in init h5py._conv (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/_conv.c:7532)
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/h5py/h5t.py", line 7, in <module>
    __bootstrap__()
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/h5py/h5t.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "/home/xianghui/anaconda3/envs/anvio232/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "h5py/numpy.pxd", line 66, in init h5py.h5t (/home/ilan/minonda/conda-bld/h5py_1490028290543/work/h5py/h5t.c:22517)
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/numpy/__init__.py", line 146, in <module>
    from . import add_newdocs
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/xianghui/anaconda3/lib/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

**Comment by xvazquezc** [comment]
For what I can see you have Python 3.6 installed in the conda root environment and 3.5 in the anvio environment. And that's interfering because for your system you set an alias to the conda root version of Python, so whenever you type `python` or a program calls it, it means `~/anaconda3/bin/python`.
Remove the alias, that should do.

**Comment by liuxianghui** [comment]
Thank you. That solve the problem.
