### ISSUE TITLE
ribosomal_RNAs issue during the generation of genomes storage

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#562]
This is a traceback from a user we need to find a way to recapitulate and fix:

``` bash

anvi-gen-genomes-storage -o ${outdirgenstorage} -i ${internalgenomes} 2>&1 | tee -a ${outdirpangenome}/log.01.genomestorage.txt

WARNING
===============================================
Good news! Anvi'o found all these functions that are common to all of your
genomes and will use them for downstream analyses and is very proud of you:
'Pfam, TIGRFAM, ProSiteProfiles, PANTHER, SFLD, CDD, ProSitePatterns, Hamap'.

Internal genomes .............................: 15 have been initialized.                                                                                                                                   
External genomes .............................: 0 found.                                                                                                                                                    
Traceback (most recent call last):
  File "anvio/virtual-envs/anvio-dev/bin/anvi-gen-genomes-storage", line 4, in <module>
    __import__('pkg_resources').run_script('anvio===2.3.2-master', 'anvi-gen-genomes-storage')
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-2.3.2_master-py3.6-macosx-10.12-x86_64.egg/EGG-INFO/scripts/anvi-gen-genomes-storage", line 49, in <module>
    pan.create_genomes_data_storage()
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-2.3.2_master-py3.6-macosx-10.12-x86_64.egg/anvio/genomestorage.py", line 126, in create_genomes_data_storage
    self.load_genomes_descriptions()
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-2.3.2_master-py3.6-macosx-10.12-x86_64.egg/anvio/genomedescriptions.py", line 166, in load_genomes_descriptions
    self.sanity_check()
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-2.3.2_master-py3.6-macosx-10.12-x86_64.egg/anvio/genomedescriptions.py", line 343, in sanity_check
    self.list_HMM_info_and_quit()
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-2.3.2_master-py3.6-macosx-10.12-x86_64.egg/anvio/genomedescriptions.py", line 84, in list_HMM_info_and_quit
    hmm_sources_in_all_genomes = self.get_HMM_sources_common_to_all_genomes()
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-2.3.2_master-py3.6-macosx-10.12-x86_64.egg/anvio/genomedescriptions.py", line 110, in get_HMM_sources_common_to_all_genomes
    [hmm_sources_in_all_genomes.remove(s) for s in hmm_sources_found if s not in self.genomes[genome_name]['hmm_sources_info']]
  File "anvio/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-2.3.2_master-py3.6-macosx-10.12-x86_64.egg/anvio/genomedescriptions.py", line 110, in <listcomp>
    [hmm_sources_in_all_genomes.remove(s) for s in hmm_sources_found if s not in self.genomes[genome_name]['hmm_sources_info']]
KeyError: 'Ribosomal_RNAs'
```

**Comment by meren** [comment]
This is addressed by this merge: https://github.com/merenlab/anvio/pull/564
