### ISSUE TITLE
--external-gene-calls is broken in v2.4.0.

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#566]
``` bash
anvio/tests/sandbox/test-output $ anvi-gen-contigs-database -f ../contigs.fa \
                                                            --external-gene-calls ../example_external_gene_calls.txt
Traceback (most recent call last):
  File "/Users/meren/github/anvio/bin/anvi-gen-contigs-database", line 44, in <module>
    a.create(args)
  File "/Users/meren/github/anvio/anvio/dbops.py", line 1968, in create
    gene_calls_tables.use_external_gene_calls_to_populate_genes_in_contigs_table(external_gene_calls, ignore_internal_stop_codons)
  File "/Users/meren/github/anvio/anvio/dbops.py", line 2676, in use_external_gene_calls_to_populate_genes_in_contigs_table
    if gene_calls_dict is not None and not len(gene_calls_dict):
TypeError: object of type 'bool' has no len()
```

**Comment by mlcoleman** [comment]
I am getting this (related?) error when I add the --ignore-internal-stop-codons flag:
```
Config Error: 'Use external gene calls' function received a non-empty gene_calls_dict object,
              but it is of type '<class 'bool'>', and not '<class 'dict'>'
```

**Comment by meren** [comment]
Sorry about that, Maureen. Can you please try again?


Thanks!

**Comment by mlcoleman** [comment]
works now! Thanks!

On Jul 31, 2017, at 8:11 AM, A. Murat Eren <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry about that, Maureen. Can you please try again?

Thanks!
