### ISSUE TITLE
"RecA" option in anvi-interactive leads to python traceback

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#595]
![image](https://user-images.githubusercontent.com/8688665/30821495-389f562e-a1eb-11e7-9b97-aae1bd7dcf4b.png)

Right clicking a bin and selecting any of "RecA", "Ribosomal S3", or "Ribosomal L10" leads to the following Traceback:

```
Traceback (most recent call last):
  File "/Users/evan/virtual-envs/anvio-master/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/evan/virtual-envs/anvio-master/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/Users/evan/Software/anvio/anvio/bottleroutes.py", line 610, in get_hmm_hit_from_bin
    hmm_sequences_dict = self.interactive.hmm_access.get_sequences_dict_for_hmm_hits_in_splits({bin_name: set(self.interactive.collection[bin_name])})
AttributeError: 'Interactive' object has no attribute 'hmm_access'
```

**Comment by ozcan** [comment]
This commit solves the issue but let's keep this open since we are planning to extend this feature and add a small window to select gene.

**Comment by meren** [comment]
This is now fixed, and I will start another issue for Ozcan's suggestion.
