### ISSUE TITLE
anvi-display-pan error: AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#597]
When using this command: `anvi-display-pan -p AB16-PAN.db -s AB16-SAMPLES.db -g baumannii-16-GENOMES.h5` I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/anvi-display-pan", line 75, in <module>
    d = interactive.Interactive(args)
  File "/usr/local/Cellar/anvio/2.4.0/libexec/lib/python3.6/site-packages/anvio/interactive.py", line 143, in __init__
    self.load_pan_mode()
  File "/usr/local/Cellar/anvio/2.4.0/libexec/lib/python3.6/site-packages/anvio/interactive.py", line 619, in load_pan_mode
    PanSuperclass.__init__(self, self.args)
  File "/usr/local/Cellar/anvio/2.4.0/libexec/lib/python3.6/site-packages/anvio/dbops.py", line 797, in __init__
    progress=self.progress)
  File "/usr/local/Cellar/anvio/2.4.0/libexec/lib/python3.6/site-packages/anvio/auxiliarydataops.py", line 232, in __init__
    HDF5_IO.__init__(self, file_path, db_hash, create_new = create_new, ignore_hash = ignore_hash)
  File "/usr/local/Cellar/anvio/2.4.0/libexec/lib/python3.6/site-packages/anvio/auxiliarydataops.py", line 67, in __init__
    We heard that they love them some e-mails." % (self.db_type, self.file_path, self.fp.attrs['version'].decode('utf-8'), self.version))
AttributeError: 'str' object has no attribute 'decode'
```

On Barhal, my working directory is `/groups/merenlab/people/awatson/A_baumannii/AB16`, but the `.h5` file is one directory up. Here is my anvio version

```
Anvi'o version ...............................: 2.4.0
Profile DB version ...........................: 20
Contigs DB version ...........................: 8
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 3
Anvi'server users data storage version .......: 1
```

**Comment by ozcan** [comment]
Hey Andrea,
This problem occurs because project created using master version on MBL but on your local you have 2.4.0 which is older comparing to master. So I would recommend you to install master on your computer too. I have tested it with master and worked perfectly.

**Comment by watsonar** [comment]
That makes sense, thank you! :)
