### ISSUE TITLE
Error in mcg-classifier.snakefile

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#606]
Repeatedly getting this error:
```
Finished job 4.
16 of 36 steps (44%) done

rule run_mcg_classifier_collection:
    input: test-output/TEST/MERGED-SAMPLES/PROFILE.db, test-output/TEST.db, test-output/import_collection.done
    output: test-output/TEST-collection-TS-plots/{*}-coverages.pdf (dynamic)
    log: test-output/TEST-run_mcg_classifier_collection.log
    jobid: 3

Subsequent jobs will be added dynamically depending on the output of this rule
Dynamically updating jobs
Finished job 3.
17 of 36 steps (47%) done

rule import_collection:
    input: test-output/TEST/MERGED-SAMPLES/PROFILE.db, test-output/TEST.db
    output: test-output/import_collection.done
    log: test-output/TEST-import_collection.log
    jobid: 7

Touching output file test-output/import_collection.done.
Finished job 7.
18 of 36 steps (50%) done
Traceback (most recent call last):
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/snakemake/__init__.py", line 481, in snakemake
    create_envs_only=create_envs_only)
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/snakemake/workflow.py", line 535, in execute
    success = scheduler.schedule()
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/snakemake/scheduler.py", line 236, in schedule
    run = self.job_selector(needrun)
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/snakemake/scheduler.py", line 346, in job_selector
    c = list(map(self.job_reward, jobs))  # job rewards
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/snakemake/scheduler.py", line 401, in job_reward
    return (self.dag.priority(job), self.dag.temp_input_count(job), self.dag.downstream_size(job),
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/snakemake/dag.py", line 247, in priority
    return self._priority[job]
KeyError: run_mcg_classifier_collection
```

Once I restart the snakefile (without making any changes), then it runs with no errors. This could be a snakemake problem, but I will look into this, and if so, then I'll try to reproduce this with a simple mock workflow and create an issue for snakemake.

**Comment by ShaiberAlon** [comment]
There is no need for this snakefile anymore.
