### ISSUE TITLE
error in anvi-export-functions

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#607]
when running:
`$ anvi-export-functions -c p214_sequence-FASTA-medusa-fixed.db -l`

I get:
```
[11 Oct 17 07:06:04 Initializing] ...                                                            Traceback (most recent call last):
  File "/Users/alonshaiber/github/anvio/bin/anvi-export-functions", line 104, in <module>
    main(args)
  File "/Users/alonshaiber/github/anvio/bin/anvi-export-functions", line 34, in main
    contigs_db = dbops.ContigsDatabase(args.contigs_db)
  File "/Users/alonshaiber/github/anvio/anvio/dbops.py", line 1823, in __init__
    self.init()
  File "/Users/alonshaiber/github/anvio/anvio/dbops.py", line 1834, in init
    self.meta[key] = int(self.meta[key])
KeyError: 'kmer_size'
```

**Comment by ozcan** [comment]
Can not reproduce this Alon, this code looks correct but I think there is something wrong with your contigs.db. There should be `kmer_size` in `self` table.

Can you check using `sqlite3 CONTIGS.db "SELECT * FROM self"` is there `kmer_size` in the output?

**Comment by minna-miha** [comment]
@ozcan hi there,

I have a very similar issue to @ShaiberAlon (only when running` anvi-gen-genomes-storage`). When I run `sqlite3 CONTIGS.db "SELECT * FROM self"` there is no kmer_size in the output. What should I do about this?
