### ISSUE TITLE
bug when running `anvi-pan-genome -h`

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#640]
Hi,

using the master here is a bug I found when running:
**anvi-pan-genome -h**
Traceback (most recent call last):
  File "/Users/tomdelmonttdelmont/virtual-envs/anvio-master/anvio/bin/anvi-pan-genome", line 8, in <module>
    import anvio.panops as panops
  File "/Users/tomdelmonttdelmont/virtual-envs/anvio-master/anvio/anvio/panops.py", line 11, in <module>
    import pandas as pd
ImportError: No module named 'pandas'

Thanks for looking into it,

Tom

**Comment by ozcan** [comment]
Hey Tom, This is only problem in `master` users, we added this dependency to both requirements.txt and homebrew formula, you just need to run `pip install pandas==0.20.1`
