### ISSUE TITLE
error with "anvi-script-predict-CPR-genomes"

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#657]
Hi,

Using anvi'o 3-master on Minnie.

I have an error when trying to predict CPR genomes in a database of interest (note that the collection is stored in the CONTIGS.db, and that this project does not include any PROFILE.db at this point):

```
**anvi-script-predict-CPR-genomes -c DOGD_v1_CONTIGS.db -C DOGD_v1 classifier-CPR --report-only-cpr**
Auxiliary Data ...............................: Found: DOGD_v1_CONTIGS.h5 (v. 1)
Contigs DB ...................................: Initialized: DOGD_v1_CONTIGS.db (v. 9)
/groups/merenlab/virtual-envs/anvio-master/lib/python3.5/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/sandbox/anvi-script-predict-CPR-genomes", line 148, in <module>
    main(args)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/sandbox/anvi-script-predict-CPR-genomes", line 81, in main
    rf.initialize_classifier()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/learning.py", line 93, in initialize_classifier
    classifier_obj = pickle.load(open(self.classifier_object_path, 'rb'))
**UnicodeDecodeError: 'ascii' codec can't decode byte 0x8a in position 6: ordinal not in range(128)**
```

Thank you for looking into this,

Tom

**Comment by meren** [comment]
I can't reproduce this error :/

master is working well here.

But why is the collection in the contigs database?

**Comment by tdelmont** [comment]
Because I do not have any PROFILE.db, as stated in the issue....

I have combined many genomes into a single database, and would like to look for CPRs this way...

Tom

**Comment by meren** [comment]
> Because I do not have any PROFILE.db, as stated in the issue....

Since when that is an excuse when `anvi-profile` can generate a blank profile for any contigs database?

**Comment by tdelmont** [comment]
I created a blank PROFILE.db.
I then created a new collection using

```
anvi-import-collection -c DOGD_v1_CONTIGS.db -p PROFILE/PROFILE.db contigs_collection-to-import.txt -C DOGD --contigs-mode
Num contigs in the contigs database ..........: 122,701
Num splits in the contigs database ...........: 142,991
Num contigs in the input file ................: 122,701
Num bins the input file describes ............: 644
Num contigs both input file and the db has ...: 122,701

* 122701 of 122701 contig names in the input file that matched to contig names in
the database resolved into 142991 split names that described in 644 bins.
Collections ..................................: The collection "DOGD" that describes 142,991 splits has been successfully added to the database at "PROFILE/PROFILE.db".
```
and then tried to predict CPRs using

```
anvi-script-predict-CPR-genomes -c DOGD_v1_CONTIGS.db -C DOGD classifier-CPR --report-only-cpr -p PROFILE/PROFILE.db
Auxiliary Data ...............................: Found: DOGD_v1_CONTIGS.h5 (v. 1)
Contigs DB ...................................: Initialized: DOGD_v1_CONTIGS.db (v. 9)
/groups/merenlab/virtual-envs/anvio-master/lib/python3.5/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/sandbox/anvi-script-predict-CPR-genomes", line 148, in <module>
    main(args)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/sandbox/anvi-script-predict-CPR-genomes", line 81, in main
    rf.initialize_classifier()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/learning.py", line 93, in initialize_classifier
    classifier_obj = pickle.load(open(self.classifier_object_path, 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8a in position 6: ordinal not in range(128)
```

So, unfortunately I have the same issue. I will make these files available to you, Meren, in case you have time looking into it.

Thanks,

Tom
