### ISSUE TITLE
anvi-self-test pysam traceback

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#659]
For whatever reason, anvio decided it was going to stop working on my computer and give me traceback errors. I uninstalled everything, and reinstalled it twice. From brew and the active codebase. I still get a traceback error.

```
anvi-self-test --version
Anvi'o version ...............................: 3-master
Profile DB version ...........................: 21
Contigs DB version ...........................: 9
Pan DB version ...............................: 6
Samples information DB version ...............: 2
Genome data storage version ..................: 4
Auxiliary data storage version ...............: 1

Traceback (most recent call last):
  File "/Users/rbartelme/virtual-envs/anvio-dev/bin/anvi-init-bam", line 4, in <module>
    __import__('pkg_resources').run_script('anvio===3-master', 'anvi-init-bam')
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-3_master-py3.6-macosx-10.9-x86_64.egg/EGG-INFO/scripts/anvi-init-bam", line 6, in <module>
    import pysam
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:7724)
ImportError: dlopen(/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so, 2): Library not loaded: @rpath/pysam/libcsamtools.cpython-36m-darwin.so
  Referenced from: /Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so
  Reason: image not found


Config Error: It seems something went wrong while running your tests :/ Anvi'o hopes that the
              reason is clear from the lines above.
```

**Comment by rbartelme** [comment]
I should also add, I can still open pangenome db's, but the self-test isn't working.

**Comment by rbartelme** [comment]
However, when I try to run anvi-summarize on the pangenome db I get another traceback.

Traceback (most recent call last):                                                                                                                                                                                                                                              
  File "/Users/rbartelme/virtual-envs/anvio-dev/bin/anvi-summarize", line 4, in <module>
    __import__('pkg_resources').run_script('anvio===3-master', 'anvi-summarize')
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-3_master-py3.6-macosx-10.9-x86_64.egg/EGG-INFO/scripts/anvi-summarize", line 96, in <module>
    main(args)
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-3_master-py3.6-macosx-10.9-x86_64.egg/EGG-INFO/scripts/anvi-summarize", line 59, in main
    summary.process()
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-3_master-py3.6-macosx-10.9-x86_64.egg/anvio/summarizer.py", line 265, in process
    ('Minbit parameter', self.p_meta['minbit']),
KeyError: 'minbit'

**Comment by meren** [comment]
The first error is independent from the second. 

I don't know what to suggest for the first one. @ozcan, do you have any idea?

**Comment by ozcan** [comment]
Hey Ryan,

Which version of pysam you have? I checked the pypi and realized that we are using old version of pysam (since it works alright, we didn't changed it). Maybe in your situation installing more recent versions may work, also we are going to release new version soon, so we may also upgrade to latest version if it is working okay.

**Comment by rbartelme** [comment]
I've tried it with both pysam 0.11 and 0.13, still get the same traceback.

**Comment by meren** [comment]
I say computer is break. Get new :(

**Comment by rbartelme** [comment]
Well I guess it only took 2 years for anvio to break my macbook.

**Comment by meren** [comment]
The second error (the minbit error) tells me that you are using an older version of `master`. What happened is, you got a copy of the master repo, installed it. master moved on, including a fix for that error you are getting, but then your installation remained the same.

One can **use** master, exactly the way it is explained here:

http://merenlab.org/2016/06/26/installation-v2/#installation-for-developers-youre-a-wizard-arry

But it seems you installed it, which no one should ever do :) That's why you have that weird 'minbit' error. It says `anvio/summarizer.py` line 256 has the line that goes like this:

```
('Minbit parameter', self.p_meta['minbit']),
```

But the actual current master has different stuff going on around that region of the file:

```
$ head -n 256 anvio/summarizer.py | tail -n 3
                'percent_of_genes_collection': 0.0,
                'genome_names': genome_names
        }
```

Does it make any sense?

**Comment by rbartelme** [comment]
That makes some sense! Play around in the master chain and you're bound to get burned I suppose.

**Comment by meren** [comment]
That is not the notion we want to promote :) We want people to play with master. But installing master is not a good idea. The link I sent you shows how to use master without installing it, and by getting the fresh copy of it every time you activate anvi'o.

This way when we fix something overnight, you have the fix the next day :)

**Comment by rbartelme** [comment]
Just to check if the traceback self-test issue is a master chain or v3 issue; it's both. I get the traceback error with installing v3 via the safe mode latest stable release.

(anvio-3) maroon:~ rbartelme$ anvi-self-test --suite mini


:: Output directory ...

/var/folders/6j/psc268nx78q548bfd24xm6140000gn/T/tmpo1kphvlh/test-output



:: Anvo'o version ...

Anvi'o version ...............................: 3
Profile DB version ...........................: 20
Contigs DB version ...........................: 9
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 4
Anvi'server users data storage version .......: 1


:: Initializing raw BAM files ...

Traceback (most recent call last):
  File "/Users/rbartelme/virtual-envs/anvio-3/bin/anvi-init-bam", line 6, in <module>
    import pysam
  File "/Users/rbartelme/virtual-envs/anvio-3/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:7724)
ImportError: dlopen(/Users/rbartelme/virtual-envs/anvio-3/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so, 2): Library not loaded: @rpath/pysam/libcsamtools.cpython-36m-darwin.so
  Referenced from: /Users/rbartelme/virtual-envs/anvio-3/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so
  Reason: image not found


Config Error: It seems something went wrong while running your tests :/ Anvi'o hopes that the
              reason is clear from the lines above.

**Comment by rbartelme** [comment]
The pysam traceback is also a problem when I try to make a plank profile db:

Traceback (most recent call last):
  File "/Users/rbartelme/virtual-envs/anvio-dev/bin/anvi-profile", line 4, in <module>
    __import__('pkg_resources').run_script('anvio===3-master', 'anvi-profile')
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-3_master-py3.6-macosx-10.9-x86_64.egg/EGG-INFO/scripts/anvi-profile", line 5, in <module>
    import anvio.profiler
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/anvio-3_master-py3.6-macosx-10.9-x86_64.egg/anvio/profiler.py", line 8, in <module>
    import pysam
  File "/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:7724)
ImportError: dlopen(/Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so, 2): Library not loaded: @rpath/pysam/libcsamtools.cpython-36m-darwin.so
  Referenced from: /Users/rbartelme/virtual-envs/anvio-dev/lib/python3.6/site-packages/pysam/libcutils.cpython-36m-darwin.so
  Reason: image not found

**Comment by ozcan** [comment]
Hey Ryan,

According to this page https://github.com/pysam-developers/pysam/issues/475#issuecomment-325200865 version `0.12` works properly on some users. Can you try that version also?

**Comment by rbartelme** [comment]
OSX seems to be the issue. 10.9.5 is too out of date to compile pysam properly.

**Comment by jjscarpa** [comment]
FYI I was having a similar problem with pysam/self-test on OSX 10.10.5. The  pysam-developers fix mentioned by @ozcan worked and the self-test ran without incident

**Comment by rbartelme** [comment]
Maybe my version of samtools is out of date? I have samtools 1.3
Using htslib 1.3

**Comment by ozcan** [comment]
Hey @rbartelme,
Have you tried `pysam==0.12`? It seems that is the only version that works for some users.

**Comment by meren** [comment]
sorry :(

I have no clue why it has to be so much pain with it. keep us posted please.

**Comment by rbartelme** [comment]
So I used rm -r on the anvio dir, and the virtual-env for anvi-dev, rebuilt the virtual env, and re-cloned the git. When I manually changed the Requirements.txt line for pysam to pysam==0.12, the self-test worked. Maybe it's as simple as updating the requirements.txt? I don't know who all would have issues with not using 0.11.1??

**Comment by meren** [comment]
Should we just update the requirements, @ozcan? Can we make sure 0.12 also works for everyone else?

**Comment by nakeene** [comment]
Hello, I am trying to install the latest Anvio version (5.2) on an HPC system using Conda and Linuxbrew and am having a pysam traceback error during the anvi-self-test every time that looks a little different than those reported above. I have used the following instructions for installation:
```
conda create -y --name anvio5 python=3.6
conda install -y --name anvio5 django=2.0.2
conda install -y --name anvio5 -c bioconda -c conda-forge anvio=5 diamond bwa 
```
I have tried installing with different versions of pysam and nothing has worked so far. The output of 
anvi-self-test looks like this: 

```
$ anvi-self-test --suite mini

:: Output directory ...

/tmp/tmpjcn5r4m5/test-output

:: Anvo'o version ...

Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

:: Initializing raw BAM files ...

Traceback (most recent call last):
  File "/home/GLBRCORG/nakeene/bin/miniconda3/envs/anvio5/bin/anvi-init-bam", line 6, in <module>
    import pysam
  File "/opt/bifxapps/python/lib/python2.7/site-packages/CrossMap-0.2.2-py2.7-linux-x86_64.egg/pysam/__init__.py", line 1, in <module>
    from pysam.csamtools import *
ImportError: /opt/bifxapps/python/lib/python2.7/site-packages/CrossMap-0.2.2-py2.7-linux-x86_64.egg/pysam/csamtools.so: undefined symbol: _Py_ZeroStruct


Config Error: It seems something went wrong while running your tests :/ Anvi'o hopes that the
              reason is clear from the lines above.                                          


(anvio5) 

```

Help!

**Comment by meren** [comment]
Your error log suggests the import request from anvi-init-bam, running by Python3, is responded by a package compiled with Python2 (and causing linkage errors, as you would expect). This should never happen in a properly configured system.
