### ISSUE TITLE
anvi-run-ncbi-cogs failure

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#673]
This is an example error:

```
Traceback (most recent call last):
  File "/Users/meren/github/anvio/bin/anvi-run-ncbi-cogs", line 49, in <module>
    main(args)
  File "/Users/meren/github/anvio/bin/anvi-run-ncbi-cogs", line 28, in main
    cogs.process()
  File "/Users/meren/github/anvio/anvio/cogs.py", line 121, in process
    self.store_hits_into_contigs_db()
  File "/Users/meren/github/anvio/anvio/cogs.py", line 153, in store_hits_into_contigs_db
    COG_ids = cogs_data.p_id_to_cog_id[ncbi_protein_id]
KeyError: '375255595'
```

**Comment by meren** [comment]
@ozcan, can you please test an up-to-date master on Chris Triverdi's contigs database and see whether this commit addresses the issue?

I couldn't find out what really might be happening, but I put in a workaround.

If `anvi-run-ncbi-cogs` is working without an issue on Chris' contigs database, feel free to close the issue and send a message to the thread explaining the fact that the issue is resolved in `master` :)

Thanks!

**Comment by weihongying** [comment]
Hi, can you tell me if the error resolved? How to do?
