### ISSUE TITLE
`anvi-pan-genome` fail with `KeyError: 'gene_lengths'`

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#691]
When running on internal genomes.
The contigs database was originally version 8 and was migrated to version 10
The profile database was v20 and migrated to v23.
I wonder if the migration caused this problem.

Here is the error (I'm also including the warning before the error just in case it has anything to do with this):
```
WARNING
===============================================
BLAST did not retun search results for 1 of 32808 the amino acid sequences in
your input FASTA file. Anvi'o will do some heuristic magic to complete the
missing data in the search output to recover from this. But since you are a
scientist, here are the amino acid sequence IDs for which BLAST failed to report
self search results: 0cca00522fdc_23615.

Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-pan-genome", line 109, in <module>
    pan.process()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/panops.py", line 767, in process
    mcl_input_file_path = self.gen_mcl_input(blastall_results)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/panops.py", line 334, in gen_mcl_input
    self_bit_scores[id_without_self_search] = (self.genomes[genome_name]['gene_lengths'][int(gene_caller_id)] / 3.0) * 2
KeyError: 'gene_lengths'
```

**Comment by meren** [comment]
Do you happen to have original versions of these database prior to the upgrade, Alon? Not that you should, but I am just curious :)

I will look into this today!

**Comment by ShaiberAlon** [comment]
Unfortunately I don't.

**Comment by meren** [comment]
Good news, it wasn't about the migration. Better news, now it is fixed :)

**Comment by ShaiberAlon** [comment]
Thank you Meren!
I'll rerun this.
