### ISSUE TITLE
error while binning gene clusters

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#700]
Here is the error with colors:
![image](https://user-images.githubusercontent.com/17661044/35164382-cb36b05c-fd0f-11e7-8d44-b1ab08974d5d.png)

and here it is in the text:

```bash
[19 Jan 18 11:45:39 Loading contig sequences] Reading contig sequences                                                                      * Gene cluster info has been requested for 1 items in Bin_2
Traceback (most recent call last):
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/Users/alonshaiber/github/anvio/anvio/bottleroutes.py", line 709, in inspect_gene_cluster
    AA_sequences = self.interactive.get_sequences_for_gene_clusters(gene_cluster_names=set([gene_cluster_name]))
  File "/Users/alonshaiber/github/anvio/anvio/dbops.py", line 948, in get_sequences_for_gene_clusters
    self.progress.new('Accessing gene cluster seqeunces')
  File "/Users/alonshaiber/github/anvio/anvio/terminal.py", line 77, in new
    raise TerminalError("Progress.new() can't be called before ending the previous one (Existing: '%s', Competing: '%s')." % (self.pid, pid))
anvio.errors.TerminalError:

Terminal Error: Progress.new() can't be called before ending the previous one (Existing: '19 Jan
                18 11:45:39 Loading contig sequences', Competing: 'Accessing gene cluster
                seqeunces').


* Gene cluster info has been requested for 0 items in Bin_2
Traceback (most recent call last):
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/Users/alonshaiber/github/anvio/anvio/bottleroutes.py", line 709, in inspect_gene_cluster
    AA_sequences = self.interactive.get_sequences_for_gene_clusters(gene_cluster_names=set([gene_cluster_name]))
  File "/Users/alonshaiber/github/anvio/anvio/dbops.py", line 948, in get_sequences_for_gene_clusters
    self.progress.new('Accessing gene cluster seqeunces')
  File "/Users/alonshaiber/github/anvio/anvio/terminal.py", line 77, in new
    raise TerminalError("Progress.new() can't be called before ending the previous one (Existing: '%s', Competing: '%s')." % (self.pid, pid))
anvio.errors.TerminalError:

Terminal Error: Progress.new() can't be called before ending the previous one (Existing: '19 Jan
                18 11:45:39 Loading contig sequences', Competing: 'Accessing gene cluster
                seqeunces').
```

**Comment by ShaiberAlon** [comment]
This also happened (in this case I didn't do any binning)
![image](https://user-images.githubusercontent.com/17661044/35164886-cddd7406-fd11-11e7-93a4-f0d22ac12b1a.png)
