### ISSUE TITLE
error in anvi-import-misc-data when importing layers data with missing data

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#723]
I was importing the following table:
[MCG-samples-information.txt](https://github.com/merenlab/anvio/files/1683513/MCG-samples-information.txt)

It looks similar to this issue: #707

```
Traceback (most recent call last):
  File "/Users/alonshaiber/github/anvio/bin/anvi-import-misc-data", line 44, in <module>
    main(args)
  File "/Users/alonshaiber/github/anvio/bin/anvi-import-misc-data", line 25, in main
    MiscDataTableFactory(args).populate_from_file(args.data_file)
  File "/Users/alonshaiber/github/anvio/anvio/tables/miscdata.py", line 87, in populate_from_file
    AdditionalDataBaseClass.add(self, data_dict, data_keys, skip_check_names)
  File "/Users/alonshaiber/github/anvio/anvio/tables/miscdata.py", line 469, in add
    type_class = utils.get_predicted_type_of_items_in_a_dict(data_dict, key)
  File "/Users/alonshaiber/github/anvio/anvio/utils.py", line 181, in get_predicted_type_of_items_in_a_dict
    if int(item or 0) == float(item):
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by meren** [comment]
This should fix this. Sorry about that.

**Comment by ShaiberAlon** [comment]
Thank you!
