### ISSUE TITLE
unhelpful error when using empty 

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#728]
This is related to #498 

When I use an empty file named `noise_cutoff_terms.txt`, I was hoping that anvio would understand that I just want the default `--cut-ga, but instead I got this:

```
Traceback (most recent call last):
  File "/Users/alonshaiber/github/anvio/bin/anvi-run-hmms", line 85, in <module>
    main(args)
  File "/Users/alonshaiber/github/anvio/bin/anvi-run-hmms", line 47, in main
    sources = utils.get_HMM_sources_dictionary([args.hmm_profile_dir])
  File "/Users/alonshaiber/github/anvio/anvio/utils.py", line 1824, in get_HMM_sources_dictionary
    noise_cutoff_terms = R('noise_cutoff_terms.txt')
  File "/Users/alonshaiber/github/anvio/anvio/utils.py", line 1801, in <lambda>
    R = lambda f: open(os.path.join(source, f), 'rU').readlines()[0].strip()
IndexError: list index out of range
```

**Comment by meren** [comment]
I'm on this.
