### ISSUE TITLE
if there is no clustering (tree data) available, anvi'o should still be able to visualize

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#73]
Fixing #68 made two new params available. However, currently PaPi is unable to visualize runs _unless_ papi-profile was run _with_ `--cluster-contigs`, and papi-merge was run _without_ `--skip-clustering`.

So if you do this:

```
cd tests/mini_test/test-output
papi-profile -i 204-7M.bam -o 204-7M -a ANNOTATION.db
papi-interactive -r 204-7M/RUNINFO.cp -a ANNOTATION.db
```

you will get this error:

```
Traceback (most recent call last):
  File "/Users/meren/Desktop/MBL/PaPi/bin/papi-interactive", line 88, in <module>
    d = interactive.InputHandler(parser.parse_args())
  File "/Users/meren/Desktop/MBL/PaPi/PaPi/interactive.py", line 82, in __init__
    tree = Tree(self.runinfo['clusterings'][self.runinfo['default_clustering']]['newick'])
KeyError: 'default_clustering'
```

Likewise, you will get the same error if you do this:

```
cd tests/mini_test/test-output/
papi-merge 204*/RUNINFO.cp -o test-output/204-MERGED --skip-clustering
papi-interactive -r 204-MERGED/RUNINFO.mcp -a ANNOTATION.db
```

PaPi should be able to operate if there is no clustering available. For instance, instead of a tree, it can show contigs ordered by name (or based on a user-provided order).

**Comment by meren** [comment]
this was fixed at some point.
