### ISSUE TITLE
anvi-pan-genome error during Aligning amino acid sequences for genes in gene cluste (...)

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#735]
```
Anvi'o version ...............................: 3-master
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
```

Running the command `anvi-pan-genome -g BRUCELLA-GENOMES.db -n BRUCELLA -T 31 --use-ncbi-blast -o PAN` in `/storage/data/00_Collaborations/LydiaVaresio/PANGENOME`yields the following error

```
[05 Feb 18 00:07:31 Aligning amino acid sequences for genes in gene cluste (...)Process Process-19:
Traceback (most recent call last):
  File "/bioware/python-3.5.1-201606221454/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/bioware/python-3.5.1-201606221454/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/panops.py", line 784, in alignment_worker
    alignments = aligner(run=r).run_stdin(gene_sequences_in_gene_cluster)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/drivers/muscle.py", line 64, in run_stdin
    if not output[0] == '>':
IndexError: string index out of range
Process Process-31:
Traceback (most recent call last):
  File "/bioware/python-3.5.1-201606221454/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/bioware/python-3.5.1-201606221454/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/panops.py", line 784, in alignment_worker
    alignments = aligner(run=r).run_stdin(gene_sequences_in_gene_cluster)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/drivers/muscle.py", line 64, in run_stdin
    if not output[0] == '>':
IndexError: string index out of range
[05 Feb 18 00:07:31 Aligning amino acid sequences for genes in gene cluste (...)
```

**Comment by ozcan** [comment]
looking into this, it may be related to recent multiprocessing things changed

**Comment by ozcan** [comment]
We worked on this issue and found out that some genes are ridiculously long in some genomes and contains mostly N.

If you run 
`for i in */*-clean.fa; do echo $i; awk -vFS="" '{for(i=1;i<=NF;i++)w[$i]++}END{for(i in w) print i,w[i]}' $i | grep N; done`
inside 
`/storage/data/00_Collaborations/LydiaVaresio/PANGENOME/FASTAS` 

you can see N counts in genomes.
Some examples:
```
29459.399/29459.399-clean.fa
N 59254
235.94/235.94-clean.fa
N 14044
235.95/235.95-clean.fa
N 72442
235.96/235.96-clean.fa
N 29607
235.97/235.97-clean.fa
N 261642
235.98/235.98-clean.fa
N 353223
235.99/235.99-clean.fa
N 21320
```

**Comment by meren** [comment]
We haven't fully resolve this, but there isn't much we can do for broken input files except boring heuristics either :/
