### ISSUE TITLE
Bottle error while running self-test

### ISSUE THREAD

**Issue by dcourtine** [merenlab/anvio#785]
Hi anvi'o team!

This morning, I installed the v4 from the master repo, on our server(CentOS) (last commit: 80f0b50d92d600de878a4ceb59368c3e1b1008fa)

While running `anvi-self-test --suite full`, I have this error:
```
:: A dry run with an items order file for the merged profile without any clustering ...

Contigs DB ...................................: Initialized: /var/folders/z2/y6swh1w13l72d708rk2ds3p40000gp/T/tmpr8lyudkw/test-output/CONTIGS.db (v. 10)
Taxonomy .....................................: Initiated for taxonomic level for "t_genus"
Interactive mode .............................: full
Auxiliary Data ...............................: Found: /var/folders/z2/y6swh1w13l72d708rk2ds3p40000gp/T/tmpr8lyudkw/test-output/SAMPLES-MERGED/AUXILIARY-DATA.db (v. 2)
Profile Super ................................: Initialized with all 35 splits: /var/folders/z2/y6swh1w13l72d708rk2ds3p40000gp/T/tmpr8lyudkw/test-output/SAMPLES-MERGED/PROFILE.db (v. 23)
Items order ..................................: An items order with 35 items is found at sandbox/example_items_order_file.txt.
* Dry run, eh? Fine. Bai!

:: Firing up the interactive interface to display the contigs db stats ...

Traceback (most recent call last):
  File "/Users/courtine/GitHub/anvio/bin/anvi-display-contigs-stats", line 71, in <module>
    app = BottleApplication(d)
  File "/Users/courtine/GitHub/anvio/anvio/bottleroutes.py", line 64, in __init__
    self.args = self.interactive.args
AttributeError: 'ContigsInteractive' object has no attribute 'args'

Config Error: It seems something went wrong while running your tests :/ Anvi'o hopes that the
              reason is clear from the lines above.
```

I updated the version I have on my computer (Mac 10.10) and I get exactly the same error.
It seems to me that the bug line has been modified in the commit 80f0b50d92d600de878a4ceb59368c3e1b1008fa

Best,
Damien

**Comment by meren** [comment]
Hey Damien,

@ozcan is working on that part of the code making serious improvements, and some hiccups are expected :) So these reports are extremely helpful. Thank you for your patience with us! I'm sure this will get addressed very soon, and we will keep you posted through this issue.

**Comment by meren** [comment]
(taking advantage of the early morning quietness, I found the little bug and fixed it. thanks again, Damien)
