### ISSUE TITLE
Anvi-migrate-db DB 20 to 23 (contigDB)

### ISSUE THREAD

**Issue by weirdlobster** [merenlab/anvio#806]
I'm having an issue with anvi-migrate-db.

```
(anvio4) Matts-MacBook-Air:~ mattwright$ anvi-self-test --version
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
```

I was looking at an old metagenome from version 3 (and I had completely moved to V4), and it threw this error on my cluster, as well as my personal computer. When I tried to migrate on my cluster, I thought maybe my computer could try to save this version, so I transferred, and repeated the migrate...nope. I think I have to rebuild.

This is my error message:

```
(anvio4) weirdlob@crick:~/SPAdes/l3a/ChIPseq/anvio$ anvi-migrate-db metagenome.db 
Database Path ................................: metagenome.db
Detected Type ................................: contigs
Current Version ..............................: 9
Target Version ...............................: 10
Traceback (most recent call last):
  File "/share/apps/bio/miniconda2/envs/anvio4/bin/anvi-migrate-db", line 111, in <module>
    Migrater(args).process()
  File "/share/apps/bio/miniconda2/envs/anvio4/bin/anvi-migrate-db", line 92, in process
    migration_scripts[self.db_type][script_name].migrate(self.db_path)
  File "/share/apps/bio/miniconda2/envs/anvio4/lib/python3.6/site-packages/anvio/migrations/contigs/v9_to_v10.py", line 50, in migrate
    contigs_db.create_table(nt_position_info_table_name, nt_position_info_table_structure, nt_position_info_table_types)
  File "/share/apps/bio/miniconda2/envs/anvio4/lib/python3.6/site-packages/anvio/db.py", line 81, in create_table
    self._exec('''CREATE TABLE %s (%s)''' % (table_name, db_fields))
  File "/share/apps/bio/miniconda2/envs/anvio4/lib/python3.6/site-packages/anvio/db.py", line 169, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: table nt_position_info already exists
```

And then this is after I transferred the aforementioned-error database to my laptop and tried it again:

```
Database Path ................................: metagenome.db
Detected Type ................................: contigs
Current Version ..............................: 8
Target Version ...............................: 10
* The anvi'o contigs database has just been updated with a description that                                                                                                                                 
contains 4 words and 23 characters.

* The contigs database is now 9! All this upgrade did was to associate your
contigs db with a project name (which happened to be 'NO_NAME', because anvi'o
likes you very much)

Traceback (most recent call last):
  File "/Users/mattwright/anaconda/envs/anvio4/bin/anvi-migrate-db", line 111, in <module>
    Migrater(args).process()
  File "/Users/mattwright/anaconda/envs/anvio4/bin/anvi-migrate-db", line 92, in process
    migration_scripts[self.db_type][script_name].migrate(self.db_path)
  File "/Users/mattwright/anaconda/envs/anvio4/lib/python3.6/site-packages/anvio/migrations/contigs/v9_to_v10.py", line 52, in migrate
    contig_names_in_db = list(fp['/data/nt_position_info'].keys())
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/mattwright/anaconda/envs/anvio4/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
```

Guess I won't be seeing my metagenome tonight.

The profile migration worked fine i think, no errors raised.

**Comment by meren** [comment]
Sorry about this, Matt. Ozcan and I discussed this a bit. 
```
sqlite3.OperationalError: table nt_position_info already exists
```

The only way the error above makes sense is this: you tried to upgrade `metagenome.db` and it failed for some reason, and this is your second try. That's why when you download it again, it gives you a different error.

Are you downloading `metagenome.db` along with the `metagenome.h5` file? If you have not been doing it that way, please try it that way, and please report back.

**Comment by weirdlobster** [comment]
Yes: I updated the database, and it failed for some reason, on both versions (the server and my computer had identical copies). The .h5 file was present for both of them.

**Comment by meren** [comment]
Weird. If you can give us access to the original contigs database and the h5 file, we could take a look into this and figure out what is wrong.

**Comment by meren** [comment]
No longer relevant :)
