### ISSUE TITLE
key error in anvi-summarize

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#814]
```
$ anvi-interactive -v
Anvi'o version ...............................: 4-master, "rosalind"
Profile DB version ...........................: 25
Contigs DB version ...........................: 11
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
```

This is the error I get:
```
Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 96, in <module>
    main(args)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 60, in main
    summary.process()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 852, in process
    self.summary['collection'][bin_id] = bin.create()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 1206, in create
    self.summarize_hmm_hits()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 1297, in summarize_hmm_hits
    info_dict[hmm_search_source][hmm_item] += 1
KeyError: 'Chlor_Acetyltrans_CAT'
Job exit status: 1
Warning: job exited non-zero: 1
```

**Comment by ShaiberAlon** [comment]
Closing this issue, because there is a better issue (#815) that describes the root of the problem.
