### ISSUE TITLE
TypeError in anvi-summarize

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#847]
```
Anvi'o version ...............................: 4-master, "rosalind"
Profile DB version ...........................: 27
Contigs DB version ...........................: 12
Pan DB version ...............................: 10
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
```

`anvi-summarize -p 03_PAN/BrucellaPangenome-PAN.db -g 03_PAN/BrucellaPangenome-GENOMES.db -C DEFAULT` yields

```
Genomes storage .............................................: Initialized (storage hash: hash93fa04fd)
Num genomes in storage ......................................: 100
Num genomes will be used ....................................: 100
Pan DB ......................................................: Initialized: 03_PAN/BrucellaPangenome-PAN.db (v. 10)

* Gene clusters are initialized for all 4607 gene clusters in the database.

Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 96, in <module>
    main(args)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 60, in main
    summary.process()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 556, in process
    self.generate_gene_clusters_file(collection_dict)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 577, in generate_gene_clusters_file
    output_file_obj = self.get_output_file_handle(prefix='gene_clusters_summary.txt', compress_output=compress_output, add_project_name=True)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 171, in get_output_file_handle
    if not os.path.exists(output_directory):
  File "/groups/merenlab/virtual-envs/anvio-master/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Job exit status: 1
```

working directory in github slack channel

**Comment by meren** [comment]
Thanks for the report!
