### ISSUE TITLE
Trouble running anvi-display-contig-stats with own HMMs

### ISSUE THREAD

**Issue by sulfuriscool** [merenlab/anvio#901]
Hi!

We followed this [tutorial](http://merenlab.org/2016/05/21/archaeal-single-copy-genes/) to generate and run our own HMM profiles using `anvi-run-hmms`.
The scan was successful:
```
HMM profiles .................................: 1 source been loaded: hmms (9 genes)
Target found .................................: AA:GENE   [0m
Contigs DB ...................................: Initialized: assembly/MERGED_ASSEMBLY/MERGED_DB/contigs.db (v. 10)
                                                                         [0m
WARNING
===============================================
23 entries in the sequences table had blank sequences :/ This is related to the
issue at https://github.com/merenlab/anvio/issues/565. If this is like mid-2018
and you still get this warning, please find an anvi'o developer and make them
feel embarrassed. If it is earlier than take this as a simple warning that some
gene calls in your downstream analyses may have no sequences, and that's OK.
This is a very minor issue due to on-the-fly addition of Ribosomal RNA gene
calls to the contigs database, and will likely will not affect anything major.
This warning will go away when anvi'o can seamlessly work with multiple gene
callers (which we are looking forward to implement in the future).

Sequences ....................................: 51219 sequences reported.
FASTA ........................................: /tmp/tmpt7tf5hp0/aa_gene_sequences.fa

HMM Profiling for hmms
===============================================
Reference ....................................: github.com/sulfuriscool
Kind .........................................: singlecopy
Alphabet .....................................: AA
Context ......................................: GENE
Domain .......................................: N\A
HMM model path ...............................: hmms/genes.hmm.gz
Number of genes ..............................: 9
Noise cutoff term(s) .........................: -E 1e-12
Number of CPUs will be used for search .......: 20
Temporary work dir ...........................: /tmp/tmpedhtulv4
HMM scan output ..............................: /tmp/tmpedhtulv4/hmm.output
HMM scan hits ................................: /tmp/tmpedhtulv4/hmm.hits
Log file .....................................: /tmp/tmpedhtulv4/00_log.txt
Number of raw hits ...........................: 265       [0m
```
However, when we tried to run `anvi-display-contig-stats`, we ran into this error.
```
[06 Jul 18 16:25:34 Generating stats tables] Num genome prediction ...         Traceback (most recent call last):
  File "/summer2018/anaconda3/bin/anvi-display-contigs-stats", line 64, in <module>
    d = interactive.ContigsInteractive(args)
  File "/summer2018/anaconda3/lib/python3.6/site-packages/anvio/interactive.py", line 1229, in __init__
    self.generate_tables()
  File "/summer2018/anaconda3/lib/python3.6/site-packages/anvio/interactive.py", line 1309, in generate_tables
    line = [source_to_domain[source] + ' (' + source + ')']
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Before adding in our HMMs, we were able to run the above command successfully. Do you have any suggestions on fixing this issue? Thanks for the help!

Best, 
Sulfuriscool

**Comment by meren** [comment]
Can you please send your zipped HMM source directory so we can quickly reproduce this?

It is likely that you are missing some information in your essential files in the HMM directory.

**Comment by sulfuriscool** [comment]
Yes, here is the directory containing our HMM files.

[hmms.tar.gz](https://github.com/merenlab/anvio/files/2177625/hmms.tar.gz)

**Comment by meren** [comment]
I am on anvi'o `v5.1`, and I am not getting the error you are getting. Mine says this:

```
$ anvi-run-hmms -c CONTIGS.db -H ~/Downloads/hmms


Config Error: This HMM profile seems to be a collection of single-copy core genes. Great. But
              for this kind, you must also declare a 'domain' in your 'kind.txt' file. It is
              simple. For instance, you could use 'singlecopy:bacteria', or
              'singlecopy:archaea', or 'singlecopy:myspecificbranch'.

```

When I do this:

```
echo "therearecertainlynotsinglecopycoregenes" > ~/Downloads/hmms/kind.txt
```

And then run again, this time I am getting this error:

```
$ anvi-run-hmms -c CONTIGS.db -H ~/Downloads/hmms


Config Error: Some gene names in genes.txt file does not seem to be appear in genes.hmm.gz.
              Here is a list of missing gene names: dsrA, RplB, dsrB

```

When I remove those genes from the `genes.txt` and run again, I get this:

```
$ anvi-run-hmms -c CONTIGS.db -H ~/Downloads/hmms
HMM profiles .................................: 1 source been loaded: hmms (6 genes)
Target found .................................: AA:GENE
Contigs DB ...................................: Initialized: CONTIGS.db (v. 12)

WARNING
===============================================
You did not provide any gene caller ids. As a result, anvi'o will give you back
sequences for every 51 gene call stored in the contigs database.

Output .......................................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmpthap_o_0/AA_gene_sequences.fa

HMM Profiling for hmms
===============================================
Reference ....................................: github.com/sulfuriscool
Kind .........................................: therearecertainlynotsinglecopycoregenes
Alphabet .....................................: AA
Context ......................................: GENE
Domain .......................................: N\A
HMM model path ...............................: /Users/meren/Downloads/hmms/genes.hmm.gz
Number of genes ..............................: 6
Noise cutoff term(s) .........................: -E 1e-12
Number of CPUs will be used for search .......: 1
Temporary work dir ...........................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp4txcnq9o
HMM scan output ..............................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp4txcnq9o/hmm.output
HMM scan hits ................................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp4txcnq9o/hmm.hits
Log file .....................................: /var/folders/x5/gt4031w53fs63csv1fp0r_3w0000gn/T/tmp4txcnq9o/00_log.txt
Number of raw hits ...........................: 0

* The HMM source 'hmms' returned 0 hits. SAD (but it's stil OK).
```

Which is normal since my contigs database is a mock one.

You are not using the best anvi'o version available (and I missed that because despite the template in new issue window that asks you specifically to mention the anvi'o version you are using, you didn't report it).

**Comment by sulfuriscool** [comment]
I think `anvi-run-hmms` worked for us too. Did you have any issues when performing  `anvi-display-contigs-stats`?

**Comment by meren** [comment]
No I did not :)
