### ISSUE TITLE
Error installing 5.1 - ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Klcross** [merenlab/anvio#909]
Hello,

I am trying to locally install Anvio 5.1 on my Mac OS High Sierra and I keep getting an error about numpy that I can't seem to get around and am not sure if it is due to paths locally or something that I am missing. Here is the information from where I start with an installation using homebrew:

**karissas-mbp**:~ ikf$ anvi-self-test --version
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

**karissas-mbp**:~ ikf$ brew install anvio
==> Installing anvio from merenlab/anvio
Error: anvio 5 is already installed
To upgrade to 5.1, run `brew upgrade anvio`

**karissas-mbp**:~ ikf$ brew upgrade anvio
==> Upgrading 1 outdated package, with result:
merenlab/anvio/anvio 5 -> 5.1
==> Upgrading merenlab/anvio/anvio 
==> Installing dependencies for merenlab/anvio/anvio: gdbm, readline, python, numpy, scipy
==> Installing merenlab/anvio/anvio dependency: gdbm
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.16.high_sierra.bottl
######################################################################## 100.0%
==> Pouring gdbm-1.16.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gdbm/1.16: 19 files, 578.5KB
==> Installing merenlab/anvio/anvio dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-7.0.5.high_sierra.
######################################################################## 100.0%
==> Pouring readline-7.0.5.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/7.0.5: 46 files, 1.5MB
==> Installing merenlab/anvio/anvio dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.0.high_sierra.bo
######################################################################## 100.0%
==> Pouring python-3.7.0.high_sierra.bottle.tar.gz
==> /usr/local/Cellar/python/3.7.0/bin/python3 -s setup.py --no-user-cfg install
==> /usr/local/Cellar/python/3.7.0/bin/python3 -s setup.py --no-user-cfg install
==> /usr/local/Cellar/python/3.7.0/bin/python3 -s setup.py --no-user-cfg install
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

Pip, setuptools, and wheel have been installed. To update them run
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.7.0: 4,788 files, 102.2MB
==> Installing merenlab/anvio/anvio dependency: numpy
==> Downloading https://files.pythonhosted.org/packages/d5/6e/f00492653d0fdf6497
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e2818
######################################################################## 100.0%
==> python2.7 -c import setuptools... --no-user-cfg install --prefix=/usr/local/
==> python2.7 setup.py build --fcompiler=gnu95 --parallel=8 install --prefix=/us
🍺  /usr/local/Cellar/numpy/1.14.5_1: 720 files, 16.7MB, built in 5 minutes 24 seconds
==> Installing merenlab/anvio/anvio dependency: scipy
==> Downloading https://homebrew.bintray.com/bottles/scipy-1.1.0_1.high_sierra.b
######################################################################## 100.0%
==> Pouring scipy-1.1.0_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/scipy/1.1.0_1: 2,034 files, 119.8MB
==> Installing merenlab/anvio/anvio
==> Downloading https://data.merenlab.org/homebrew-anvio/anvio-5.1.high_sierra.b
######################################################################## 100.0%
==> Pouring anvio-5.1.high_sierra.bottle.1.tar.gz
Warning: merenlab/anvio/anvio dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/anvio/5.1: 12,311 files, 227.7MB

**karissas-mbp**:~ ikf$ anvi-self-test --suite mini
Traceback (most recent call last):
  File "/usr/local/bin/anvi-self-test", line 13, in <module>
    import anvio.filesnpaths as filesnpaths
  File "/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/anvio/filesnpaths.py", line 12, in <module>
    import anvio.fastalib as u
  File "/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/anvio/fastalib.py", line 9, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

THANK YOU!
Karissa

**Comment by Klcross** [comment]
I managed to get around this problem when the conda environment came out by just creating a new conda environment and re-doing and updating everything:

`conda create --name anvio5.1 python=3
conda install -n anvio5.1 -c bioconda -c conda-forge anvio=5.1.0 diamond bwa`

One day I will learn how to install things in correct paths so as to avoid future disasters! You can close/delete this issue if you want.

Karissa
