### ISSUE TITLE
anvi-migrate-db .py script to be rerouted

### ISSUE THREAD

**Issue by sipesk** [merenlab/anvio#913]
Anvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

When I run an anvi-migrate-db with an external genome I get the following output.

$anvi-migrate-db NC_0106281_Nostoc_punctiforme_PCC_73102_complete_genome.db 
Database Path ................................: NC_0106281_Nostoc_punctiforme_PCC_73102_complete_genome.db
Detected Type ................................: contigs
Current Version ..............................: 10
Target Version ...............................: 12
Traceback (most recent call last):
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/bin/anvi-migrate-db", line 119, in <module>
    Migrater(args_for_single_db).process()
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/bin/anvi-migrate-db", line 93, in process
    migration_scripts[self.db_type][script_name].migrate(self.db_path)
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/lib/python3.5/site-packages/anvio/migrations/contigs/v10_to_v11.py", line 38, in migrate
    contigs_db._exec("DROP TABLE %s;" % genes_in_splits_summary_table_name)
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/lib/python3.5/site-packages/anvio/db.py", line 176, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: no such table: genes_in_splits_summary

I run the same command with a smaller data set and it is able to go. I know its because the current partition that the tmp folder lives in is much too small. I was wondering how I can resource the file path for the db.py script to output to a tmp file in another partition on my machine.

Thanks,
Katie

**Comment by ozcan** [comment]
Hi Katie,
If you set environment variable `TMPDIR` you can change temp path.

You can either change for shell session like below:

```export TMPDIR=/storage/path```

Or run a specific program with the new variable.

```
TMPDIR=/storage/path anvi-migrate-db xxxxx.db
```

Best,
