### ISSUE TITLE
Inspecting split isn't working

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#987]
I am trying to inspect a split in a metagenome with a blank profile but the page won't load in the new tab. 

The path to the contigs.db and profile.db are on slack.

This is the command I ran:
`anvi-interactive -p PROFILE.db -c CONTIGS.db`

This is the error message:
Auxiliary Data Error: Database does not know anything about split "FIJ00XX_0000000000XX_split_00001"

Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/groups/merenlab/virtual-envs/anvio-master/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/bottleroutes.py", line 468, in charts
    coverages = auxiliary_coverages_db.get(split_name)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/auxiliarydataops.py", line 116, in get
    raise AuxiliaryDataError('Database does not know anything about split "%s"' % split_name)

**Comment by meren** [comment]
It is normal that we can't inspect a split when we are working with a blank profile. 

I guess the solution is to make 'inspect' option unavailable in the interface :)
